### gensim 라이브러리 모델에서 GridSearchCV를 이용하는 방법
- sklearn에서 제공하는 GridSearchCV는 모델의 fit(), transform(), predict() 함수를 이용하여 최적의 매개변수의 값들을 찾는 class
- gensim의 모델들은 해당 함수들이 존재하지 않는다
- class를 새로 생성하여 fit(), transform(), predict() 함수를 내장한 객체를 생성
- pipeline, kfold, gridsearch를 이용

In [1]:
# 라이브러리 로드
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from gensim.models import FastText
from konlpy.tag import Komoran
import numpy as np

In [2]:
# Komoran 형태소 분석기를 이용한 토큰화 함수 정의
komoran = Komoran()
def tokenize():
    return lambda x : [t for t in komoran.morphs(x)]
tokenizer = tokenize()

In [3]:
# FastText를 fit(), transform()를 내장한 class 정의
class FastTextVectorizer(BaseEstimator, TransformerMixin):
    # 생성자 함수 -> class가 생성될떄 치초로 한번 실행이 되는 함수
    # class 내부에서 사용할 데이터들을 저장하기 위해 사용
    def __init__(
            self,
            # FastText에서 사용할 매개변수
            # 토큰화된 데이터 (2차원 리스트)
            # vector_size : (좌표축의 개수(차원의 수))
            # window : 주변의 체크할 단어의 개수
            # min_count : 최소 등장 횟수
            # epochs : 반복 학습의 횟수
            # sg : 확률 계산 방식 (주변단어를 찾을것인가 중심단어를 찾을것인가)
            # min_n : subword의 최소 개수(글자수)
            # max_n : subword의 최대 개수(글자수)
            # worker : 병렬 처리 스레드의 수
            tokenizer = None,
            vector_size = 100,
            min_count = 1,
            window = 3,
            sg = 1,
            epochs = 10,
            min_n = 3,
            max_n = 6,
            worker = 1
    ):
        # class 안에 저장공간을 생성하여 데이터들 저장
        self.tokenizer = tokenizer
        self.vector_size = vector_size
        self.window = window
        self.sg = sg
        self.epochs = epochs
        self.min_count = min_count
        self.min_n = min_n
        self.max_n = max_n
        self.worker = worker
        # 시드값 고정
        self.seed = 42

        # 모델이랑 단어 사전이 저장될 빈 공간을 생성
        self.model = None
        self.voca = None
        
    # 총 4개의 메서드를 생성
    # 토큰화 메서드
    def to_token(self, X):
        # 만약에 토큰화 함수가 존재하지 않는다면 공백을 기준으로 문자를 나눠준다
        if self.tokenizer is None:
            # s -> 문장 하나
            # t -> 문장안에서 단어
            return [ [t for t in s.split()] for s in X ]
        return [self.tokenizer(s) for s in X]
    
    # 학습 함수 -> fit(X, Y)
    def fit(self, X, Y):
        # class 내부의 to_token() 함수를 호출
        sentences = self.to_token(X)
        # FastText를 이용하여 sentences들을 학습
        self.model = FastText(
            sentences = sentences,
            vector_size = self.vector_size,
            window = self.window,
            min_count = self.min_count,
            sg = self.sg,
            epochs = self.epochs,
            min_n = self.min_n,
            max_n = self.max_n,
            workers = self.worker,
            seed = self.seed
        )
        # 학습한 후 학습 데이터에서의 단어사전 생성
        self.voca = set(self.model.wv.key_to_index.keys())
        return self
    
    # 문장에서 평균 벡터로 사용할 _doc_vec() 함수를 정의
    def doc_vec(self, tokens):
        # 하나의 문장을 벡터화 -> 단위 벡터의 평균
        # self.model -> FastText 모델
        # wv -> 단어들과 단위 벡터들이 모여있는 dict형태의 데이터
        vecs = [self.model.wv[w] for w in tokens if w in self.model.wv]
        if not vecs:
            # vecs가 존재하지 않은 경우 -> 빈 리스트인 경우
            # 희소행렬을 되돌려준다
            v = np.zeros(self.model.vector_size)
        else:
            v = np.mean(vecs, axis=0)
        return v
    
    # 변형함수 정의 (transform 함수)
    def transform(self, X):
        # 토큰화
        sentences = self.to_token(X)
        # 임베딩
        mat = np.vstack([self.doc_vec(tokens) for tokens in sentences])
        return mat

In [4]:
# 1차 class 테스트
X = [
    '상품 품질이 아주 좋다',
    '배송이 너무 느리다',
    '포장이 잘되어 있고 만족합니다',
    '환불이 오래 걸려서 불안하다',
    '가격 대비 만족스럽다',
    '연락이 잘 안 되고 불친절하다',
    '디자인이 예쁘고 마음에 든다',
    '설명과 달라서 실망이다',
    '배송이 빠르고 기사분이 친절했습니다',
    '색상이 사진과 달라서 만족하지 못했습니다'
]
Y = [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [5]:
vec_data = FastTextVectorizer(tokenizer=tokenizer)

In [6]:
vec_data.fit(X, Y)

FastTextVectorizer(tokenizer=<function tokenize.<locals>.<lambda> at 0x000001ADED2F1C60>)

In [7]:
# transform 함수 테스트
vec_data.transform(X)

array([[-5.96644531e-04, -7.28217885e-04,  3.52308089e-05,
         1.08762376e-03,  7.21835066e-04,  9.30204056e-04,
        -1.55889057e-03,  2.79799756e-03, -2.47293301e-05,
        -1.56941859e-03,  1.65195775e-03, -7.28901185e-04,
         2.95845768e-03,  4.12191177e-04, -5.16326225e-04,
         8.61331529e-04, -1.95881512e-04, -1.06853340e-03,
         2.28973315e-03, -8.48166936e-04,  9.49163223e-05,
        -1.09193625e-03,  1.20801397e-03,  2.64558126e-03,
         2.81515531e-06, -1.03822083e-03, -3.17189656e-03,
         2.17441819e-03, -2.16655689e-03, -4.03829530e-04,
        -1.30875746e-03, -2.52864382e-04, -1.43088808e-03,
         6.81717240e-04,  1.49278762e-03, -1.73330773e-03,
         7.12495530e-05, -5.07070392e-04, -4.96310349e-05,
         1.16008031e-03,  6.81594189e-04, -1.30102376e-03,
        -3.34970355e-05,  6.79796853e-04,  2.61060748e-04,
         1.84251030e-03, -1.37908931e-03,  1.69073886e-04,
         2.21366272e-03, -3.59894079e-06,  1.08278019e-03,
        -2.78988550e-03,  1.26704527e-03, -1.20958651e-03,
        -2.31387536e-03,  2.64072642e-05,  6.58354489e-04,
        -6.95559487e-04,  1.73351413e-03,  1.45367905e-03,
         6.69758010e-04,  9.10711766e-04, -1.77669153e-03,
         1.99460192e-04, -4.52808803e-04, -8.92724085e-04,
         2.99149845e-03, -2.76846415e-03, -3.58661567e-03,
        -1.01979962e-03, -4.98351474e-05, -1.11349451e-03,
        -8.04244410e-05,  3.17688286e-03, -3.16498481e-04,
         3.27806367e-04, -2.14576977e-03, -1.04983908e-03,
         2.70119589e-03, -6.14867837e-04,  2.47694529e-03,
         2.16400577e-03, -1.70252693e-03,  2.80382577e-04,
         5.00922324e-04, -2.32318719e-03,  4.29135427e-04,
         1.39993543e-04,  7.14930706e-04,  8.93779390e-04,
         1.21866749e-03,  1.06152252e-03,  8.15033680e-04,
        -2.71305745e-03,  2.38687010e-03, -1.29661243e-03,
         3.35125165e-04, -6.35245015e-05,  2.41672597e-03,
         6.22836742e-05],
       [ 2.39818427e-03, -8.43839734e-05, -1.02412072e-03,
        -4.45060607e-04,  4.63372387e-04, -1.65757746e-03,
        -1.75287353e-03,  4.99911548e-04, -1.21633126e-03,
         7.82184885e-04, -1.87347981e-03,  6.63130428e-04,
         2.24388065e-03,  2.10375802e-04,  4.95792483e-04,
         3.03159258e-03, -9.25823231e-04,  1.08870002e-03,
        -1.56553695e-04,  2.71955272e-04,  8.44264752e-04,
         2.69074948e-03, -3.05239635e-04,  4.54526482e-04,
         2.12305138e-04,  4.85644588e-04, -4.29850537e-03,
         1.61058805e-03,  1.70854473e-04, -2.78950873e-04,
        -1.73773617e-03, -1.89845206e-03, -1.03137118e-03,
         2.25214148e-03, -6.61305268e-04, -1.93849136e-03,
        -1.08332129e-03, -2.88263138e-04,  1.22902379e-03,
         7.54695968e-04,  1.52223278e-03,  2.05726406e-04,
         2.62465025e-03,  1.38382049e-04,  1.54703122e-03,
         1.42755860e-03, -6.57786615e-04,  1.32225011e-03,
         3.26015498e-03, -4.80496790e-04, -1.01692905e-03,
        -1.57785881e-03, -1.26835366e-03, -1.98496692e-03,
        -1.40044477e-03, -1.09296408e-03, -6.83492341e-04,
         1.73639320e-03, -1.87306665e-04,  1.18706899e-03,
         1.55353031e-04, -7.54370994e-04, -2.64537032e-03,
        -1.46950444e-03,  9.97604104e-04,  4.39236406e-04,
         7.60393799e-04, -6.08585069e-05,  7.67189078e-04,
        -1.62945932e-03, -7.85943121e-04, -9.50930291e-04,
         9.15161581e-05,  1.91718270e-03,  3.28205386e-03,
         4.27325082e-04,  6.15599682e-04,  1.37471361e-03,
        -8.11272330e-05, -4.08905005e-04,  7.54588400e-04,
        -2.94304127e-03, -4.27583000e-03,  1.39923242e-03,
         1.97647186e-03,  2.18723062e-03, -1.76092924e-03,
        -3.53986165e-03, -2.36645574e-03,  1.66798418e-03,
         2.09117221e-04, -1.53569842e-03, -2.07833527e-03,
        -8.67227442e-04,  2.45154602e-03, -8.29173252e-04,
         4.47187398e-04,  8.22120695e-04, -1.58770906e-03,
         1.21566257e-03],
       [-4.43718542e-04,  1.66432071e-03,  7.41207623e-04,
         1.25133360e-04,  7.86755991e-04,  1.71905034e-03,
        -6.78129087e-04,  9.26010776e-04, -1.58612675e-03,
         2.73091955e-05, -1.22012303e-03,  1.15478807e-03,
        -1.09380647e-03, -1.40321223e-04, -1.59822311e-03,
         1.57101767e-03,  8.30740668e-04,  2.54281156e-04,
         1.66769011e-03, -5.78994513e-04, -7.47162907e-04,
        -1.03518029e-03,  9.01523628e-04,  8.47194678e-05,
         1.32781430e-03,  7.75251247e-04,  4.76381392e-05,
         4.25540318e-04, -1.73472275e-03,  1.03950093e-03,
        -8.45912378e-04,  1.28097960e-03,  1.07869855e-03,
         1.26695493e-03, -3.01114924e-04, -2.34222418e-04,
         2.15845532e-03, -2.09282013e-03,  1.15088886e-03,
         5.18576016e-05,  3.42657382e-04,  4.59249306e-04,
         2.58118869e-03, -1.06340936e-04,  4.29233070e-04,
         3.18438309e-04, -2.88068550e-04, -4.93783504e-04,
         8.36090010e-04, -2.47455428e-05,  5.51106234e-04,
        -9.28147230e-04, -1.34846731e-03, -6.66460721e-04,
         4.19201278e-05, -7.98835594e-04, -1.62228200e-04,
        -2.52661481e-03, -7.73994776e-04,  1.23020238e-03,
         2.00473660e-04,  6.14173303e-04, -1.81221520e-03,
         1.60083140e-03,  7.20015669e-04,  1.61242249e-04,
        -8.28490010e-04, -1.13719818e-03,  1.04204091e-05,
        -2.74118560e-04,  2.66692950e-04, -1.26590708e-03,
         6.95334689e-04, -1.04244379e-03, -1.46377448e-03,
         4.96862922e-04, -3.88782995e-04,  1.28237542e-03,
         4.79606068e-04,  2.14923493e-04,  1.30872650e-03,
         2.00699782e-03,  1.45256217e-03, -9.98829491e-04,
        -9.68187465e-04, -8.54401034e-04, -9.36857890e-04,
        -1.52991503e-03, -2.62745190e-04, -1.10494602e-03,
        -1.30144041e-03,  1.13157395e-04,  2.27753539e-04,
        -1.24988030e-03,  1.54688105e-03,  1.20415841e-03,
        -1.87104288e-03, -1.09708984e-03, -4.37719369e-04,
        -5.94698533e-04],
       [-7.25903432e-04, -5.74153673e-05, -1.91353698e-04,
        -3.62950261e-04,  2.08534161e-03,  9.59088677e-04,
        -1.26902224e-03,  1.63491163e-03, -1.16686581e-03,
         3.28662485e-04, -1.52739463e-03,  1.06063427e-03,
        -1.17601408e-03, -4.67784994e-04, -8.58469139e-05,
        -1.20190321e-04, -1.71848608e-03, -6.02424843e-04,
        -1.56632578e-03, -4.36159578e-04, -4.43441299e-04,
        -8.93659424e-04, -2.33307318e-03, -3.99879937e-04,
         2.31174054e-04, -3.26201553e-05, -7.68373953e-04,
         3.94819886e-04, -1.03635970e-03, -1.90709397e-05,
        -5.95290214e-04,  3.67535220e-04, -2.42312439e-03,
         3.29180388e-03,  6.85091421e-04, -1.06741302e-03,
         1.14661036e-03,  1.44576712e-04, -1.42730493e-03,
         1.25534891e-04,  2.11120350e-04, -5.82582550e-04,
         2.68458994e-03, -3.62628489e-05, -1.24439527e-03,
         1.75684155e-03, -1.21043646e-03,  2.47140095e-04,
         1.91578956e-03, -6.48358895e-04,  1.68317580e-04,
        -1.03004789e-03, -6.05891109e-04, -1.82121049e-03,
        -1.60169380e-03,  9.97777563e-04,  9.65224812e-04,
        -1.99172786e-03,  2.21815193e-04,  1.83470466e-03,
         1.89578056e-03,  9.14322911e-04, -1.17160159e-03,
         1.22219208e-03, -6.47944980e-05,  3.41403735e-04,
         1.79492729e-03, -5.16015221e-04, -6.26038411e-04,
        -8.32065009e-04, -2.72367452e-03, -2.09121406e-03,
         1.06015627e-03,  9.13575524e-04, -1.04096963e-03,
        -7.54459761e-04, -7.92585313e-04,  1.77001883e-03,
         1.26059563e-03, -7.49798259e-04,  3.29678180e-03,
        -4.84498363e-04, -2.77333660e-04,  8.56891857e-04,
         1.25441467e-03,  4.53954912e-04, -2.15913565e-03,
        -1.06265955e-03, -9.20594903e-05,  1.22715719e-03,
         1.17518974e-03,  6.44225453e-04, -1.16885247e-04,
        -1.08826323e-03,  2.73700012e-03,  3.49877635e-04,
        -2.32152859e-04, -1.83059729e-03, -2.78510095e-04,
        -6.06695074e-04],
       [ 7.55021116e-04, -1.15827541e-03, -1.57080626e-03,
         2.43214401e-03,  1.23886019e-03,  3.10276955e-04,
        -1.15139272e-04,  1.10133237e-03,  8.62916117e-04,
         2.15277146e-03, -3.22789361e-04,  1.18122553e-03,
         1.59975630e-03, -1.63202430e-03, -4.31828194e-05,
         2.59776902e-03, -5.74414735e-04, -6.48011453e-04,
         1.03361334e-03, -2.45265201e-05, -3.58652964e-04,
         4.55828675e-04, -5.29842800e-04, -1.42199593e-03,
         2.32599629e-03, -5.65932074e-04, -1.78126956e-03,
         1.79481762e-03, -2.09290115e-03,  4.76163812e-04,
        -7.34458095e-04, -3.37060192e-04, -1.42722018e-03,
         2.63230153e-03, -3.52345663e-03, -2.41477299e-03,
        -1.66049856e-03,  2.35446729e-04,  7.14445923e-05,
         1.05865416e-03,  1.83461886e-03,  4.31552544e-05,
         3.79647769e-04, -2.07670266e-03,  9.49829642e-04,
         1.23480451e-03, -2.72685615e-03, -1.76739413e-05,
         8.39545974e-04, -8.44798691e-04,  1.65575370e-03,
         3.01847787e-04,  3.91649955e-04, -2.46565463e-03,
        -6.11679978e-04,  1.80391740e-04, -4.81181400e-04,
         4.75070119e-04, -5.85301023e-04, -4.23185149e-04,
        -1.99542800e-03, -1.22923811e-03, -4.48381354e-04,
         2.54157465e-03, -1.34741538e-03,  4.08516824e-03,
         2.37062104e-05,  7.48454942e-04, -2.78270250e-04,
        -1.70694455e-03,  4.09444241e-04,  7.78907095e-04,
         1.92327821e-03,  8.84331472e-04,  1.16875360e-03,
        -4.09845350e-04,  2.46994081e-03, -9.94558912e-04,
         2.99021415e-03,  6.73654504e-05,  9.32805589e-04,
        -1.29172741e-03, -2.19988590e-03,  8.61806038e-04,
         2.38556601e-03, -3.03779473e-03, -5.29025681e-04,
         7.65465200e-04,  1.95658577e-04,  7.47894883e-05,
         2.45958311e-03,  1.49244315e-03,  1.05668872e-03,
        -5.24337753e-04,  1.52681675e-03, -8.03495408e-04,
        -1.11114723e-03,  1.27461948e-03,  1.17620591e-04,
         2.88196141e-04],
       [ 9.10617673e-05,  1.57191325e-03,  4.66107304e-04,
         7.42646516e-04,  1.43557379e-03,  7.47596088e-04,
         5.52730926e-04,  1.83881540e-03, -1.59799086e-03,
         3.91155947e-04, -1.40971947e-03,  1.14842900e-03,
        -1.47500518e-03,  1.11660839e-03, -1.73205044e-04,
         1.58790534e-03,  5.24598465e-04,  5.43659204e-04,
         1.49701349e-03,  5.53338148e-04, -1.51054387e-03,
        -1.84062612e-03,  5.08232333e-04,  2.46093850e-06,
         2.70472048e-03,  1.35302951e-03, -8.91799864e-04,
         7.81621027e-04,  4.73989494e-04,  3.56509816e-04,
        -9.52229966e-05,  5.72949415e-04,  1.03378657e-03,
         1.81155861e-03,  7.62428041e-04, -9.53712326e-04,
         1.60981272e-03, -1.55345281e-03, -6.85071282e-04,
        -6.46978035e-04,  1.58057641e-03,  3.63791158e-04,
         2.09625927e-03,  2.54480165e-05,  1.38623384e-03,
         1.06713083e-03, -2.42014692e-04, -4.58788883e-04,
         1.48665777e-03, -1.53643952e-03,  4.73797700e-04,
        -1.90904294e-03, -1.16723531e-03,  1.19482305e-04,
        -4.66795405e-04,  6.41913444e-04,  9.88641055e-04,
        -3.01665685e-04, -9.21497121e-05,  3.32008605e-03,
         4.37350653e-04,  6.18300284e-04, -2.12030183e-03,
         9.28439084e-04, -2.24366551e-04, -1.01651181e-03,
         2.61470501e-04, -4.12955706e-04, -3.60788894e-04,
        -1.90274863e-04,  2.22301111e-04, -7.69502949e-04,
         9.68862616e-04, -4.20505166e-05, -8.59834981e-05,
         8.36641353e-04, -7.53846660e-04,  2.31160826e-04,
        -4.18111362e-04, -2.71187164e-04,  6.77747303e-04,
         2.13121506e-03,  4.19091724e-04, -1.97977806e-03,
        -4.87214187e-04,  6.84440951e-04,  1.19242308e-04,
        -1.70384836e-03, -1.48142211e-03, -2.39255559e-03,
        -5.89491450e-04, -2.95158934e-05,  7.31412729e-04,
        -1.01014099e-03,  1.73707749e-03,  1.40468779e-04,
        -2.14732112e-03, -9.65155195e-04, -6.49755297e-04,
        -9.40315425e-04],
       [-1.59110175e-03,  1.41308992e-03,  2.95228063e-04,
         7.53708009e-04, -6.71685208e-04,  2.25526839e-03,
        -3.23014101e-05,  1.56071584e-03, -1.02572085e-03,
        -1.06005452e-03,  2.52023456e-04,  1.08655053e-03,
         6.66804262e-05,  2.16548145e-03, -1.56730169e-03,
         1.34398532e-03,  3.42994253e-03,  1.74719898e-05,
         6.51493843e-04,  1.42673787e-03, -9.66046471e-04,
        -9.92469722e-04, -2.52842391e-03,  2.60810740e-03,
         2.24301219e-03,  1.14458892e-03, -3.15773912e-04,
         7.29178428e-04, -5.38910914e-04, -9.36764874e-04,
         1.24173495e-03,  5.23546943e-04, -7.05095590e-04,
         1.01900683e-03, -2.97766412e-04, -2.94713327e-03,
         2.95336242e-03,  8.75390659e-04, -1.71183143e-03,
        -5.23462513e-05,  6.04786153e-04,  1.22580188e-03,
         1.84954249e-03, -3.23649525e-04, -1.21851481e-04,
        -8.39192304e-04,  1.59152574e-03,  3.24339751e-04,
        -5.28109318e-04, -1.09007757e-04,  9.21742758e-04,
        -9.43213934e-04, -1.33805058e-03, -2.21809861e-03,
        -3.06608388e-04,  6.29727729e-05,  3.16435442e-04,
         1.34513387e-03, -1.32623059e-03, -1.00212987e-04,
        -3.85473802e-04, -3.85420048e-04, -1.48249813e-03,
        -4.79335780e-04, -3.02741537e-04, -4.63108881e-04,
         8.20245012e-04,  1.84344163e-03, -2.44636741e-03,
         2.12064479e-03,  1.03225326e-03,  1.95129542e-06,
         2.40750657e-03, -4.37094044e-04,  4.32551489e-04,
        -2.45185627e-04, -7.66993500e-04,  3.95535928e-04,
         1.61005952e-03, -7.49235798e-04,  4.57830989e-04,
         1.01489201e-03, -1.90123537e-04,  1.57169369e-03,
         1.24298211e-03, -1.11959071e-03, -1.12664234e-03,
        -3.00410134e-03,  4.48008650e-04, -1.02731481e-03,
         2.86517898e-04, -1.20037026e-03,  7.12403969e-04,
        -7.59513583e-04, -3.17380938e-04, -1.97426925e-04,
        -1.90798193e-03,  3.35533230e-04, -3.93486058e-04,
        -1.25790376e-03],
       [-7.51647458e-04, -1.11844076e-03, -1.64439739e-03,
         1.05433763e-04, -3.42866406e-06,  2.27166736e-03,
        -2.08187965e-03, -1.97637896e-03, -4.19053773e-04,
        -1.23330031e-03,  1.20109168e-03,  1.82217860e-03,
        -3.43586522e-04, -6.35903707e-05,  1.68473937e-03,
         1.54219463e-03, -1.78830349e-03, -1.18166870e-04,
         1.01315258e-04, -7.43931450e-04, -1.53077010e-03,
         2.27336437e-04, -2.15162034e-03,  7.96184468e-04,
         9.49432608e-04, -4.07353567e-04, -5.36314074e-05,
         2.90523545e-04, -2.29214015e-03, -5.22176793e-04,
         1.60963822e-03, -7.18622352e-04, -2.55933939e-03,
         2.01303815e-03, -2.56766307e-05,  1.97815782e-04,
         5.95871301e-04, -2.01950059e-03, -9.14958189e-04,
         2.05532182e-03,  3.60412196e-05, -2.47169781e-04,
         3.12962197e-03, -6.76022784e-04, -1.17148249e-03,
        -4.31569148e-04, -2.37862999e-03, -2.00478389e-04,
         5.16952423e-04, -2.22644606e-03,  1.60182477e-03,
         8.20190544e-05,  7.64411874e-04, -1.77582994e-03,
         5.12804429e-04,  2.74841464e-03, -5.43845701e-04,
         9.50879126e-04,  1.67476735e-03,  3.41924606e-03,
        -1.86718637e-04,  1.79267640e-03, -6.55659591e-04,
         1.67103100e-03, -2.10915619e-04, -1.28687522e-03,
         2.69459747e-03, -1.37428357e-03, -2.66055274e-03,
        -2.12448556e-03, -1.94452039e-03, -3.60338658e-04,
        -4.08523862e-04,  1.72277784e-03, -2.24833508e-04,
         5.98292914e-04, -1.09503441e-03,  1.66870468e-05,
         3.36125901e-04, -3.82598810e-04,  2.30517727e-03,
        -2.16120825e-04, -2.09373562e-03, -8.97543156e-04,
         2.02026611e-04,  1.36654510e-03, -1.00083556e-03,
         1.12384721e-03,  3.35268734e-04,  4.63758741e-04,
        -1.70744315e-03,  8.80234060e-04, -3.57653887e-04,
        -6.90174929e-04,  1.94926909e-03, -4.68228012e-04,
        -8.19645211e-05, -6.43740932e-04,  5.44366019e-04,
         3.56164091e-04],
       [-4.10388777e-04,  1.08907174e-03, -1.04287372e-03,
         1.00830148e-04,  1.15463161e-03, -1.29678322e-03,
         3.58006160e-04, -1.96988083e-04, -8.16171232e-04,
         1.03314756e-03, -2.47881748e-03,  1.50605061e-04,
        -3.81719641e-04,  1.55987032e-03,  5.11473685e-04,
         5.61505847e-04, -3.03315639e-04,  2.62339658e-04,
         2.52237718e-04,  2.72835605e-05, -1.86248799e-03,
        -1.22649479e-03,  5.18841087e-04, -2.61088077e-04,
         2.75741040e-04, -1.06020016e-03,  8.82752414e-04,
         3.90360685e-04,  6.71225716e-04,  3.31319316e-04,
         1.14085351e-03,  1.20876858e-03, -2.69566779e-04,
         1.08552165e-03, -8.02230381e-04,  7.41765019e-04,
         8.54852959e-04, -1.02501886e-03,  2.56027823e-04,
         1.14675460e-03,  1.42224878e-03,  1.98976556e-03,
         2.20925407e-03, -5.57954772e-04,  5.12939761e-04,
        -1.36921869e-03,  3.60833306e-04, -3.82215774e-04,
         1.11950946e-03, -2.85121001e-04, -1.48583879e-03,
        -2.45472742e-03, -1.13987981e-03,  9.25341039e-04,
         4.57275280e-04,  6.89742388e-04,  2.39856169e-03,
        -2.59059656e-04, -1.94662623e-03,  8.26380565e-05,
         1.05608162e-03,  3.89716588e-05, -2.11507897e-03,
         1.65604544e-03, -8.76347185e-04,  9.39479214e-05,
         8.23607319e-04,  9.40230500e-04, -4.86386853e-04,
         4.64065641e-04,  6.40141894e-04, -1.39892125e-03,
        -2.92612356e-04, -1.79532799e-03, -1.66710470e-05,
        -2.39347311e-04,  1.42352912e-03,  1.14440988e-03,
        -7.14034773e-04, -5.61112029e-05,  1.55716014e-04,
        -1.01405359e-03,  4.37079754e-04, -7.52383727e-04,
        -1.15163729e-03,  1.07281806e-03, -5.80444583e-04,
        -1.48141431e-03, -4.14952490e-04,  5.31013182e-04,
         1.52910675e-03,  8.63466048e-05, -9.31170885e-04,
         3.75137839e-04, -1.46658008e-03,  6.72543421e-04,
        -9.67633096e-05,  1.67584664e-03, -3.44879692e-03,
        -1.74003933e-03],
       [-1.52997032e-03,  6.09572569e-04, -4.83574142e-04,
         4.54078079e-04,  6.00002939e-04,  1.06836704e-03,
        -7.23464938e-04, -6.77600619e-05, -6.31511619e-04,
        -9.94874630e-04, -8.42147332e-04,  3.78003722e-04,
        -6.89997105e-05,  1.51504728e-03,  1.52875204e-03,
         5.70973789e-04, -1.82368211e-04, -1.96383032e-03,
        -1.14274316e-03,  4.36001392e-05, -1.24389410e-03,
        -5.80980442e-04,  8.57727078e-04, -1.91089732e-03,
         3.43686756e-04,  4.39354248e-04,  1.04100432e-03,
         2.06698547e-04, -1.35807705e-03,  1.01624895e-03,
         9.39888007e-04,  1.29361427e-03, -1.42030872e-03,
         1.78957928e-03, -1.18735433e-03,  3.03327659e-04,
         1.62131060e-03, -5.15165913e-04, -1.34804135e-03,
         1.12286874e-03,  5.03385207e-04,  6.96348026e-04,
         1.12329237e-03, -1.93926113e-04, -6.35204196e-04,
        -1.01554359e-03, -1.85659897e-04, -9.19270969e-04,
         1.05608976e-03, -1.73159351e-03, -1.78093047e-04,
        -7.81554918e-05, -2.17330293e-04, -2.91168253e-04,
         5.78548585e-04,  1.09605747e-03, -5.98490769e-05,
         2.95781239e-04,  2.59398337e-04,  2.33943597e-03,
        -1.01143669e-04,  1.13194622e-03, -1.01473089e-03,
         9.42078361e-04, -8.96339770e-06,  5.83949324e-04,
         1.55253895e-03, -5.47444390e-04, -9.67025058e-04,
        -7.53764005e-04, -8.93300225e-04, -1.24700845e-03,
        -5.17834036e-04,  4.29749576e-04, -7.52421853e-04,
        -4.67230944e-04, -6.36236146e-05, -9.61293001e-04,
         1.05771248e-03, -4.66048747e-04,  2.36480264e-05,
         2.77009734e-04, -7.74563814e-04,  7.51945699e-05,
         6.42146682e-04,  1.62888132e-03, -2.16467376e-03,
        -9.05324996e-04, -5.63526293e-04,  6.11646508e-04,
         4.86561534e-04,  2.35278788e-03,  1.55609392e-03,
        -6.61270053e-04, -1.27778295e-03, -1.78552538e-04,
        -6.94991264e-04, -5.85458067e-04, -1.29336418e-04,
        -2.56531872e-04]], dtype=float32)

In [8]:
# 파이프라인 생성
pipe = Pipeline(
    [
        ('ft' , FastTextVectorizer(tokenizer=tokenizer)),
        ('clf', LogisticRegression(max_iter=2000))
    ]
)

In [9]:
pipe.fit(X, Y)

Pipeline(steps=[('ft',
                 FastTextVectorizer(tokenizer=<function tokenize.<locals>.<lambda> at 0x000001ADED2F1C60>)),
                ('clf', LogisticRegression(max_iter=2000))])

In [10]:
# 최적의 파라미터를 찾기 위해 GridSearch와 Fold화
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

In [11]:
# 매개변수의 경우들을 dict데이터로 생성
grid_params = {
    'ft__vector_size' : [50, 100],
    'ft__sg' : [0, 1],
    'clf__C' : [1.0, 2.0]
}

In [12]:
# pipe와 cv, grid_params들을 이용하여 GridSearchCV를 사용
grid = GridSearchCV(
    estimator = pipe,
    param_grid = grid_params,
    cv = cv,
    scoring = 'f1_macro',
    verbose = 1
)

In [13]:
# gridsearch 실행
grid.fit(X, Y)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('ft',
                                        FastTextVectorizer(tokenizer=<function tokenize.<locals>.<lambda> at 0x000001ADED2F1C60>)),
                                       ('clf',
                                        LogisticRegression(max_iter=2000))]),
             param_grid={'clf__C': [1.0, 2.0], 'ft__sg': [0, 1],
                         'ft__vector_size': [50, 100]},
             scoring='f1_macro', verbose=1)

In [14]:
# 최적의 파라미터를 출력
print("GridSearch 기준 최적의 파라미터 :", grid.best_params_)
print("GridSearchCV의 최적의 F1 :", grid.best_score_)

GridSearch 기준 최적의 파라미터 : {'clf__C': 1.0, 'ft__sg': 0, 'ft__vector_size': 50}
GridSearchCV의 최적의 F1 : 0.39999999999999997

### 연습
- tokenizer, FastTextVectorizer, StratifiedKfold, Pipeline, GridSearchCV을 이용하여 data 폴더 안에 ratings_train.txt 파일의 데이터를 학습하여 최적의 파라미터를 구하라
    1. train 데이터를 ratings_train.txt에서 상위 500개의 데이터를 이용
    2. text 데이터는 하위 100개의 데이터
    3. 파라미터 경우의 수
        - FastText
            - window -> 3, 5
            - sg -> 0, 1
            - epochs -> 10, 50
        - Logistic
            - C -> 1.0, 2.0
    4. Fold는 3개를 생성
    5. 최적의 파라미터를 생성
    6. 최적의 모델을 이용하여 test 데이터를 예측한 뒤 class_report 생성

In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('../data/ratings_train.txt', sep='\t')
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [17]:
# 사용할 컬럼을 제외하고 제거 -> id 컬럼
df.drop('id', axis=1, inplace=True)
df.head()

                                            document  label
0                                아 더빙.. 진짜 짜증나네요 목소리      0
1                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2                                  너무재밓었다그래서보는것을추천한다      0
3                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   document  149995 non-null  object
 1   label     150000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 2.3+ MB

In [19]:
# document 컬럼에서 문자열 좌우의 공백을 제거
# Series에서 문자열 Method을 사용할 수 있는 형태로 변환하고 문자열 함수 사용
df['document'].str.strip()

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 150000, dtype: object

In [20]:
# map() 함수를 이용해서 원소 각각을 대입하여 변환
df['document'] = df['document'].astype(str).map(
    lambda x : x.strip()
)

In [21]:
# document에서 중복된 데이터를 제거
df.drop_duplicates('document', inplace=True)

In [22]:
# train, test 데이터를 나눠준다
X_train = df['document'].head(500).values
Y_train = df['label'].head(500).values

In [23]:
X_test = df['document'].tail(100).values
Y_test = df['label'].tail(100).values

In [24]:
pipe2 = Pipeline(
    [
        ('ft' , FastTextVectorizer(tokenizer=tokenizer)),
        ('clf', LogisticRegression(max_iter=2000))
    ]
)

In [25]:
# 최적의 파라미터를 찾기 위해 GridSearch와 Fold화
cv2 = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [26]:
grid_params2 = {
    'ft__window' : [3, 5],
    'ft__sg' : [0, 1],
    'ft__epochs' : [10, 50],
    'clf__C' : [1.0, 2.0]
}

In [27]:
# pipe와 cv, grid_params들을 이용하여 GridSearchCV를 사용
grid2 = GridSearchCV(
    estimator = pipe2,
    param_grid = grid_params2,
    cv = cv2,
    scoring = 'f1_macro',
    verbose = 1
)

In [28]:
grid2.fit(X_train, Y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits

GridSearchCV(cv=StratifiedKFold(n_splits=3, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('ft',
                                        FastTextVectorizer(tokenizer=<function tokenize.<locals>.<lambda> at 0x000001ADED2F1C60>)),
                                       ('clf',
                                        LogisticRegression(max_iter=2000))]),
             param_grid={'clf__C': [1.0, 2.0], 'ft__epochs': [10, 50],
                         'ft__sg': [0, 1], 'ft__window': [3, 5]},
             scoring='f1_macro', verbose=1)

In [37]:
# 최적의 스코어
print(grid2.best_score_)
# 최적의 파라미터
print(grid2.best_params_)

0.6740835985590984
{'clf__C': 2.0, 'ft__epochs': 50, 'ft__sg': 1, 'ft__window': 3}

In [34]:
best_model = grid2.best_estimator_

In [35]:
best_pred = best_model.predict(X_test)

In [49]:
print(classification_report(best_pred, Y_test))

              precision    recall  f1-score   support

           0       0.49      0.72      0.58        32
           1       0.83      0.65      0.73        68

    accuracy                           0.67       100
   macro avg       0.66      0.68      0.65       100
weighted avg       0.72      0.67      0.68       100

In [42]:
# 최적의 파라미터를 이용하여 재학습 -> 예측 검증
params = grid2.best_params_

In [43]:
pipe3 = Pipeline(
    [
        ('ft', FastTextVectorizer(
            tokenizer=tokenizer,
            window = params['ft__window'],
            sg = params['ft__sg'],
            epochs= params['ft__epochs'],
        )),
        ('clf', LogisticRegression(max_iter=2000, C=params['clf__C']))
    ]
)

In [44]:
pipe3.fit(X_train, Y_train)

Pipeline(steps=[('ft',
                 FastTextVectorizer(epochs=50,
                                    tokenizer=<function tokenize.<locals>.<lambda> at 0x000001ADED2F1C60>)),
                ('clf', LogisticRegression(C=2.0, max_iter=2000))])

In [46]:
pred3 = pipe3.predict(X_test)

In [48]:
print(classification_report(pred3, Y_test))

              precision    recall  f1-score   support

           0       0.49      0.72      0.58        32
           1       0.83      0.65      0.73        68

    accuracy                           0.67       100
   macro avg       0.66      0.68      0.65       100
weighted avg       0.72      0.67      0.68       100