# 변수
- 데이터가 저장되는 공간의 이름 (접근성 좋아짐)
    - 데이터 종류
        - 단일 데이터
            - 문자(str)
            - 숫자(int / float)
            - bool(참/거짓)
        - 다차원 데이터
            - tuple
            - list
            - dict
    - 변수의 종류
        - 전역 변수
            - 어디서든 사용이 가능한 변수
            - globals()를 이용하여 확인
        - 지역 변수
            - 특정한 영역에서만 사용이 가능
            - 함수 내에서 생성된 변수나 매개변수등이 지역변수의 대표적인 예
        - 매개 변수
            - 함수가 호출될 때 입력 값(인자)을 받아오기 위한 공간의 이름
            - 기본 값을 지정하여 인자가 없더라도 기본값을 이용하여 함수가 실행
            - 인자의 개수가 가변인 경우 변수명 앞에 * 붙여서 변수를 생성
        - 객체 변수
            - class 내부에서 사용을 하는 데이터들을 저장하는 공간의 이름
            - self.변수명을 이용하여 데이터들을 저장
            - 생성이 되는 class마다 독립적인 데이터를 저장
        - 클래스 변수
            - class 내부에서 사용하는 데이터들을 저장하는 공간의 이름
            - 클래스 선언시 함수와 같은 영역에 변수를 생성
            - 같은 class가 생성이 될때 서로 공유할 수 있는 변수

In [3]:
# python에서는 변수를 생성할때 데이터가 같이 대입
vari_1 = "hello"
print(vari_1)

hello

In [17]:
def func_1():
    result = 1111
    return result
a = func_1()
print(a)

1111

In [13]:
# result는 함수 내부에서 생성된 지역 변수임으로 외부에서는 사용이 불가능
# print(result)

In [14]:
def func_2():
    result = 1111
    print(result)

In [20]:
b = func_2()
print(b)

1111
None

In [23]:
# bool -> True / False 2가지의 타입을 가진 데이터
# 조건식에서 사용 -> if문, while문
# 조건식이 들어가는 부분에서 변수를 사용하는 경우가 종종 발생
# 변수를 강제적으로 bool형태로 변환
# 문자 타입의 강제 bool 변환
print(bool('a'))    # True
print(bool(' '))    # True
print(bool(''))     # False

True
True
False

# 경로
- 절대 경로
    - 절대적인 주소 값
    - 어떤 환경에서도 같은 위치를 나타낸다.
        - 환경 -> 컴퓨터
    - ex
        - c:/users/admin/document/a.txt
            - 컴퓨터 안에 파일들을 불러오는 경우에는 절대 경로보다는 상대 경로 사용이 유리
        - https://www.google.com
            - url 이용시에는 절대 경로로 사용
        - Database server의 주소를 이용하는 경우 절대 경로 사용
- 상대 경로
    - 상대적인 주소
    - 환경이 변경되었을 때 위치도 변화한다.
        - ./ : 현재 작업중인 디렉토리(경로)
        - ../ : 현재 디렉토리 상위 디렉토리 이동
        - 디렉토리명(폴더명)/ : 하위 디렉토리 이동

In [35]:
import pandas as pd

In [38]:
# 절대 경로를 이용하여 csv 파일 불러오기
df = pd.read_csv(r"C:\python\multicam\csv\AAPL.csv")

In [37]:
# 상대 경로를 이용하여 csv 파일 불러오기
df2 = pd.read_csv("../csv/AAPL.csv")

# 함수
- 특정 행동(기능)을 특정 공간에 저장하여 함수의 이름을 호출하여 반복적으로 사용
- 사용하는 이유? -> 같은 행동을 여러 곳에서 사용하는 경우 함수를 이용한다면 
코드의 라인이 줄어들고 가독성이 올라가고 오류가 날 확률이 줄어든다.
- def 키워드를 이용해서 함수를 생성
- 이름없는 함수 : lambda 함수
    - 간단한 작업을 특정 영역에서 반복적으로 실행을 할때 사용
    - map()함수나 apply()함수에서 자주 사용
- 재귀함수
    - 내가 나 자신을 호출하는 함수
    - 루프를 돌려서 반복 실행하고 특정 결과가 완성되었을때 출력을 돌려주는 함수
    - 일반적인 반복문을 이용하는 것보다 가독성이 올라간다.

In [42]:
# 매개변수가 존재하지 않는 함수 생성
def func_3():
    # 함수가 호출될때 일반적으로 동일한 데이터를 되돌려준다.
    result = "Hello"
    return result

In [44]:
func_3()

'Hello'

In [56]:
# 매개변수가 존재하는 함수
def func_4(x, y):
    # x, y는 함수가 호출될때 입력 값들이 대입이 되는 공간
    # 매개변수가 2개인 함수는 호출시 인자도 2개
    result = x + y
    return result

In [64]:
func_4(10, 2)

12

In [66]:
# 매개변수가 2개인데 호출이 인자의 개수가 다르다면?
# 에러가 발생
# func_4(10, 3, 2)

In [68]:
# 매개변수의 기본값을 설정한 함수
def load_data( servicekey, cnt = 10 ):
    # servicekey 매개변수는 입력이 필수 항목
    # cnt 매개변수는 기본값이 설정되어있으므로 선택 항목
    # servicekey 확인
    if servicekey == 'abcd':
        df = pd.read_csv("../csv/boston.csv")
        result = df.head(cnt).to_dict(orient='records')
    else:
        result = "등록된 servicekey가 아닙니다."
    return result

In [73]:
load_data('aaaa')

'등록된 servicekey가 아닙니다.'

In [79]:
len(load_data('abcd', cnt = 20))

20

In [ ]:
# 인자의 개수가 가변인 경우 매개변수 생성하는 함수
def func_5( x, *y ):
    print(type(x))
    print(type(y))

In [85]:
func_5('a', 'b', 'c', 'd')

<class 'str'>
<class 'tuple'>

In [87]:
func_5(1, 2, 3, 4)

<class 'int'>
<class 'tuple'>

In [111]:
def func_6(_type, *_numbers):
    if _type == 'sum':
        result = 0
        for num in _numbers:
            result += num
    else:
        result = 1
        for num in _numbers:
            result *= num
    return result

In [112]:
input_type = 'sum'
input_numbers = [1,2,3,4,5]

In [113]:
func_6(input_type, *input_numbers)

15

# class
- 변수, 함수들의 모음
- 특징
    - 동일한 class가 여러 곳(변수)에서 생성(사용)이 가능
    - 여러 곳에서 같은 기능을 사용이 가능
- python에서 클래스를 사용하는 이유?
    - python의 모든 데이터의 타입은 class 구성
    - 같은 class를 생성하여도 독립적인 데이터를 이용해서 함수를 사용이 가능
- 상속
    - 부모 클래스에 있는 변수, 함수들을 자식 클래스가 사용하도록 물려받는 기능
    - 부모 클래스에서의 기능은 그대로 유지한 채로 자식 클래스에서는 그 외의 기능들을 추가해서 사용
    - 파일을 분할 관리 하듯이 클래스도 기능별 각각 분할하여 관리 가능

In [121]:
# 특정 경로에 있는 파일의 목록을 불러와서 파일들을 모두 로드하는 방법
import os
from glob import glob

In [122]:
# 특정 경로에 있는 파일의 목록을 불러온다.
# 목록(list) + 디렉토리(dir)
os.listdir('../csv')

['2014.csv',
 '2017',
 '2017_expense_list.csv',
 '2017_expense_list.xlsx',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2022년 06월 교통카드통계자료.xls',
 'AAPL.csv',
 'AMZN.csv',
 'boston.csv',
 'campaign_master.csv',
 'card',
 'class_master.csv',
 'corona.csv',
 'csv_exam.csv',
 'customer_master.csv',
 'dept.csv',
 'drinks.csv',
 'emp.csv',
 'example.csv',
 'GM.csv',
 'item_master.csv',
 'Koweps_Codebook.xlsx',
 'MSFT.csv',
 'num_1',
 'num_2',
 'num_3',
 'Sales Records.csv',
 'Superstore KR - VizLab 2022.xlsx',
 'tran_1.csv',
 'tran_2.csv',
 'tran_d_1.csv',
 'tran_d_2.csv',
 'uriage.csv',
 'use_log.csv',
 'USM.csv',
 '주민등록.csv',
 '태블로']

In [139]:
glob('../csv/*.csv')

['../csv\\2014.csv',
 '../csv\\2017_expense_list.csv',
 '../csv\\AAPL.csv',
 '../csv\\AMZN.csv',
 '../csv\\boston.csv',
 '../csv\\campaign_master.csv',
 '../csv\\class_master.csv',
 '../csv\\corona.csv',
 '../csv\\csv_exam.csv',
 '../csv\\customer_master.csv',
 '../csv\\dept.csv',
 '../csv\\drinks.csv',
 '../csv\\emp.csv',
 '../csv\\example.csv',
 '../csv\\GM.csv',
 '../csv\\item_master.csv',
 '../csv\\MSFT.csv',
 '../csv\\Sales Records.csv',
 '../csv\\tran_1.csv',
 '../csv\\tran_2.csv',
 '../csv\\tran_d_1.csv',
 '../csv\\tran_d_2.csv',
 '../csv\\uriage.csv',
 '../csv\\use_log.csv',
 '../csv\\USM.csv',
 '../csv\\주민등록.csv']

## 특정 경로에 있는 데이터 파일을 모두 로드
- 파일 로드의 방식
    1. os 라이브러리 안이 엤는 listdir()
    2. glob 라이브러리 안에 있는 glob()
- 파일의 저장 방식
    1. 각각의 전역 변수에 저장
    2. 하나의 []에 저장
    3. 하나의 데이터프레임으로 결합(단순한 행 결합 UNION)

In [147]:
# 파일의 목록
file_path = "../csv/2017/"
file_list = os.listdir(file_path)
file_list

['201701_expense_list.csv',
 '201702_expense_list.csv',
 '201703_expense_list.csv',
 '201704_expense_list.csv',
 '201705_expense_list.csv',
 '201706_expense_list.csv',
 '201707_expense_list.csv',
 '201708_expense_list.csv',
 '201709_expense_list.csv',
 '201710_expense_list.csv',
 '201711_expense_list.csv',
 '201712_expense_list.csv']

In [ ]:
# 반복문을 이용하여 file_list의 목록 하나씩 대입하여 file_path와 결합후 read_csv()함수를 이용한다.
for file in file_list:    
    # print(file_path + file)
    # df에 1월부터 12월까지 데이터가 로드될때마다 대입
    # 결과적으로는 12월 데이터만 df에 남는다.
    df = pd.read_csv(file_path + file)

In [148]:
# 수정1 -> 빈 리스트에 반복 실행할 때마다 데이터프레임을 추가
dfs = []
for file in file_list:
    df = pd.read_csv(file_path + file)
    #  리스트에 추가
    dfs.append(df)

len(dfs)

12

In [149]:
dfs[2]

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,11538711,2017.3월분 업무추진비 지출내역,http://opengov.seoul.go.kr/public/11538711,사업소,서울역사박물관,학예연구부,유물관리과,NaN,2017,3,250000.0,250000.0,현업-우수부서 격려 등,서울역사박물관 유물관리과,2017-03-22 00:00,서울시청 연금매점,부서운영에 필요한 물품구입,9,카드,74710
1,11538711,2017.3월분 업무추진비 지출내역,http://opengov.seoul.go.kr/public/11538711,사업소,서울역사박물관,학예연구부,유물관리과,NaN,2017,3,250000.0,250000.0,현업-우수부서 격려 등,서울역사박물관 유물관리과,2017-03-17 00:00,홈플러스 광화문,부서운영에 필요한 물품구입,9,카드,175290
2,11633721,2017년 3월 생활환경과 업무추진비 집행내역,http://opengov.seoul.go.kr/public/11633721,서울시본청,기후환경본부,생활환경과,NaN,NaN,2017,3,NaN,NaN,NaN,생활환경과,2017-03-24 20:33,명동함흥면옥(중구 명동2 26-1),도로물청소 전용 수전확보 위한 간담회,생활환경과장 외 4인,카드,53000
3,11633721,2017년 3월 생활환경과 업무추진비 집행내역,http://opengov.seoul.go.kr/public/11633721,서울시본청,기후환경본부,생활환경과,NaN,NaN,2017,3,NaN,NaN,NaN,생활환경과,2017-03-22 16:01,고릴라김밥(중구 서소문로134),부서운영 직원격려 간식비 지급,생활환경과장 외 20인,카드,40000
4,11633721,2017년 3월 생활환경과 업무추진비 집행내역,http://opengov.seoul.go.kr/public/11633721,서울시본청,기후환경본부,생활환경과,NaN,NaN,2017,3,NaN,NaN,NaN,생활환경과,2017-03-17 13:05,시골집(은평구 연서로 34길 14-1),악취방지시설 모니터링 감담회,생활환경과장 외 3인,카드,63000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6109,11988247,2017년 3월 서울시본청_서울혁신기획관_청년정책담당관 업무추진비 내역,http://opengov.seoul.go.kr/public/11988247,서울시본청,서울혁신기획관,NaN,NaN,NaN,2017,3,NaN,NaN,NaN,사회혁신기획관청년정책담당관,2017-03-09 19:56,고미정 (서대문구연희로26),대청마루향후방안 관련간담회비지급,청년정책담당관 등 9명,카드,164000
6110,11988247,2017년 3월 서울시본청_서울혁신기획관_청년정책담당관 업무추진비 내역,http://opengov.seoul.go.kr/public/11988247,서울시본청,서울혁신기획관,NaN,NaN,NaN,2017,3,NaN,NaN,NaN,사회혁신기획관청년정책담당관,2017-03-09 20:07,카페로뎀바이예다움 (서대문구연희로138),건강한금융생활 지원간담회비지급,청년정책담당관 등 4명,카드,33000
6111,11988247,2017년 3월 서울시본청_서울혁신기획관_청년정책담당관 업무추진비 내역,http://opengov.seoul.go.kr/public/11988247,서울시본청,서울혁신기획관,NaN,NaN,NaN,2017,3,NaN,NaN,NaN,사회혁신기획관청년정책담당관,2017-03-09 20:01,리치몬드과자점 (서대문구연희로26),건강한금융생활지원관련간담회비지급,청년정책담당관 등 4명,카드,36200
6112,11988247,2017년 3월 서울시본청_서울혁신기획관_청년정책담당관 업무추진비 내역,http://opengov.seoul.go.kr/public/11988247,서울시본청,서울혁신기획관,NaN,NaN,NaN,2017,3,NaN,NaN,NaN,사회혁신기획관청년정책담당관,2017-03-03 19:36,할리스 (중구무교로28),긴급생활안정지원 간담회비지급,청년정책담당관 등 5명,카드,24600
6113,11988247,2017년 3월 서울시본청_서울혁신기획관_청년정책담당관 업무추진비 내역,http://opengov.seoul.go.kr/public/11988247,서울시본청,서울혁신기획관,NaN,NaN,NaN,2017,3,NaN,NaN,NaN,사회혁신기획관청년정책담당관,2017-03-02 19:16,목포세발낙지 (중구다동144),청년콘서트및박람회관련간담회비지급,청년정책담당관 등4명,카드,49000

In [153]:
for i in range(3):
    globals()[f"a{i}"] = i

In [168]:
# 수정2 -> 반복실행할때마다 각각의 전역 변수에 데이터프레임을 대입
for file in file_list:
    # file의 이름으로 변수를 생성
    # file에서 2017xx로 되어있는 문자만 출력
    # 처음부터 7번째 문자 전에서 자른다.
    # print(file[:6])
    # '_'를 기준으로 문자를 나눠주고 첫번째를 출력
    # print(file.split('_')[0])
    var_name = file.split('_')[0]
    globals()[f"df_{var_name}"] = pd.read_csv(file_path + file)

In [ ]:
df_201701

In [189]:
# 해당하는 경로의 모든 데이터들이 같은 구조의 데이터프레임이라면 데이터프레임으로 반복적으로 로드하고 유니언 결합(concat())

# 비어있는 리스트에 반복 실행할때마다 append로 추가하는 것과 같다.
# 비어있는 데이터프레임에 반복 실행할때마다 concat()

# 빈 데이터프레임 생성
df2017 = pd.DataFrame()

for file in file_list:
    df = pd.read_csv(file_path + file)
    # df를 df2017에 추가
    df2017 = pd.concat( [df2017, df], axis = 0 )

In [190]:
len(df2017)

70132

In [200]:
# 2019년도의 데이터를 하나의 데이터프레임으로 생성

file_path = "../csv/2019/"
file_list = os.listdir(file_path)

df2019 = pd.DataFrame()

for file in file_list:
    df = pd.read_json(file_path + file)
    df2019 = pd.concat( [df2019, df], axis = 0 )

In [192]:
file_path = "../csv/2019/"
file_list = os.listdir(file_path)
file_list

['201901_expense_list.json',
 '201902_expense_list.json',
 '201903_expense_list.json',
 '201904_expense_list.json',
 '201905_expense_list.json',
 '201906_expense_list.json',
 '201907_expense_list.json',
 '201908_expense_list.json',
 '201909_expense_list.json',
 '201910_expense_list.json',
 '201911_expense_list.json',
 '201912_expense_list.json']

In [ ]:
df2019 = pd.DataFrame()

for file in file_list:
    df = pd.read_json(file_path + file)
    # df를 df2019에 추가
    df2019 = pd.concat( [df2019, df], axis = 0 )

In [194]:
len(df2019)

74207

In [218]:
# 특정 경로에 파일의 확장자가 같은 확장자라면 위의 방식으로 그대로 유지
# 2021년도 폴더에는 여러 확장자 존재 -> 위의 방법으로는 불가능
# 전체의 목록을 로드 -> 원하는 확장자 파일의 목록을 새로 생성

file_path = "../csv/2019/201901_expense_list.csv"
# os에서 제공하는 함수 path.split() -> 경로와 파일을 나눠주는 함수
file_dir, file_name = os.path.split(file_path)
# path.splitext() -> 파일명과 확장자로 나눠주는 함수
os.path.splitext(file_name)

('201901_expense_list', '.csv')

In [ ]:
file_list = os.listdir("../csv/2021/")
file_list

In [226]:
new_list = []

for file in file_list:
    # file의 확장자가 csv라면
    # if file.split('.')[-1] == 'csv':
    # if file.endswith('.csv'):
    name, ext = os.path.splitext(file)
    if ext == '.csv':
        new_list.append(file)
new_list

['202101_expense_list.csv',
 '202102_expense_list.csv',
 '202103_expense_list.csv',
 '202104_expense_list.csv',
 '202105_expense_list.csv',
 '202106_expense_list.csv',
 '202107_expense_list.csv',
 '202108_expense_list.csv',
 '202109_expense_list.csv',
 '202110_expense_list.csv',
 '202111_expense_list.csv',
 '202112_expense_list.csv']

In [223]:
glob("../csv/2021/*.csv")

['../csv/2021\\202101_expense_list.csv',
 '../csv/2021\\202102_expense_list.csv',
 '../csv/2021\\202103_expense_list.csv',
 '../csv/2021\\202104_expense_list.csv',
 '../csv/2021\\202105_expense_list.csv',
 '../csv/2021\\202106_expense_list.csv',
 '../csv/2021\\202107_expense_list.csv',
 '../csv/2021\\202108_expense_list.csv',
 '../csv/2021\\202109_expense_list.csv',
 '../csv/2021\\202110_expense_list.csv',
 '../csv/2021\\202111_expense_list.csv',
 '../csv/2021\\202112_expense_list.csv']

### 특정 경로의 파일을 모두 로드 하는 함수 생성
- 매개변수 3개
    - file_path -> 파일의 경로 : str
    - ext -> 확장자 : str -> .csv
    - concat -> 결합방식 : bool -> False
- file_path를 이용해서 파일의 목록을 생성
- file_path에 '/' 더해준다.
- 확장자에 따라서 새로운 목록을 생성
- concat이 True라면
    - 빈 데이터프레임 생성
- False라면
    - 빈 리스트 생성
- 새로운 목록을 이용하여 반복문을 생성
    - 확장자에 따라서 read함수를 지정하고 파일을 로드
    - concat에 따라 concat(), append() 지정
- 결과물을 되돌려준다.

In [ ]:
def data_load_os( file_path, ext = '.csv', concat = False):
    # file_path에 '/'를 더해준다.
    file_path = file_path + '/'
    # file_path의 파일 목록을 로드
    file_list = os.listdir(file_path)
    # ext에 맞는 확장자 파일만 존재하는 새로운 리스트를 생성
    new_list = []
    for name in file_list:
        if name.endswith(ext):
            new_list.append(name)
    # concat에 따라서 빈 데이터프레임을 생성할것인가? 빈 리스트를 생성할 것인가?
    if concat:
        result = pd.DataFrame()
    else:
        result = []
    # 새로운 리스트로 반복 실행
    for name in new_list:
        if ext == '.csv':
            try:
                df = pd.read_csv(file_path + name)
            except:
                df = pd.read_csv(file_path + name, encoding='cp949')
        elif ext == '.json':
            try:
                df = pd.read_json(file_path + name)
            except:
                df = pd.read_json(file_path + name, encoding='cp949')
        elif ext == '.xml':
            try:
                df = pd.read_xml(file_path + name)
            except:
                df = pd.read_xml(file_path + name, encoding='cp949')
        elif ext in ['.xlsx', '.xls']:
            df = pd.read_excel(file_path + name)
        else:
            return "사용 가능 확장자가 아닙니다."
        
        if concat:
            result = pd.concat([result, df], axis=0)
        else:
            result.append(df)
    # 결과를 되돌려준다.
    return result

In [231]:
df2, df3, df4, df5 = data_load_os(
    "../csv/2022"
)

In [ ]:
df5

In [ ]:
data_load_os("../csv/2022", concat=True)

### 특정 경로의 파일 목록을 불러와서 확장자에게 따라 read함수를 지정하는 함수
- 매개변수 1개
    - 파일의 경로
- 파일의 경로를 이용하여 파일 전체 목록 로드
- 로드한 데이터들이 저장될 빈 리스트 생성
- 목록을 이용하여 반복문을 실행
- 파일의 확장자를 따로 추출하여 확장자에 따라 read_함수를 지정
- 예외처리로 encoding 변환
- 로드가 된 데이터프레임을 빈 리스트에 추가
- 결과를 되돌려준다.

In [271]:
def data_load_glob(file_path):
    # file_path + /* --> 폴더를 포함한 리스트 생성
    # file_path + /*.* --> 폴더를 제외한 리스트 생성
    file_list = glob(file_path + '/*.*')
    # 결과값의 빈 리스트 생성
    result = []
    for name in file_list:
        file_ext = os.path.splitext(name)[-1]
        if file_ext == '.csv':
            try:
                df = pd.read_csv(name)
            except:
                df = pd.read_csv(name, encoding='cp949')
        elif file_ext == '.json':
            try:
                df = pd.read_json(name)
            except:
                df = pd.read_json(name, encoding='cp949')
        elif file_ext in ['.xlsx', '.xls']:
            df = pd.read_excel(name)
        elif file_ext == '.xml':
            try:
                df = pd.read_xml(name)
            except:
                df = pd.read_xml(name, encoding='cp949')
        result. append(df)
    return result

In [272]:
glob("../csv/*.*")

['../csv\\2014.csv',
 '../csv\\2017_expense_list.csv',
 '../csv\\2017_expense_list.xlsx',
 '../csv\\2022년 06월 교통카드통계자료.xls',
 '../csv\\AAPL.csv',
 '../csv\\AMZN.csv',
 '../csv\\boston.csv',
 '../csv\\campaign_master.csv',
 '../csv\\class_master.csv',
 '../csv\\corona.csv',
 '../csv\\csv_exam.csv',
 '../csv\\customer_master.csv',
 '../csv\\dept.csv',
 '../csv\\drinks.csv',
 '../csv\\emp.csv',
 '../csv\\example.csv',
 '../csv\\GM.csv',
 '../csv\\item_master.csv',
 '../csv\\Koweps_Codebook.xlsx',
 '../csv\\MSFT.csv',
 '../csv\\Sales Records.csv',
 '../csv\\Superstore KR - VizLab 2022.xlsx',
 '../csv\\tran_1.csv',
 '../csv\\tran_2.csv',
 '../csv\\tran_d_1.csv',
 '../csv\\tran_d_2.csv',
 '../csv\\uriage.csv',
 '../csv\\use_log.csv',
 '../csv\\USM.csv',
 '../csv\\주민등록.csv']

In [273]:
glob("../csv/*")

['../csv\\2014.csv',
 '../csv\\2017',
 '../csv\\2017_expense_list.csv',
 '../csv\\2017_expense_list.xlsx',
 '../csv\\2018',
 '../csv\\2019',
 '../csv\\2020',
 '../csv\\2021',
 '../csv\\2022',
 '../csv\\2022년 06월 교통카드통계자료.xls',
 '../csv\\AAPL.csv',
 '../csv\\AMZN.csv',
 '../csv\\boston.csv',
 '../csv\\campaign_master.csv',
 '../csv\\card',
 '../csv\\class_master.csv',
 '../csv\\corona.csv',
 '../csv\\csv_exam.csv',
 '../csv\\customer_master.csv',
 '../csv\\dept.csv',
 '../csv\\drinks.csv',
 '../csv\\emp.csv',
 '../csv\\example.csv',
 '../csv\\GM.csv',
 '../csv\\item_master.csv',
 '../csv\\Koweps_Codebook.xlsx',
 '../csv\\MSFT.csv',
 '../csv\\num_1',
 '../csv\\num_2',
 '../csv\\num_3',
 '../csv\\Sales Records.csv',
 '../csv\\Superstore KR - VizLab 2022.xlsx',
 '../csv\\test',
 '../csv\\tran_1.csv',
 '../csv\\tran_2.csv',
 '../csv\\tran_d_1.csv',
 '../csv\\tran_d_2.csv',
 '../csv\\uriage.csv',
 '../csv\\use_log.csv',
 '../csv\\USM.csv',
 '../csv\\주민등록.csv',
 '../csv\\태블로']

In [274]:
test1, test2, test3 = data_load_glob('../csv/test')

In [266]:
test1.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,25844143,2022년 2월 사업소 도로사업소 서부도로사업소 업무추진비 - 기관운영 시책추진 부서운영,http://opengov.seoul.go.kr/expense/25844143,사업소,도로사업소,서부도로사업소,,,2022,2,0,0,,서부도로사업소 기전과,2022-02-11 14:52,다농마트(마포구 월드컵로 235),부서운영 물품구입,기전과장 외 48명,제로페이,230630

In [267]:
test2.head(2)

         Date      Open      High       Low     Close  Adj Close       Volume
0  1980-12-12  0.513393  0.515625  0.513393  0.513393   0.410525  117258400.0
1  1980-12-15  0.488839  0.488839  0.486607  0.486607   0.389106   43971200.0

In [268]:
test3.head(2)

,Row ID,Order ID,Order Date,Delivery Date,Delivery Mode,Customer ID,Customer Name,Customer Segment,Country,Address Region,Address SD,Address SGG,Product ID,Product Name,Product Category,Product Sub-Category,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-BO-10001798,Bush Somerset Collection Bookcase,가구,책장,317364.54,2,0.0,50778.3264
1,2,CA-2020-152156,2020-11-08,2020-11-11,빠른배송,CG-12520,류미령,개인고객,대한민국,호남,광주광역시,북구,FUR-CH-10000454,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",가구,의자,886745.31,3,0.0,266023.5930