# 데이터의 분할
- 분석 모델을 학습하고 성과를 확인하기 위하여 데이터를 train과 test 세트로 나누고 독립변수와 종속변수로 분리하는 작업
- 분석 방법이나 데이터의 양에 따라서 train, validation, test 세트로 분리를 하는 경우도 발생
- 데이터를 분할하는 일반적인 비율
    - Train : Test = 7 : 3 // 8 : 2
        - 가장 일반적으로 데이터를 분할하는 방법
        - 파라미터 수정시에는 Kfold 방식을 이용하여 최적의 파라미터 구성
    - Train : Validation : Test = 6 : 2 : 2
        - 데이터의 양이 굉장히 많은 경우 검증 세트를 생성하여 파라미터 수정
- sklearn의 train_test_split() 함수를 이용하여 데이터를 분할
    - train_test_split(X, Y, test_size = None, random_state = None, shuffle = True, stratify = None)
        - X : 독립 변수 데이터
        - Y : 종속 변수 데이터
        - test_size : 테스트 데이터의 비율 (0부터 1사이 값)
        - random_state : 임의의 데이터를 추출하는 과정에서 seed 값을 지정하면 임의의 데이터를 선택하는 과정이 동일( seed에 따라 랜덤 값에 규칙이 생성 )
        - shuffle : True인 경우 데이터를 섞는다. (시계열이 기준이 데이터에서는 False)
        - stratify : None이 아닌 경우 데이터는 지정한 변수를 기준으로 하여 계층화되어 해당 변수의 비율을 유지하도록 데이터를 분할

In [25]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [26]:
# 샘플 데이터셋을 로드
iris_data = load_iris()

In [27]:
iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5.5, 4.2, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.2],
        [5. , 3.2, 1.2, 0.2],
        [5.5, 3.5, 1.3, 0.2],
        [4.9, 3.6, 1.4, 0.1],
        [4.4, 3. , 1.3, 0.2],
        [5.1, 3.4, 1.5, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [4.5, 2.3, 1.3, 0.3],
        [4.4, 3.2, 1.3, 0.2],
        [5. , 3.5, 1.6, 0.6],
        [5.1, 3.8, 1.9, 0.4],
        [4.8, 3. , 1.4, 0.3],
        [5.1, 3.8, 1.6, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [5.3, 3.7, 1.5, 0.2],
        [5. , 3.3, 1.4, 0.2],
        [7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3.9, 1.2],
        [6. , 2.7, 5.1, 1.6],
        [5.4, 3. , 4.5, 1.5],
        [6. , 3.4, 4.5, 1.6],
        [6.7, 3.1, 4.7, 1.5],
        [6.3, 2.3, 4.4, 1.3],
        [5.6, 3. , 4.1, 1.3],
        [5.5, 2.5, 4. , 1.3],
        [5.5, 2.6, 4.4, 1.2],
        [6.1, 3. , 4.6, 1.4],
        [5.8, 2.6, 4. , 1.2],
        [5. , 2.3, 3.3, 1. ],
        [5.6, 2.7, 4.2, 1.3],
        [5.7, 3. , 4.2, 1.2],
        [5.7, 2.9, 4.2, 1.3],
        [6.2, 2.9, 4.3, 1.3],
        [5.1, 2.5, 3. , 1.1],
        [5.7, 2.8, 4.1, 1.3],
        [6.3, 3.3, 6. , 2.5],
        [5.8, 2.7, 5.1, 1.9],
        [7.1, 3. , 5.9, 2.1],
        [6.3, 2.9, 5.6, 1.8],
        [6.5, 3. , 5.8, 2.2],
        [7.6, 3. , 6.6, 2.1],
        [4.9, 2.5, 4.5, 1.7],
        [7.3, 2.9, 6.3, 1.8],
        [6.7, 2.5, 5.8, 1.8],
        [7.2, 3.6, 6.1, 2.5],
        [6.5, 3.2, 5.1, 2. ],
        [6.4, 2.7, 5.3, 1.9],
        [6.8, 3. , 5.5, 2.1],
        [5.7, 2.5, 5. , 2. ],
        [5.8, 2.8, 5.1, 2.4],
        [6.4, 3.2, 5.3, 2.3],
        [6.5, 3. , 5.5, 1.8],
        [7.7, 3.8, 6.7, 2.2],
        [7.7, 2.6, 6.9, 2.3],
        [6. , 2.2, 5. , 1.5],
        [6.9, 3.2, 5.7, 2.3],
        [5.6, 2.8, 4.9, 2. ],
        [7.7, 2.8, 6.7, 2. ],
        [6.3, 2.7, 4.9, 1.8],
        [6.7, 3.3, 5.7, 2.1],
        [7.2, 3.2, 6. , 1.8],
        [6.2, 2.8, 4.8, 1.8],
        [6.1, 3. , 4.9, 1.8],
        [6.4, 2.8, 5.6, 2.1],
        [7.2, 3. , 5.8, 1.6],
        [7.4, 2.8, 6.1, 1.9],
        [7.9, 3.8, 6.4, 2. ],
        [6.4, 2.8, 5.6, 2.2],
        [6.3, 2.8, 5.1, 1.5],
        [6.1, 2.6, 5.6, 1.4],
        [7.7, 3. , 6.1, 2.3],
        [6.3, 3.4, 5.6, 2.4],
        [6.4, 3.1, 5.5, 1.8],
        [6. , 3. , 4.8, 1.8],
        [6.9, 3.1, 5.4, 2.1],
        [6.7, 3.1, 5.6, 2.4],
        [6.9, 3.1, 5.1, 2.3],
        [5.8, 2.7, 5.1, 1.9],
        [6.8, 3.2, 5.9, 2.3],
        [6.7, 3.3, 5.7, 2.5],
        [6.7, 3. , 5.2, 2.3],
        [6.3, 2.5, 5. , 1.9],
        [6.5, 3. , 5.2, 2. ],
        [6.2, 3.4, 5.4, 2.3],
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 'frame': None,
 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'),
 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n',
 'feature_names': ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 'filename': 'iris.csv',
 'data_module': 'sklearn.datasets.data'}

In [28]:
iris = pd.DataFrame(iris_data['data'], columns=iris_data['feature_names'])
iris.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [29]:
iris['class'] = iris_data['target']
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [30]:
iris_data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [31]:
iris['class'].map(
    {
        0 : 'setosa',
        1 : 'versicolor',
        2 : 'virginica'
    }
)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: class, Length: 150, dtype: object

In [32]:
iris['class'] = iris['class'].map(
    lambda x : iris_data['target_names'][x]
)

In [33]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [34]:
iris.drop('class', axis=1)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [35]:
iris.iloc[:, :-1]

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(
    # 독립변수 : class 컬럼의 데이터를 제외한 부분
    iris.drop('class', axis=1),
    # 종속변수 : class 컬럼
    iris['class'],
    # 테스트 데이터의 비율
    test_size = 0.3,
    # random_seed 설정
    random_state = 100
)

In [37]:
# 데이터의 개수를 확인
print(f"X_train : {X_train.shape}, X_test : {X_test.shape}")
print(f"Y_train : {Y_train.shape}, Y_test : {Y_test.shape}")

X_train : (105, 4), X_test : (45, 4)
Y_train : (105,), Y_test : (45,)

In [38]:
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [39]:
Y_train.value_counts()

class
versicolor    39
setosa        34
virginica     32
Name: count, dtype: int64

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(
    iris.drop('class', axis = 1),
    iris['class'],
    test_size = 0.3,
    random_state = 100,
    stratify = iris['class']
)

In [41]:
Y_train.value_counts()

class
versicolor    35
setosa        35
virginica     35
Name: count, dtype: int64

# 데이터 스케일링
- 대분분 분석 알고리즘은 컬럼 간 데이터의 범위가 크게 차이나는 경우에는 정상적으로 작동을 하지 않는다. (성능이 떨어진다.)
- 값은 범위가 작은 컬럼에 비해서 범위가 큰 컬럼이 종속변수를 예측하는데 큰 영향을 준다고 판단.
- 스케일링 작업은 모든 컬럼의 값의 범위를 같게 만들어주는 작업
- 스케일링 작업 전에 일반적으로 이상치 데이터를 대체하거나 삭제

- 스케일링 순서
    - 데이터 스케일링 하는 경우
        - train, test 나눠져있는 경우에는 train에서 사용한 scaler를 test에서 사용(일반적인 사용법)
    1. Scaler 선택 -> 해당 Scaler를 import
    2. Scaler 객체(class) 생성
    3. train 데이터의 분포를 저장
    4. train 데이터 스케일링
    5. test 데이터 스케일링
    6. 원본 데이터로 변환

### Standard Scaler
- 표준화 방식으로 가장 기본적인 스케일러
- 평균이 0, 분산이 1인 정규분포로 스케일링
- 최솟값과 최댓값의 크기를 따로 제한하지 않아 이상치에 민감하기 때문에 이상치에 대한 확인 및 정제를 한 뒤 사용
- 일반적으로 회귀보다는 분류분석에서 사용

In [42]:
# 스케일러를 선택하고 import
from sklearn.preprocessing import StandardScaler

In [43]:
# Scaler class 생성
StdScaler = StandardScaler()

In [44]:
# train 데이터의 분포를 저장
StdScaler.fit(X_train)

StandardScaler()

In [45]:
# train 데이터를 스케일링
X_train_sc = StdScaler.transform(X_train)

In [46]:
# test 데이터를 스케일링
X_test_sc = StdScaler.transform(X_test)

In [52]:
def scaler_print(train, test):
    print(
        f"""Train Scaled : 
                           {round(train.min(), 2)}
                           {round(train.max(), 2)}
                           {round(train.mean(), 2)}
                           {round(train.std(), 2)}
        """
    )
    print(
        f"""Test Scaled : 
                           {round(test.min(), 2)}
                           {round(test.max(), 2)}
                           {round(test.mean(), 2)}
                           {round(test.std(), 2)}
        """
    )

In [53]:
scaler_print(X_train_sc, X_test_sc)

Train Scaled :
                           -2.14
                           2.75
                           -0.0
                           1.0

Test Scaled :
                           -2.63
                           3.23
                           -0.08
                           1.03

### Min-Max Scaler
- 정규화 방식으로 컬럼의 데이터들을 0과 1사이의 값으로 스케일링하는 방식
- 최솟값 0 최댓값 1
- 이상치에 매우 민감함으로 이상치에 대한 확인 정제 필수
- 일반적으로 분류보다는 회귀에서 사용

In [54]:
from sklearn.preprocessing import MinMaxScaler

MmScaler = MinMaxScaler()

MmScaler.fit(X_train)

X_train_sc = MmScaler.transform(X_train)
X_test_sc = MmScaler.transform(X_test)

scaler_print(X_train_sc, X_test_sc)

Train Scaled :
                           0.0
                           1.0
                           0.45
                           0.27

Test Scaled :
                           -0.1
                           1.1
                           0.43
                           0.27

### Max Abs Scaler
- 최대절댓값과 0이 각각 1, 0이 되도록 스케일링을 하는 정규화 방식으로 모든 값은 -1부터 1 사이로 표현
- 스케일링 대상의 데이터가 모든 양수인 경우라면 MinMaxScaler와 동일
- 이상치에 매우 민감 정제 작업 필요
- 일반적으로 분류보다는 회귀 사용

In [55]:
from sklearn.preprocessing import MaxAbsScaler

In [56]:
MaScaler = MaxAbsScaler()

In [61]:
X_train_sc = MaScaler.fit_transform(X_train)
X_test_sc = MaScaler.transform(X_test)

scaler_print(X_train_sc, X_test_sc)

Train Scaled :
                           0.04
                           1.0
                           0.63
                           0.24

Test Scaled :
                           0.08
                           1.05
                           0.61
                           0.24

### Robust Scaler
- 평균과 분산을 사용하는 Standard 대신에 중앙값과 사분위수를 활용하는 방식
- 중앙값을 0으로 설정 IQR을 사용하여 이상치의 영향을 최소화
- quantile_range 매개변수(기본값이 [0.25, 0.75])의 값을 조정하여 더 넓거나 좁은 범위의 값을 이상치로 판단하게 정제할 수 있다.

In [68]:
from sklearn.preprocessing import RobustScaler

# RuScaler = RobustScaler(quantile_range = (0.2, 0.8))
RuScaler = RobustScaler()

In [69]:
RuScaler.fit(X_train)

RobustScaler()

In [70]:
X_train_sc = RuScaler.transform(X_train)
X_test_sc = RuScaler.transform(X_test)

In [71]:
scaler_print(X_train_sc, X_test_sc)

Train Scaled :
                           -1.33
                           2.0
                           -0.03
                           0.6

Test Scaled :
                           -1.67
                           2.33
                           -0.08
                           0.62

In [73]:
pd.DataFrame(X_train_sc).head()

          0         1         2         3
0  0.230769 -0.333333 -0.111111 -0.066667
1 -0.230769 -0.666667  0.000000 -0.133333
2 -0.615385  1.000000 -0.833333 -0.800000
3 -0.538462  0.833333 -0.833333 -0.733333
4 -0.076923  1.333333 -0.750000 -0.733333

In [75]:
# 스케일링 데이터를 원본의 데이터로 변환
X_origin = RuScaler.inverse_transform(X_train_sc)
pd.DataFrame(X_origin).head()

     0    1    2    3
0  6.1  2.8  4.0  1.3
1  5.5  2.6  4.4  1.2
2  5.0  3.6  1.4  0.2
3  5.1  3.5  1.4  0.3
4  5.7  3.8  1.7  0.3