### 연습문제
- Doc2Vec 라이브러리 이용한 감정에 분석
- 데이터는 ratings_train.txt 파일을 로드
    - 특수 문자, 2칸 이상의 공백의 문자를 제거하는 정규화함수
    - document 컬럼의 데이터에서 중복 데이터를 제거
    - 빈 텍스트, " "가 존재한다면 해당 행 데이터도 제거
    - 상위의 5000개 정도 데이터를 이용
- 토큰화 함수 Komoran를 이용
    - 필요한 품사 : NNP, NNG, VV, VA, MAG, XR만을 사용
    - 불용어 단어 : 하다, 되다, 이다, 것, 수, 거 단어들은 제외
- 데이터에서 독립(document), 종속(label) 변수로 데이터를 나눠주고 train, test 데이터셋을 나눠준다 비율은 8:2
- Doc2Vec 객체를 생성하여 학습
    - 매개변수
        - vector_size = 200
        - window = 5
        - min_count = 2
        - dm = 1
        - negative = 5
        - seed = 42
        - epochs = 50
    - 학습시키는 데이터는 X_train
- X_train, X_test -> 문자열 데이터 -> infer_vector() 함수를 이용해서 임베딩
- 고전 머신러닝 분류 모델을 이용하여 임베딩된 데이터를 독립 변수로 Y의 데이터들을 종속 변수로 학습하여 예측
    - 정확도를 확인
    - LogisticRegression(max_iter=2000, random_state=42)
    - LinearSVC(random_state=42)
    - 두 개의 모델을 사용하여 정확도가 좋은 모델을 선택

In [139]:
import pandas as pd
from konlpy.tag import Komoran
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re
import random
from sklearn.model_selection import train_test_split

In [163]:
data = pd.read_csv('../data/ratings_train.txt', sep='\t')
data

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                    이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[150000 rows x 3 columns]

In [164]:
data['document']

0                                       아 더빙.. 진짜 짜증나네요 목소리
1                         흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나
2                                         너무재밓었다그래서보는것을추천한다
3                             교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정
4         사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...
                                ...
149995                                  인간이 문제지.. 소는 뭔죄인가..
149996                                        평점이 너무 낮아서...
149997                      이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?
149998                          청춘 영화의 최고봉.방황과 우울했던 날들의 자화상
149999                             한국 영화 최초로 수간하는 내용이 담긴 영화
Name: document, Length: 150000, dtype: object

In [165]:
data['document'] = [re.sub(r"[^가-힣0-9a-zA-Z\s\.]", " ", str(text)) for text in data['document']]

In [166]:
data['document'] = [re.sub(r"\s+", " ", text).strip() for text in data['document']]

In [167]:
# for text in data['document']:
#     text = re.sub(r"[^가-힣0-9a-zA-Z\s\.]", " ", str(text))
#     text = re.sub(r"\s+", " ", text).strip()

In [168]:
data['document'] = data['document'].str.strip()

In [169]:
data.drop_duplicates('document', inplace=True)
data

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[144735 rows x 3 columns]

In [170]:
data.dropna(axis=0, inplace=True, ignore_index=True)

In [171]:
data.isna().sum(axis=0)

id          0
document    0
label       0
dtype: int64

In [172]:
data

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
144730   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
144731   8549745                                      평점이 너무 낮아서...      1
144732   9311800                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다      0
144733   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
144734   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[144735 rows x 3 columns]

In [173]:
df = data.head(5000)

In [174]:
# 형태소 분석 Komoran을 이용하여 토큰화
komoran = Komoran()

# 특정 품사만 사용
allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'XR']
# 불용어
stop_word = ['하다', '되다', '이다', '것', '수', '거']

In [175]:
def tokenize(text):
    
    tokens = []
    for word, pos in komoran.pos(text):
        if word not in stop_word and len(word) > 1 and pos in allow_pos:
                tokens.append(word)
    return tokens

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        5000 non-null   int64
 1   document  5000 non-null   object
 2   label     5000 non-null   int64
dtypes: int64(2), object(1)
memory usage: 117.3+ KB

In [177]:
df

            id                                           document  label
0      9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1      3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2     10265843                                  너무재밓었다그래서보는것을추천한다      0
3      9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4      6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...        ...                                                ...    ...
4995   9246120                                       꼭 보세요. 꿀잼입니다      1
4996  10058146              재미도 없고 감동도 없고.. 평점 8.5 이해가 안감. 알바생들인가      0
4997  10077756                                 어디 디비디방에나 있을거같은 영화      0
4998   2887151                                  패러디 영화네 이거왠지 저질일듯      0
4999   8715619                                     으리 으리 으리 으리 으리      1

[5000 rows x 3 columns]

In [178]:
[tokenize(text) for text in df['document']]

[['더빙', '진짜', '짜증', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기', '가볍'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '평점', '조정'],
 ['익살', '연기', '돋보이', '영화', '스파이더맨', '보이', '커스틴 던스트', '너무나'],
 ['걸음마', '초등학교', '학년', '영화', '반개', '아깝'],
 ['원작', '긴장감', '제대로', '살리'],
 ['반개',
  '아깝',
  '나오',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '드라마',
  '가족',
  '연기',
  '못하',
  '사람',
  '모이'],
 ['액션', '재미', '영화'],
 ['평점', '헐리우드', '화려', '너무', '길들이'],
 [],
 ['눈물', '나서', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'],
 ['손들', '횡단보도', '건너', '뛰쳐나오', '이범수', '연기', '드럽'],
 ['담백', '깔끔', '신문', '기사', '로만', '보다', '자꾸', '잊어버리', '사람'],
 ['취향', '존중', '진짜', '극장', '영화', '가장', '감동', '스토리', '어거지', '감동', '어거지'],
 ['매번', '긴장'],
 ['사람', '웃기', '바스코', '이기', '락스', '바비', '이기', '아이돌', '그냥', '안달', '보이'],
 ['굿바이 레닌', '표절', '이해', '갈수록', '재미없'],
 ['이건', '정말', '깨알', '캐스팅', '질퍽', '산뜻', '내용', '구성', '깨알'],
 ['약탈', '위하', '변명', '착하', '절대'],
 ['심오', '그냥', '학생', '선생', '놀아나', '영화', '절대'],
 ['가능'],
 ['재미없',
  '지루',
  '음식',
  '영화',
  '만찬',
  '만찬',
  '이야기',
  '음식',
  '재미',
  '이건',
  '음식',
  '별로',
  '나오',
  '핀란드',
  '풍경',
  '별로',
  '나오'],
 ['절대', '평범', '영화', '수작', '말씀', '드리'],
 ['주제', '중반', '지루'],
 ['짜르', '납득', '그렇', '그렇'],
 ['고추'],
 ['카밀라', '연기'],
 [],
 ['센스', '연출력', '탁월', '캐스팅', '90년대', '향수'],
 ['포스', '위력', '다시', '깨닫', '검사', '연기', '정말', '완전', '명품', '드라마'],
 ['쓰레기', '시간', '아깝'],
 ['재밌', '별점', '이리', '은고'],
 ['라도', '기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하', '열정', '안나', '투어'],
 ['키이라 나이틀리', '연기', '대체', '정신', '장애', '장애'],
 ['작가', '정신', '나가', '유령', '재미있'],
 ['포스터', '보이', '관객'],
 ['영화', '이렇', '평가', '모르'],
 ['단순', '은은', '매력', '영화'],
 ['알바',
  '내용',
  '무섭',
  '거도',
  '웃기',
  '거도',
  '완전',
  '싱겁',
  '영화',
  '시간',
  '아깝',
  '완전',
  '낚이'],
 ['서리', '굶주리'],
 ['정말', '방법'],
 ['윤제문',
  '멋지',
  '배우',
  '발견',
  '소소',
  '일탈',
  '잔잔',
  '미소',
  '머금',
  '음악',
  '조금',
  '아쉽',
  '평점',
  '올리'],
 ['평점', '속지', '마시', '시간', '낭비', '낭비'],
 ['리얼리티',
  '뛰어나',
  '공감',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '툭하면',
  '사람',
  '물건',
  '파손',
  '조금',
  '오바',
  '초반',
  '신선',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불가'],
 ['마이너스', '영화', '수준', '북한', '만들'],
 ['영화', '사랑합니다'],
 ['리스',
  '타르',
  '가르',
  '용의',
  '주인',
  '이랑',
  '근친상간',
  '다니',
  '소설',
  '제일',
  '멋지',
  '자이',
  '니스',
  '드라마',
  '드래곤',
  '제일',
  '멋지',
  '웃음',
  '감독',
  '토르',
  '다크 월드',
  '잡수',
  '기본',
  '선방'],
 ['영화', '사람', '영혼', '어루만지', '거치', '세상사', '잠시', '동화', '영화', '행복'],
 ['게이', '고추', '매운맛', '보이', '진호', '간다'],
 ['이렇', '가슴', '시리', '드라마', '감동', '자체'],
 ['꼬마', '애가', '원한', '그냥', '혼자', '나대', '어쩌'],
 ['재미있'],
 [],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '꺼지',
  '느낌',
  '활력',
  '너무나',
  '무겁',
  '지독',
  '차갑',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '대단',
  '생각'],
 ['심심', '영화'],
 ['백봉기', '언제나'],
 ['그대로', '들어맞', '예측', '카리스마', '악역'],
 ['불알', '나오', '당황', '아무튼', '영화', '중간', '끝나', '느낌'],
 ['평범', '함속', '아든', '평범', '일상', '조금', '밋밋'],
 ['계속',
  '전개도',
  '느리',
  '주인공',
  '은희',
  '나오',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나',
  '기대',
  '전개',
  '빨리빨리'],
 ['사랑', '가슴속', '감정', '헤집', '영화', '요정', '최고'],
 ['사람',
  '우리나라',
  '슬프',
  '현대사',
  '단면',
  '대하',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하',
  '노력',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '명백',
  '살인',
  '살인자'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '내용',
  '시청률',
  '아예',
  '나오',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '불구', '지루', '손예진'],
 ['재밌', '비슷', '영화', '안보', '재미있'],
 ['노래', '실력', '박시환', '가면', '진짜', '망신'],
 ['일본', '영화', '유치'],
 ['이틀',
  '재밌',
  '물건',
  '조작',
  '열리',
  '활짝',
  '열리',
  '들어가',
  '문자',
  '조작',
  '비번',
  '걸리',
  '억지',
  '내용',
  '자체'],
 [],
 ['달팽이', '빠르', '재밌'],
 ['어설프', '전개', '어이없', '결말'],
 ['부패', '로마노프 왕조', '기리', '영화', '온몸', '항거', '러시아', '민중', '그저'],
 ['내용', '전개', '무난', '편이'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오', '리플릿', '사진', '불안'],
 ['단연', '최고'],
 ['감독', '영화', '만들', '관객', '모르', '엉망진창', '개진'],
 ['이건', '우뢰'],
 ['정말', '쓰레기', '영화'],
 ['진정', '위대', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '좋아하', '가요'],
 ['진짜', '부라리', '쓰러지'],
 ['성룡', '영화', '악인'],
 ['때리', '걸스데이', '이혜리'],
 ['서기', '이쁘'],
 ['완전', '재밌', '백인', '공주', '귀여움'],
 ['인상', '영화'],
 ['스티', '완전', '정말', '재밌'],
 ['재미있', '영화'],
 ['클라라', '볼라', '화신'],
 ['진짜', '너무', '슬프', '영화'],
 ['설정', '재밌', '새롭', '에피소드', '메인', '스토리', '차차', '나오', '재밌'],
 ['신카이 마코토', '작화', '카나', '연기', '대박'],
 ['재미없', '진심', '캐스팅'],
 ['잔잔', '생각', '영화인'],
 ['감독', '고은님', '영화'],
 ['무섭', '스토리'],
 ['영화', '억지', '노골적', '광고', '은은', '센스', '어떻'],
 ['킬링타임'],
 ['크리스마스', '떠오르', '영화'],
 ['재미있', '매력', '행복'],
 ['음악', '완전히', '빠지', '영화', '산만'],
 ['태어나', '처음', '영화', '중간', '나오', '불륜', '로맨스'],
 ['짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭'],
 ['솔직히', '별루', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '패널', '가구', '거지', '명작', '드라마', '망치', '서운'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌'],
 ['내용', '전개', '너무나', '느리'],
 ['소재', '흥미', '이야기', '전개', '투박', '몰입'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '보이',
  '안간힘',
  '노력',
  '가상',
  '고증',
  '현실감',
  '떨어지',
  '설정',
  '거북',
  '도대체',
  '이렇',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡', '영화', '우상', '만들', '미국', '따뜻', '설정', '이건'],
 ['2년', '주인공', '생애', '전부', '드러나'],
 ['별점', '가자'],
 ['별로'],
 ['지나', '남기', '재미있'],
 ['아니'],
 ['지나', '다시', '영화', '다시', '순수', '사랑', '감동', '연기'],
 ['올레',
  '공짜',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리',
  '상대',
  '배우',
  '따로',
  '이건',
  '연기자',
  '문제',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들'],
 ['너무', '욕심', '영화', '제대로', '보이'],
 ['빵점'],
 ['아주'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '나라', '만들'],
 ['온몸', '찌릿', '짜릿', '용기', '가지'],
 ['정말', '재미있', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '재밌', '전하', '작품'],
 ['케이블', '그만', '나오'],
 ['다르', '차이밍량', '섞이', '짬뽕', '그릇', '담기'],
 ['여군', '건지', '질리', '다이'],
 [],
 ['한석규', '김혜수', '연기', '돋보이', '영화', '모르', '많이', '어설프', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '떠들석',
  '영화',
  '작품',
  '영화',
  '힘들',
  '정도',
  '정말',
  '만들',
  '마지막',
  '후반부',
  '살짝',
  '아쉽',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝',
  '영화'],
 ['만해'],
 ['재미있', '허풍'],
 ['용가리', '진짜'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '작품',
  '어떻',
  '위하',
  '고민',
  '시간',
  '모건 프리먼',
  '나이',
  '여전히',
  '섹시'],
 ['작가', '별로', '내용', '진짜', '맨날', '그냥', '기대', '재방송', '혹시나', '진짜'],
 ['명작', '명작', '여운', '영화'],
 ['진짜',
  '조금',
  '상업',
  '영화',
  '못하',
  '만들',
  '아쉽',
  '충분히',
  '재미있',
  '개인',
  '조금',
  '잔인',
  '자극',
  '노출',
  '화끈',
  '어떻',
  '국산',
  '영화',
  '많이',
  '아끼',
  '보이'],
 ['그만', '이제', '끝내', '지겹', '지겹'],
 [],
 ['드니', '연기', '일품', '맥스', '죽이'],
 ['괜찮', '작품'],
 ['너무', '영화'],
 ['정말', '실망'],
 ['배우', '영화', '진짜', '모르', '면상', '자신', '모르'],
 ['어린이', '좋아하', '어리', '동심', '멀리'],
 ['무술'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '유명', '영화'],
 ['오랜만'],
 ['아쉽',
  '오늘',
  '방도',
  '방송',
  '대본',
  '완성도',
  '느낌',
  '요즘',
  '드라마',
  '막장',
  '지치',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하',
  '어이없',
  '화이팅'],
 ['평점',
  '조절',
  '위원회',
  '나오',
  '웃음',
  '김혜선',
  '내일이 오면',
  '순정',
  '순정',
  '역할',
  '정도',
  '해내',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지',
  '대하',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하',
  '장면',
  '웃음'],
 ['영화', '끝나', '멍하', '한마디', '나오'],
 ['공유'],
 ['상쾌', '발랄', '영화', '소재', '유쾌', '해설'],
 ['소파', '지키', '이유', '작품'],
 ['로큰롤'],
 ['주되',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없',
  '배경',
  '거슬리'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '내용',
  '뻔하',
  '주인공',
  '목소리',
  '너무',
  '어울리',
  '어제',
  '나가',
  '진심',
  '말리',
  '영국',
  '예산',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10'],
 ['어리', '나이', '좋아하', '로맨틱', '코미디'],
 ['게이', '인줄', '모르'],
 ['알바'],
 ['영화', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답', '영화'],
 ['자극', '익숙', '현대인', '힘들', '연출력'],
 ['당하'],
 ['정말',
  '짜증',
  '극치',
  '보이',
  '영화',
  '굉장히',
  '느낌',
  '뚱뚱',
  '못생기',
  '남자',
  '연기',
  '시종일관',
  '고역',
  '흘러나오',
  '잔잔',
  '클래식',
  '음악',
  '조차',
  '짜증',
  '정도',
  '상당히',
  '영화'],
 ['감동', '감동', '정말', '최고'],
 ['별점',
  '아깝',
  '얼마나',
  '내용',
  '진부',
  '나오',
  '재밌',
  '사람',
  '초딩',
  '죄송',
  '너무',
  '화가',
  '나서',
  '그냥',
  '비판',
  '집기'],
 ['짜증'],
 ['돼지', '닭목', '장면', '에선', '무당'],
 [],
 ['유치', '지루'],
 ['판타지', '가져가'],
 ['윤종신',
  '복귀',
  '이하늘',
  '도대체',
  '뽑히',
  '참가자',
  '실력',
  '따지',
  '심사',
  '위원',
  '인격',
  '실력',
  '오시',
  '그만'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['최고', '영화'],
 ['어리',
  '시절',
  '너무',
  '무섭',
  '재미있',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘',
  '금물',
  '지옥',
  '가요'],
 ['기존', '멜로', '영화', '형식', '탈피', '감정', '절제', '지나치', '너무', '담백', '영화'],
 ['사랑비', '서주', '빠지', '절대', '후회', '도안', '할거'],
 ['이영화', '교훈', '남은', '인생', '화려', '나오'],
 ['추억', '생각', '없이', '가볍', '추천'],
 ['단순', '싸이코', '벗어나'],
 ['만들', '가요', '예전', '만들', '다시', '개봉', '가요', '너무', '접하'],
 ['사랑', '영화', '보고', '연잇', '귀여워'],
 ['청춘 영화', '감성', '넘치', '순간', '지나가', '다시', '돌아오', '순간', '무한', '젊음', '감성'],
 ['건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '웃음', '이안'],
 ['사다코', '서리', '우물', '펀치', '감동'],
 ['후세',
  '사랑',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗',
  '이유',
  '시노',
  '출현',
  '연극',
  '알리',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '노력',
  '보이'],
 ['새벽', '시간', '일본', '영화', '전부', '일본', '영화', '원래', '이러'],
 ['강수연', '나가', '최정원', '신음'],
 ['정말', '김혜성', '너무', '예쁘', '이현진', '정말'],
 ['가발'],
 ['화려', '이인상', '배두나', '연기', '정말'],
 ['10대', '위하', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '필요', '그냥', '닥치'],
 ['각기', '사람', '재밌', '멋지', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '수없', '미묘', '사로잡', '최고'],
 ['너무너무', '훈훈'],
 ['응답하라', '은지원', '원도', '스스로'],
 ['너무', '웃기', '배꼽', '빠지', '영화'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점'],
 ['로드', '몰락', '가져오', '오우삼', '헐리우드', '작품', '가장', '재미없'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['하나에',
  '설레',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '드라마'],
 ['진심', '재미', '너무', '평점', '화나'],
 ['더럽', '재미없', '형태', '허무', '완벽히', '지루', '영화', '영양가', '영화'],
 ['이승기', '정말', '연기', '조연', '연기', '정말'],
 ['현실', '현실'],
 ['오늘', '현충일', '특집', '프로', '매우', '훌륭', '작품'],
 ['의미', '동급'],
 ['제대', '재밌'],
 ['영화',
  '마음',
  '휴가',
  '다녀오',
  '느낌',
  '하지',
  '잔잔',
  '지루',
  '다시',
  '영화',
  '햇살',
  '가득',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '짜임새', '너무', '허술'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '아직',
  '신현준',
  '장군',
  '연기',
  '괜찮',
  '한석규',
  '전성시대',
  '열리',
  '영화',
  '이때',
  '한석규'],
 ['일단', '재생', '괴물', '서스펜스', '귀신', '흡입'],
 ['진짜',
  '댓글',
  '한번쯤',
  '영화인',
  '죽기',
  '직전',
  '소원',
  '들어주',
  '죽기',
  '직전',
  '감동',
  '진짜',
  '영화',
  '발톱',
  '따라가',
  '쓰레기',
  '영화',
  '실망'],
 ['시간',
  '긍정',
  '드라마',
  '보기',
  '오버',
  '연기',
  '거슬리',
  '연기',
  '너무',
  '홍혜정',
  '이그',
  '마도',
  '후련',
  '기도',
  '고시원',
  '나머지',
  '답답',
  '월요일',
  '해피'],
 ['정치인', '모순', '인가', '정치범', '모순'],
 ['어떻', '상상', '대단'],
 ['어렵', '전쟁', '대하', '묘사', '모르'],
 ['일본', '극장판', '만들', '우리나라', '에선', '개봉', '하니', '이건'],
 ['개그콘서트', '전화', '개그', '콘서트', '없애'],
 ['한물', '동서양', '배우', '싸움판'],
 ['기대'],
 ['세계', '최초', '반공', '애니매이션', '역사', '가치'],
 ['감각', '시각', '바라보', '색다르', '느낌', '사랑', '문학'],
 ['엄마', '무고', '감옥살이', '시키', '시키', '이해'],
 ['이영화', '제발', '보세', '감독', '미치', '만들', '정도'],
 ['신나', '흑인', '음악', '아이스 큐브'],
 ['드럽', '재미없', '시간', '시간', '어쩌'],
 ['그저', '한마디', '알리'],
 ['진짜', '생생', '느끼'],
 ['재밌', '평점', '이상', '정도'],
 ['옥소리', '프로필', '사진', '남기', '완전', '대박', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 ['진짜', '너무'],
 ['연기'],
 ['영화', '다시', '나오', '그때', '시절', '나타내'],
 ['중간', '정도', '대단'],
 ['제맛', '제맛'],
 ['소설', '재미없'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['매력', '빠지', '영화'],
 ['모녀', '토막', '살해', '살인자', '성애', '말이', '감동', '사람', '본인', '피해자', '감동', '진심'],
 ['재밌', '평점', '이렇', '구리지'],
 ['아깝', '진짜', '진짜', '명작'],
 ['필름', '아깝', '재미', '더럽', '수준', '매미'],
 [],
 ['영화', '재미있'],
 ['남주인공',
  '연기력',
  '소리',
  '너무',
  '힘들',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '생각',
  '정도',
  '영화',
  '자체',
  '적당히'],
 ['액션', '스릴러', '액션', '스릴'],
 ['완전', '스토리', '엉망', '완전'],
 ['영화', '전달', '모르', '거리'],
 ['영화'],
 ['더빙', '이상', '할머니', '월래', '익숙'],
 ['나오'],
 ['부족'],
 ['정말', '그대로', '영화'],
 ['기억', '진개', '천카이거', '감독', '이름', '기억'],
 ['정은지', '언니', '연기', '노래', '부르', '마지막', '즐겁', '트로트의 연인'],
 [],
 ['망하'],
 ['아이', '시선', '전쟁', '내내', '가슴', '먹먹'],
 ['사람',
  '재미없',
  '레알',
  '기대',
  '생각',
  '여자',
  '복순이',
  '다투',
  '장면',
  '굳이',
  '생각',
  '몰입',
  '겁나',
  '없애',
  '어색',
  '보이'],
 ['설정', '연속극', '느낌', '배우', '연기', '뛰어나'],
 ['여주인공', '인터뷰', '지루', '그냥저냥', '킬링타임', '스릴러'],
 ['박스',
  '오피스',
  '그냥',
  '몰아주',
  '어떻',
  '영화',
  '옛날',
  '90년대',
  '우뢰',
  '수준',
  '폭탄',
  '싸움',
  '가나',
  '폭탄',
  '나가',
  '다르'],
 ['감독', '여자', '보니', '기량', '많이', '딸리'],
 [],
 ['영화', '개연', '허무', '만들', '조디', '포스터', '이쁘', '모습', '영화'],
 [],
 ['스토리', '개막', '사랑이야', '기도', '아니', '시간', '아끼', '호구'],
 ['살리', '아깝', '세기', '대사'],
 ['평점',
  '너무',
  '전혀',
  '재미있',
  '쓸데없이',
  '영화',
  '조연',
  '뒷받침',
  '중요',
  '조연',
  '내용',
  '자체',
  '전혀',
  '여배우',
  '별로',
  '매력',
  '이틀',
  '저스트',
  '고위',
  '애니',
  '스톤',
  '영화',
  '그렇',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '인가', '훈련', '나오', '작살'],
 ['이건',
  '시종일관',
  '제목',
  '야경꾼 일지',
  '지금',
  '넘어가',
  '넘어가',
  '군가',
  '얘기',
  '그렇',
  '순간',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '이해', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '아역',
  '연기',
  '추노',
  '나오',
  '민폐',
  '외국',
  '인줄',
  '초반',
  '그럴싸',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '결말', '이상'],
 ['딱히', '재미'],
 ['송강호', '정말', '연기', '위하', '태어나', '인하', '즐거움', '느끼', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리', '불후의 명작', '그립'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌',
  '살인',
  '대하',
  '감독',
  '해석',
  '정말',
  '재치',
  '배우',
  '모습',
  '정말',
  '유쾌',
  '재밌'],
 ['라파스', '신봉선'],
 ['케이블', '그만', '재탕'],
 ['멋지', '정말', '멋지', '이외'],
 ['어떻', '영화', '만들', '의문', '당대', '최고', '영화', '지금', '결코', '떨어지'],
 ['지금', '한심'],
 ['쓰레기', '연예인', '재기'],
 [],
 ['감동', '드라마'],
 ['발로',
  '만들',
  '영화',
  '지진',
  '나서',
  '주인공',
  '넘어지',
  '사람',
  '유유히',
  '다니',
  'CG',
  '연기',
  '시나리오',
  '내용',
  '정말'],
 ['적당히', '언제', '끝나'],
 ['안개', '워터', '다리', '마스코트'],
 ['사토시',
  '감독',
  '안타깝',
  '돌아가',
  '가슴',
  '먹먹',
  '정말',
  '천재',
  '감독',
  '이제',
  '와서',
  '다시',
  '작품',
  '대작'],
 ['생각'],
 [],
 ['어리',
  '영화로',
  '나이',
  '인생',
  '뭉클',
  '영화',
  '세상',
  '살아가',
  '갈수록',
  '세상',
  '비정',
  '비정',
  '함마',
  '따뜻',
  '친구'],
 ['영상', '너무나', '멋지'],
 ['비디오', '1997년', '도인', '모르', '정도', '만들', '긴장감'],
 [],
 ['만들', '재밌', '영화', '다듬', '소재', '몰입', '기대', '이상', '매끄럽', '부분', '연기'],
 ['지나',
  '코미디',
  '뼈대',
  '가문',
  '이야기',
  '지루',
  '박정아',
  '비롯',
  '배우',
  '민망',
  '연기',
  '펼치',
  '기억'],
 ['군더더기', '없이', '진행', '재미', '문제'],
 ['심심', '재밌', '연기', '배우', '포스'],
 ['괜찮'],
 ['지대', '짜증', '아빠', '민망'],
 [],
 ['순이', '영화'],
 ['최악', '애니메이션', '지루', '재미없', '스토리', '진부'],
 ['의도', '다르', '불쾌', '표현법'],
 ['줄리아', '로버츠', '귀엽', '연인', '5년'],
 ['신선'],
 ['예술가', '사람', '인생', '당시', '시대', '상황', '느끼', '명작'],
 ['관객', '너무', '아쉽', '영화', '베테랑', '류승완', '감독', '역작', '강하', '악역'],
 ['한창', '펭귄', '남북', '거짓', '평화로', '국민', '만들', '영화'],
 ['지금'],
 ['여자', '해서'],
 ['성룡', '단연', '고지'],
 [],
 ['감독', '의도', '전혀', '알아차리'],
 ['하나님', '가정', '온전히', '만들', '진리', '이신', '분이', '만들', '영화', '마음'],
 ['흥미진진', '헤드', '아쉽'],
 ['국산', '코미디', '영화', '신라', '달밤', '제일', '푸근', '따뜻'],
 ['최악', '영화', '오기', '지루'],
 ['탄탄', '배우'],
 ['영화', '점점', '달려가', '몰입', '도가', '영화', '이번', '처음'],
 ['결국', '감독', '자신', '의견', '지존파', '핑계', '지존파', '살인', '정당화', '정부', '사회'],
 ['사실',
  '여부',
  '떠나',
  '아더',
  '너무',
  '원탁',
  '기사',
  '실제',
  '검술',
  '최고',
  '랜스',
  '트리스탄',
  '싸우',
  '검술',
  '마치',
  '중국',
  '검술',
  '흉내',
  '란슬롯',
  '실제',
  '너무',
  '안대',
  '하트',
  '어역',
  '미스'],
 ['대한민국', '영화', '수준', '평균', '하락', '충분', '영상물'],
 [],
 ['재밌'],
 ['재미없', '기대', '완전', '완전', '실망'],
 ['종착역', '인생', '대유', '트레비', '단지', '흘러가'],
 ['시간', '아깝', '영화'],
 ['예쁘', '음악', '동영상', '취미', '영화', '만들', '끝나', '음악', '올인', '하기'],
 ['배우', '연기'],
 ['학위', '위조', '성범죄', '문제', '모으', '영화', '그러', '제작비', '아끼', '패자부활전'],
 ['솔직히'],
 ['완전', '재미있', '알맞'],
 ['잔인', '무섭', '멋있'],
 ['무섭', '기분', '나쁘'],
 ['군더더기', '깔끔', '강하', '메세지', '전달', '뜻밖', '영화'],
 ['영화', '최고', '그냥', '최고'],
 ['그랜드 부다페스트 호텔', '시리즈', '캐스팅', '아깝'],
 ['빨리', '감기', '투자비', '많이', '영화사', '망하'],
 ['도대체',
  '재밌',
  '건지',
  '모르',
  '아이언맨',
  '시리즈',
  '개그',
  '뛰어넘',
  '모르',
  '내용',
  '히어로',
  '놀이',
  '이렇',
  '평점',
  '모르'],
 ['끌어가',
  '중심',
  '캐릭터',
  '영화',
  '살인마',
  '대적',
  '사건',
  '해결',
  '인물',
  '마지막',
  '탈출',
  '나서',
  '잡히',
  '죽이',
  '당하',
  '이해',
  '대체',
  '조달환',
  '정유미',
  '나오'],
 ['리얼', '쓰레기', '영화', '정말', '영화', '절대'],
 ['비록',
  '로봇',
  '점차',
  '인간',
  '감정',
  '가지',
  '자신',
  '대하',
  '고민',
  '결국',
  '인간',
  '앤드',
  '모습',
  '영화',
  '최고',
  '감동',
  '선사',
  '영화'],
 ['영구', '땡칠이', '시리즈', '레전드', '영화'],
 ['초딩',
  '친척',
  '비디오',
  '빌리',
  '기억',
  '너무',
  '재미',
  '나중',
  '우연히',
  '다시',
  '보니',
  '재밌',
  '그렇',
  '재미',
  '초등학교',
  '학년',
  '사촌',
  '당시',
  '최신',
  '비디오',
  '빌리'],
 ['지루', '고요', '서글프', '선속', '머물', '성찰', '사색'],
 ['영화', '진짜', '펑펑', '너무', '슬프'],
 ['내기', '박빙'],
 ['딸리', '심은하', '눈부시', '미모', '아름답', '영상', '메인 주', '제가'],
 ['나오', '아직', '풀리', '이야기', '극장판', '정말', '시간', '모르'],
 ['스토리', '부족', '이상', '진짜'],
 [],
 ['절망', '슬픔', '자신', '챙기', '잔인', '거부', '비참', '대하'],
 ['페이스'],
 ['시간', '흐르', '퇴색', '영화'],
 ['진짜', '어마어마', '여운', '멜로', '영화'],
 ['소피',
  '마르',
  '불륜',
  '내용',
  '망치',
  '물론',
  '실제',
  '역사',
  '이야기',
  '전혀',
  '주인공',
  '공주',
  '한마디',
  '만약',
  '미국인',
  '맞서',
  '싸우',
  '아메리칸',
  '원주민',
  '자유',
  '투쟁기',
  '절대',
  '아카데미상'],
 ['훈훈', '따뜻', '부정', '느끼'],
 [],
 ['정말', '재미있'],
 ['일어나', '느낌', '강하', '영화', '만들', '이유', '군가', '실제로', '따르', '바라', '정장'],
 ['개봉', '당시', '극장', '영화', '내내', '오우삼', '쥑이'],
 ['견자단', '대박', '엽문', '시리즈', '계속'],
 ['정말', '오월', '멜로', '정말로', '계속', '영화', '순위', '순위', '그런지', '야릇', '느낌'],
 ['흥미', '여배우들', '이쁘', '반하'],
 ['스토리', '액션', '그래픽', '건지', '그냥', '게임'],
 ['그냥', '레전드', '레전드'],
 ['평론가',
  '명치',
  '겁나',
  '때리',
  '정말',
  '영화',
  '재미없',
  '생각',
  '재미',
  '인생',
  '도움',
  '가장',
  '영화',
  '본인',
  '깨닫',
  '인생',
  '바꾸'],
 ['키아누 리브스', '최고', '액션 영화'],
 ['소재',
  '아름답',
  '영화',
  '다소',
  '아쉽',
  '부분',
  '이유',
  '영화',
  '영화',
  '로맨스',
  '사실',
  '남자',
  '마음',
  '시선'],
 ['영화', '평론가', '한번', '영화', '울림', '영화'],
 ['재밌', '재탕'],
 ['4대강'],
 ['간첩', '애쓰', '다니'],
 ['검증', '출현', '이탈리아', '특집', '장난'],
 ['정말', '짜증', '보지', '나오'],
 ['슬프'],
 ['악의', '환경', '만화', '만들', '사람', '경의', '보내'],
 [],
 ['여운', '엄청', '영화', '이이경', '사랑', '영화'],
 ['한국', '영화'],
 [],
 ['이상', '가나', '다라'],
 ['혼자',
  '자식',
  '키우',
  '살아오',
  '엄마',
  '아들',
  '힘들',
  '살아오',
  '서로',
  '예민',
  '날카롭',
  '결국',
  '가족',
  '아빠',
  '사람',
  '생각',
  '최악',
  '여자',
  '확실히',
  '요구',
  '도와주',
  '왠지',
  '혼자',
  '괜히',
  '끙끙거리',
  '단순',
  '생각',
  '이든'],
 ['별로', '전개도', '별로', '연기', '별로', '한마디', '재미없'],
 ['지수', '갈팡질팡'],
 [],
 ['너무', '사랑', '감동', '영화', '정말'],
 ['고의', '영화'],
 ['13년',
  '영화',
  '다시',
  '보니',
  '공효진',
  '평수',
  '줄이',
  '콧대',
  '높이',
  '완전',
  '생기',
  '권상우',
  '화산고',
  '왼쪽',
  '팔자',
  '심하',
  '지금',
  '사라지',
  '생기',
  '장혁',
  '멋지',
  '다시',
  '보니'],
 ['말랑말랑'],
 ['공부', '열심히', '공부', '인생'],
 ['그냥', '최고'],
 ['전쟁',
  '이후',
  '아픔',
  '그린',
  '영화',
  '마지막',
  '장면',
  '압권',
  '유대인',
  '더럽',
  '도움',
  '필요',
  '하니',
  '동행',
  '토마스',
  '더럽',
  '유태인',
  '장면',
  '유대인',
  '인척',
  '사실',
  '유대인',
  '가족사진',
  '미묘',
  '감정',
  '사슴',
  '인형',
  '변한',
  '영화'],
 ['오랜만', '동화', '다운', '동화', '기분'],
 ['감사', '정말로', '감사'],
 ['변태'],
 ['샤넬', '인생', '성공', '샤넬', '남자들'],
 ['영화', '내용'],
 ['십수',
  '세월',
  '찰나',
  '순간',
  '찰나',
  '순간',
  '영원',
  '기억',
  '남기',
  '시간',
  '상대',
  '이론',
  '관하'],
 ['니노', '이중', '인격', '연기', '두근거리'],
 ['울컥', '영화', '재미', '감동'],
 ['열정', '돌진', '만들', '영화'],
 ['연기력', '유혹'],
 ['난감', '재미', '세상', '깜짝', '놀라', '센세이션'],
 ['아무리', '노력', '차이나타운', '대놓고', '베끼', '용서'],
 ['신화', '화이팅', '에릭', '화이팅', '모두', '힘내'],
 ['슬프'],
 ['영화관', '어리', '시절', '돌아가', '느낌', '만감'],
 ['정말', '최고', '이민정', '신하균', '연기', '너무'],
 ['재밌', '영화'],
 ['교양',
  '시간',
  '충격',
  '영화',
  '마지막',
  '너무',
  '슬프',
  '빨갱이',
  '소리',
  '지르',
  '초가',
  '갑자기',
  '단어',
  '선생님',
  '대하',
  '그리움',
  '미안',
  '슬픔',
  '초가',
  '마지막',
  '울먹이'],
 [],
 ['무섭', '귀신', '애기', '건지', '그냥', '하기'],
 ['어설프'],
 ['배우', '따뜻', '연기', '일상', '힘겹', '그리', '현실감'],
 ['남자', '배우', '정말', '미스', '캐스팅', '연기력', '조은숙', '김유미', '연기'],
 ['세계',
  '대전',
  '피고',
  '청춘',
  '무기',
  '기술력',
  '세기',
  '전쟁',
  '일으키',
  '정치인',
  '전쟁',
  '지휘',
  '고위',
  '장교',
  '생각',
  '19세기'],
 ['분명히', '시선', '괜찮'],

In [179]:
df['document'] = [tokenize(text) for text in df['document']]

C:\Users\student\AppData\Local\Temp\ipykernel_7932\752334765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['document'] = [tokenize(text) for text in df['document']]

In [180]:
df

            id                                    document  label
0      9976970                           [더빙, 진짜, 짜증, 목소리]      0
1      3819312                   [포스터, 초딩, 영화, 오버, 연기, 가볍]      1
2     10265843                                          []      0
3      9045019                 [교도소, 이야기, 솔직히, 재미, 평점, 조정]      0
4      6483659  [익살, 연기, 돋보이, 영화, 스파이더맨, 보이, 커스틴 던스트, 너무나]      1
...        ...                                         ...    ...
4995   9246120                                          []      1
4996  10058146                    [재미, 감동, 평점, 이해, 안감, 알바]      0
4997  10077756                                    [비디, 영화]      0
4998   2887151                            [패러디 영화, 왠지, 저질]      0
4999   8715619                                          []      1

[5000 rows x 3 columns]

In [181]:
X = df['document'].values
Y = df['label'].values

In [196]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42, stratify=Y
)

In [197]:
tagged = []
for idx, toks in enumerate(X_train):
    # TaggedDocument를 이용하여 문장 당 ID을 부여하고 tagged에 추가
    tagged.append(
        TaggedDocument(words = toks, tags = [f'DOC_{idx}'])
    )
tagged

[TaggedDocument(words=[], tags=['DOC_0']),
 TaggedDocument(words=['서리', '굶주리'], tags=['DOC_1']),
 TaggedDocument(words=[], tags=['DOC_2']),
 TaggedDocument(words=['우연히', '돌리', '사로잡히', '최근', '10년', '코미디 영화', '최고'], tags=['DOC_3']),
 TaggedDocument(words=['찜찜', '감독', '소유진', '죽이'], tags=['DOC_4']),
 TaggedDocument(words=['그냥', '최고', '드라마', '그냥'], tags=['DOC_5']),
 TaggedDocument(words=['컴퓨터', '전기세', '아깝'], tags=['DOC_6']),
 TaggedDocument(words=['위하', '영화'], tags=['DOC_7']),
 TaggedDocument(words=['소문나', '잔치', '호화', '캐스팅'], tags=['DOC_8']),
 TaggedDocument(words=['종교', '분위기', '물씬', '풍기', '최루', '가족', '영화'], tags=['DOC_9']),
 TaggedDocument(words=['진짜', '재미있', '실망', '도라에몽', '극장판', '처음', '이건', '진짜', '재미있'], tags=['DOC_10']),
 TaggedDocument(words=['한일', '월드컵', '시절', '영화', '어설프', '부끄럽'], tags=['DOC_11']),
 TaggedDocument(words=['재밌', '영화'], tags=['DOC_12']),
 TaggedDocument(words=[], tags=['DOC_13']),
 TaggedDocument(words=['에반게리온', '인가'], tags=['DOC_14']),
 TaggedDocument(words=['시간', '다행', '돼지가 우물에 빠진 날', '어떻', '만들', '만들', '마다', '가치', '한심', '엉터리', '이야기', '마술', '배우', '웃기', '전문가', '니들', '전문가', '이렇', '세상', '미치', '돌아가'], tags=['DOC_15']),
 TaggedDocument(words=['쓰레기', '시간', '아깝'], tags=['DOC_16']),
 TaggedDocument(words=['정말', '평범', '별로', '특별'], tags=['DOC_17']),
 TaggedDocument(words=['시청', '조심'], tags=['DOC_18']),
 TaggedDocument(words=['총체', '부실', '위안', '들이', '만들', '중국산', '블럭', '버스', '여전히', '아름답', '정초', '다양', '빛깔', '눈빛', '매력', '지니', '린즈링', '홍콩', '전성기', '이끌', '유덕화', '캐스팅', '화려', '재미', '라고', '눈꼽', '악작'], tags=['DOC_19']),
 TaggedDocument(words=['느낌', '좋아하', '재미'], tags=['DOC_20']),
 TaggedDocument(words=['안나'], tags=['DOC_21']),
 TaggedDocument(words=['스토리', '프로', '아쉽', '소재', '선택'], tags=['DOC_22']),
 TaggedDocument(words=['신나', '흑인', '음악', '아이스 큐브'], tags=['DOC_23']),
 TaggedDocument(words=[], tags=['DOC_24']),
 TaggedDocument(words=['소림축구', '절대'], tags=['DOC_25']),
 TaggedDocument(words=['거부', '몸짓', '하늘'], tags=['DOC_26']),
 TaggedDocument(words=['교도소', '이야기', '솔직히', '재미', '평점', '조정'], tags=['DOC_27']),
 TaggedDocument(words=[], tags=['DOC_28']),
 TaggedDocument(words=['이건', '내용', '결말'], tags=['DOC_29']),
 TaggedDocument(words=['역대', '영화', '한국', '영화', '사상', '손가락', '작품'], tags=['DOC_30']),
 TaggedDocument(words=['결말', '어떻', '가요', '댓글', '남기', '서류', '봉투', '앞부분', '고양이', '그냥', '도망가', '가요', '그냥', '바람', '끝나', '영화', '점점', '그냥', '끝나'], tags=['DOC_31']),
 TaggedDocument(words=['나래', '바꾸', '무스'], tags=['DOC_32']),
 TaggedDocument(words=['어이없', '영화', '함정', '빠지', '유일', '관심'], tags=['DOC_33']),
 TaggedDocument(words=['생애', '최악', '한국', '영화'], tags=['DOC_34']),
 TaggedDocument(words=['헛점', '대본', '연출', '감독', '꼼꼼', '특정', '종교', '찬양', '웃기'], tags=['DOC_35']),
 TaggedDocument(words=['진짜', '쓰레기', '영화', '아깝', '여러분'], tags=['DOC_36']),
 TaggedDocument(words=['개인', '영화감독', '영화', '성공', '예감', '대한민국', '관람객', '수준', '아주', '평가절하', '라고', '단호히'], tags=['DOC_37']),
 TaggedDocument(words=['보아주', '아깝', '영화'], tags=['DOC_38']),
 TaggedDocument(words=['잭 블랙'], tags=['DOC_39']),
 TaggedDocument(words=['혼자', '자식', '키우', '살아오', '엄마', '아들', '힘들', '살아오', '서로', '예민', '날카롭', '결국', '가족', '아빠', '사람', '생각', '최악', '여자', '확실히', '요구', '도와주', '왠지', '혼자', '괜히', '끙끙거리', '단순', '생각', '이든'], tags=['DOC_40']),
 TaggedDocument(words=['김치', '자위', '하네', '대한민국', '아버지', '만들', '남자', '하나', '물어', '평생', '생각', '하등', '존재'], tags=['DOC_41']),
 TaggedDocument(words=['영화', '시리즈', '인해', '휴 잭맨'], tags=['DOC_42']),
 TaggedDocument(words=['진짜', '재미없'], tags=['DOC_43']),
 TaggedDocument(words=['넘치', '덜하', '외면'], tags=['DOC_44']),
 TaggedDocument(words=['최근', '사랑', '전쟁', '영화', '자주', '등장', '만약', '부류', '영화', '사람', '영화', '지금', '드라마', '수준', '앞으로', '계속', '외면'], tags=['DOC_45']),
 TaggedDocument(words=['프랑스', '자국', '전투기', '홍보', '영상'], tags=['DOC_46']),
 TaggedDocument(words=['진짜', '짜증', '영화'], tags=['DOC_47']),
 TaggedDocument(words=['영화', '박자', '디테일', '정말', '시가전', '완벽', '남자', '사랑', '대하', '묘사', '작중', '한석규', '군가', '사랑', '마음', '정말', '디테일', '대단', '마지막', '얘기', '완급', '조절', '완벽', '영화', '정말', '멋지'], tags=['DOC_48']),
 TaggedDocument(words=['무간도', '홍콩', '영화', '명작', '아주', '진짜', '재밌', '평생', '소장', '여명', '진짜', '잘생기'], tags=['DOC_49']),
 TaggedDocument(words=['꽃보다 청춘', '라오스', '정말', '힐링', '프로', '끝나', '너무', '아쉽', '해빙', '엄마'], tags=['DOC_50']),
 TaggedDocument(words=['반개', '아깝', '나오', '이응경', '길용우', '연기', '생활', '정말', '발로', '납치', '감금', '반복', '반복', '드라마', '가족', '연기', '못하', '사람', '모이'], tags=['DOC_51']),
 TaggedDocument(words=['지저분', '공포'], tags=['DOC_52']),
 TaggedDocument(words=['정말', '재밌는 영화'], tags=['DOC_53']),
 TaggedDocument(words=['주인공', '정말', '매력', '멜로', '영화', '감명'], tags=['DOC_54']),
 TaggedDocument(words=['영화', '배경', '음악', '주님', '찬송', '노래', '수없이', '나오', '내용', '성경', '내용', '그대로', '특별', '스토리', '흥미', '요소', '제로', '교인', '평점', '일반인', '실망', '평점', '나뉘', '이유', '꼬옥', '보시', '기전', '바라'], tags=['DOC_55']),
 TaggedDocument(words=['사람', '낚이', '낚이'], tags=['DOC_56']),
 TaggedDocument(words=['별로'], tags=['DOC_57']),
 TaggedDocument(words=['작가', '진짜', '주관', '생각', '없이', '막장', '만들', '다시'], tags=['DOC_58']),
 TaggedDocument(words=['어떻', '평점', '이렇', '개봉', '당시', '극장가', '진짜', '지루', '연기', '개판', '스토리', '개판', '슬프'], tags=['DOC_59']),
 TaggedDocument(words=['정말', '오랜만', '통쾌', '내일', '기대'], tags=['DOC_60']),
 TaggedDocument(words=['은영'], tags=['DOC_61']),
 TaggedDocument(words=['그럭저럭', '딱히', '기억', '남지'], tags=['DOC_62']),
 TaggedDocument(words=['한마디', '컴퓨터', '전기세', '아깝'], tags=['DOC_63']),
 TaggedDocument(words=['별루'], tags=['DOC_64']),
 TaggedDocument(words=['맛깔', '드라마'], tags=['DOC_65']),
 TaggedDocument(words=['긴장감', '조성', '마지막', '귀신'], tags=['DOC_66']),
 TaggedDocument(words=[], tags=['DOC_67']),
 TaggedDocument(words=['볼거리', '흥미진진', '원작', '미치', '훌륭', '특히', '올랜도 블룸'], tags=['DOC_68']),
 TaggedDocument(words=['지금', '전환점', '영화'], tags=['DOC_69']),
 TaggedDocument(words=['세계', '인정', '영화'], tags=['DOC_70']),
 TaggedDocument(words=['추억'], tags=['DOC_71']),
 TaggedDocument(words=['보고서', '화나', '박상면', '낚이'], tags=['DOC_72']),
 TaggedDocument(words=['영화', '태어나'], tags=['DOC_73']),
 TaggedDocument(words=['연출력', '그래픽', '수준', '시대', '어떻', '스마트폰', '착각', '빠지', '경험', '실수', '개뿔', '볼바', '영구', '용가리'], tags=['DOC_74']),
 TaggedDocument(words=['리옹', '진짜', '매력', '영화', '그냥', '킬링타임'], tags=['DOC_75']),
 TaggedDocument(words=['무섭', '답답', '짜증', '영화', '쓸데없이', '공포', '영화', '배경', '연출', '남발', '잔뜩', '기대', '허무', '끝내', '영화'], tags=['DOC_76']),
 TaggedDocument(words=['요즘', '재밌', '시청률', '저조', '요미'], tags=['DOC_77']),
 TaggedDocument(words=['세계', '최초', '반공', '애니매이션', '역사', '가치'], tags=['DOC_78']),
 TaggedDocument(words=['정말', '잔인', '무섭', '장면', '심리', '압박', '공포', '선사', '공포', '영화', '수작'], tags=['DOC_79']),
 TaggedDocument(words=['오늘의 연애', '평점', '알바'], tags=['DOC_80']),
 TaggedDocument(words=[], tags=['DOC_81']),
 TaggedDocument(words=['고현정', '어제', '진행', '너무'], tags=['DOC_82']),
 TaggedDocument(words=[], tags=['DOC_83']),
 TaggedDocument(words=['개도', '아깝', '대체', '저러', '다니', '이해', '수도', '공감', '영화'], tags=['DOC_84']),
 TaggedDocument(words=['말초', '신경', '자극', '막장', '드라마', '진배없', '드라마', '수준', '높이', '작가', '노력', '짜임새', '많이', '부족'], tags=['DOC_85']),
 TaggedDocument(words=['개뿔'], tags=['DOC_86']),
 TaggedDocument(words=['연출', '스토리', '액션', '하나', '특출', '영화', '특히', '주인공', '여주', '사랑', '얘기', '정말', '정도', '그나마', '18세기', '프랑스', '배경', '대관', '괜찮', '정도'], tags=['DOC_87']),
 TaggedDocument(words=['기존', '계열', '좋아하', '사람', '예찬', '영화', '오만', '포기'], tags=['DOC_88']),
 TaggedDocument(words=['명불허전'], tags=['DOC_89']),
 TaggedDocument(words=['아이들', '보이', '전혀', '부끄럽', '명작', '만화', '영화'], tags=['DOC_90']),
 TaggedDocument(words=['소희', '귀엽', '귀엽'], tags=['DOC_91']),
 TaggedDocument(words=['정말', '명작', '배우', '스토리', '탄탄'], tags=['DOC_92']),
 TaggedDocument(words=['기대', '하나', '도안', '하면', '보기', '영화'], tags=['DOC_93']),
 TaggedDocument(words=['아무리', '노력', '차이나타운', '대놓고', '베끼', '용서'], tags=['DOC_94']),
 TaggedDocument(words=['하나님', '살리'], tags=['DOC_95']),
 TaggedDocument(words=['연기', '요리', '여자', '머리', '치렁치렁', '음식', '헤어쇼', '연기', '기본', '최정윤'], tags=['DOC_96']),
 TaggedDocument(words=['돼지', '베끼'], tags=['DOC_97']),
 TaggedDocument(words=['이렇', '멋지', '영화', '이제'], tags=['DOC_98']),
 TaggedDocument(words=['영호', '변하', '너무', '두렵'], tags=['DOC_99']),
 TaggedDocument(words=['코믹', '짜임새', '너무', '허술'], tags=['DOC_100']),
 TaggedDocument(words=['드림'], tags=['DOC_101']),
 TaggedDocument(words=['감동', '참고', '영화', '신분', '마지막', '부분', '자막', '나오', '부분', '영화상', '실화', '거지', '진짜', '레알', '현재', '실제로', '실화', '전지현', '피디', '장면', '진짜', '제가', '아니'], tags=['DOC_102']),
 TaggedDocument(words=['스토리', '비주얼', '연출', '연기', '역사', '가장', '위대', '판타지', '서막', '영상미', '캐릭터', '취하', '지루'], tags=['DOC_103']),
 TaggedDocument(words=['세기', '최고', '영화음악'], tags=['DOC_104']),
 TaggedDocument(words=['악당', '약하', '액션', '답답', '영화', '특히', '아들', '답답', '짜증', '유발'], tags=['DOC_105']),
 TaggedDocument(words=['재밌', '감동', '영화'], tags=['DOC_106']),
 TaggedDocument(words=['장난', '감우성', '최강희', '배우', '이한', '감독', '진짜', '미치', '블랙리스트', '순위'], tags=['DOC_107']),
 TaggedDocument(words=['스토리', '솔직히', '기대', '천사와 악마', '싸움', '최소한', '액션', '걸맞', '기대', '정말', '아날로그', '방식', '속편', '의식', '만들', '속편', '나오', '의문'], tags=['DOC_108']),
 TaggedDocument(words=['도대체', '후속작', '감독', '바뀌', '영화', '개판'], tags=['DOC_109']),
 TaggedDocument(words=['유전무죄 무전유죄'], tags=['DOC_110']),
 TaggedDocument(words=['중반', '정말', '따분', '그나마', '갈수록', '급박', '억지로', '끼우', '맞추', '전개', '나가', '느낌', '강하'], tags=['DOC_111']),
 TaggedDocument(words=['남자', '주인공', '장승'], tags=['DOC_112']),
 TaggedDocument(words=['저스틴 팀버레이크', '완전', '이건', '영화', '자체', '완전'], tags=['DOC_113']),
 TaggedDocument(words=['정말', '재미있', '음악', '템포', '편집', '기술', '두드러지', '작품'], tags=['DOC_114']),
 TaggedDocument(words=['타이타닉', '여주인공', '남주인공', '의리'], tags=['DOC_115']),
 TaggedDocument(words=['연기', '그러'], tags=['DOC_116']),
 TaggedDocument(words=['성악가', '실화', '바탕', '영화', '기대', '없이', '화려', '생생', '오페라', '무대', '아리아', '호강', '영화', '전혀', '어색', '유지태', '노래', '모습', '놀랍', '영화', '감사'], tags=['DOC_117']),
 TaggedDocument(words=['이건', '무조건', '감독', '잘못'], tags=['DOC_118']),
 TaggedDocument(words=['공부', '열심히', '공부', '인생'], tags=['DOC_119']),
 TaggedDocument(words=['전달', '모르', '영화'], tags=['DOC_120']),
 TaggedDocument(words=['감안', '모순', '전개', '버전', '리메이크', '모티브'], tags=['DOC_121']),
 TaggedDocument(words=['최악', '영화', '오기', '지루'], tags=['DOC_122']),
 TaggedDocument(words=['정말', '최악', '절대로', '영화'], tags=['DOC_123']),
 TaggedDocument(words=['행여나', '여름', '방학', '특선', '보지', '마라'], tags=['DOC_124']),
 TaggedDocument(words=['재밌', '우디', '연기', '인상'], tags=['DOC_125']),
 TaggedDocument(words=['진짜', '재미있', '대박', '신하균'], tags=['DOC_126']),
 TaggedDocument(words=['감독', '변태', '욕구', '드러나', '쓰레기', '영화'], tags=['DOC_127']),
 TaggedDocument(words=['그림', '아기자기', '아름답', '사랑'], tags=['DOC_128']),
 TaggedDocument(words=['천녀유혼', '비하', '표현', '힘들', '영화'], tags=['DOC_129']),
 TaggedDocument(words=['감상문'], tags=['DOC_130']),
 TaggedDocument(words=['미치', '사랑', '나도', '한번쯤', '해보', '영화', '영화', '멋지'], tags=['DOC_131']),
 TaggedDocument(words=['몰입'], tags=['DOC_132']),
 TaggedDocument(words=['재밌'], tags=['DOC_133']),
 TaggedDocument(words=['그대로', '들어맞', '예측', '카리스마', '악역'], tags=['DOC_134']),
 TaggedDocument(words=['엄청나', '여운', '빼놓', '영상미', '따뜻'], tags=['DOC_135']),
 TaggedDocument(words=['형제', '영화', '진짜', '영화', '영화'], tags=['DOC_136']),
 TaggedDocument(words=[], tags=['DOC_137']),
 TaggedDocument(words=['이제', '충분', '억지로', '내용', '끼우', '맞추', '고생'], tags=['DOC_138']),
 TaggedDocument(words=['재미', '스토리', '엉성'], tags=['DOC_139']),
 TaggedDocument(words=['공리', '실컷'], tags=['DOC_140']),
 TaggedDocument(words=['영화', '자본'], tags=['DOC_141']),
 TaggedDocument(words=['개인', '점수', '김희선', '재발견', '취향', '의외로', '빠지', '영화'], tags=['DOC_142']),
 TaggedDocument(words=['리버', '피닉스', '나오', '벌써', '흐르'], tags=['DOC_143']),
 TaggedDocument(words=['한가지', '아쉽', '타임 패러독스', '유전자', '패러독스', '사실'], tags=['DOC_144']),
 TaggedDocument(words=['이영화', '전작', '레전드', '길이길이'], tags=['DOC_145']),
 TaggedDocument(words=['정말', '완벽', '최고', '영화', '꼽히', '영화'], tags=['DOC_146']),
 TaggedDocument(words=['타임', '킬링', '조금', '아깝', '영화', '순간', '다세포 소녀'], tags=['DOC_147']),
 TaggedDocument(words=[], tags=['DOC_148']),
 TaggedDocument(words=['그냥'], tags=['DOC_149']),
 TaggedDocument(words=['무겁', '소재', '깃털', '예술', '영화', '흑백', '영화', '지루함'], tags=['DOC_150']),
 TaggedDocument(words=[], tags=['DOC_151']),
 TaggedDocument(words=['영화', '학교', '재미', '몰입'], tags=['DOC_152']),
 TaggedDocument(words=['눈물', '나서', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'], tags=['DOC_153']),
 TaggedDocument(words=['유럽', '작품', '유럽', '중요', '얘기', '픽션'], tags=['DOC_154']),
 TaggedDocument(words=['스토리', '부족', '이상', '진짜'], tags=['DOC_155']),
 TaggedDocument(words=['접영', '화도', '재미있', '이건'], tags=['DOC_156']),
 TaggedDocument(words=['일단', 'B급 영화', 'B급 영화', '연출', '부족', '부분', '만들', '영화', '재미', '스토리', '연기', '연출'], tags=['DOC_157']),
 TaggedDocument(words=['결국', '감독', '자신', '의견', '지존파', '핑계', '지존파', '살인', '정당화', '정부', '사회'], tags=['DOC_158']),
 TaggedDocument(words=['평점', '이러', '명작'], tags=['DOC_159']),
 TaggedDocument(words=['시원', '장면', '너무', '장난'], tags=['DOC_160']),
 TaggedDocument(words=['무섭', '기분', '나쁘'], tags=['DOC_161']),
 TaggedDocument(words=['내일', '기대'], tags=['DOC_162']),
 TaggedDocument(words=['시나리오', '연기', '연출'], tags=['DOC_163']),
 TaggedDocument(words=['불법', '정비', '달인', '내놓', '불법', '조작', '단속', '이백만', '벌금', '내놓', '지금', '불법', '정비', '단속'], tags=['DOC_164']),
 TaggedDocument(words=['재미있', '연기', '삼류', '배우', '얼굴'], tags=['DOC_165']),
 TaggedDocument(words=['이건', '영화', '이름', '붙이', '민망', '연기', '이건', '스토리'], tags=['DOC_166']),
 TaggedDocument(words=['최악', '스토리', '결혼식', '깽판', '그렇', '택연', '미도', '감동', '장임', '그나마', '마동석', '마누라'], tags=['DOC_167']),
 TaggedDocument(words=['불법', '외국인', '노동자', '미화', '영화', '아깝'], tags=['DOC_168']),
 TaggedDocument(words=[], tags=['DOC_169']),
 TaggedDocument(words=['액션', '약하', '스토리', '약하', '에선', '개선'], tags=['DOC_170']),
 TaggedDocument(words=['성유리', '진짜', '짜증', '캐릭터', '본인', '일부러', '짜증', '그렇', '걱정', '을사', '얼른', '기억', '돌아오', '행동', '후회', '나오'], tags=['DOC_171']),
 TaggedDocument(words=['개인', '프렌즈', '생각'], tags=['DOC_172']),
 TaggedDocument(words=['영화', '평점', '이유', '모르'], tags=['DOC_173']),
 TaggedDocument(words=['연기', '그냥', '웃기'], tags=['DOC_174']),
 TaggedDocument(words=['기함'], tags=['DOC_175']),
 TaggedDocument(words=['기계', '들어주'], tags=['DOC_176']),
 TaggedDocument(words=['시나리오', '오르', '송강호', '서울', '말씨', '정말', '한국', '진짜', '캐릭터', '소화', '사람', '웃기', '영화'], tags=['DOC_177']),
 TaggedDocument(words=['당하'], tags=['DOC_178']),
 TaggedDocument(words=['리키', '주근깨', '얼굴', '마지막', '장면', '울부짖', '모습', '잊히', '지질'], tags=['DOC_179']),
 TaggedDocument(words=['대놓고', '욕심', '드러내', '최종', '목적', '드러내', '마카오', '포커페이스', '반하'], tags=['DOC_180']),
 TaggedDocument(words=['평점', '보구', '시간', '돌리', '공포', '스토리', '절대', '절대', '보지'], tags=['DOC_181']),
 TaggedDocument(words=['확실히', '제임스 완', '감독'], tags=['DOC_182']),
 TaggedDocument(words=['여운', '엄청', '영화', '이이경', '사랑', '영화'], tags=['DOC_183']),
 TaggedDocument(words=['즐겁', '보고 싶다', '생각', '정도'], tags=['DOC_184']),
 TaggedDocument(words=['사랑'], tags=['DOC_185']),
 TaggedDocument(words=['마지막', '결투', '최고', '폭풍', '눈물', '팝핀현준', '할아버지'], tags=['DOC_186']),
 TaggedDocument(words=['초반', '10분', '전부'], tags=['DOC_187']),
 TaggedDocument(words=['사건', '연계', '감정', '표현', '집중', '정작', '필요', '느낌'], tags=['DOC_188']),
 TaggedDocument(words=['진짜', '대박', '재밌', '크루즈'], tags=['DOC_189']),
 TaggedDocument(words=['로드리게스', '영화', '최고', '셀마', '최고', '음악', '액션'], tags=['DOC_190']),
 TaggedDocument(words=['이전', '이미', '신데렐라', '러브 스토리'], tags=['DOC_191']),
 TaggedDocument(words=['역작', '고증', '무지', '힘쓰', '드라마'], tags=['DOC_192']),
 TaggedDocument(words=[], tags=['DOC_193']),
 TaggedDocument(words=['이유', '없이', '그냥', '가슴', '오래도록', '가끔', '문득', '생각', '영화'], tags=['DOC_194']),
 TaggedDocument(words=['감독', '내공', '부족'], tags=['DOC_195']),
 TaggedDocument(words=['진짜', '재밌'], tags=['DOC_196']),
 TaggedDocument(words=['눈물', '힘들', '사람', '더욱', '공감', '영화'], tags=['DOC_197']),
 TaggedDocument(words=['전쟁', '영화', '좋아하', '강력히', '추천'], tags=['DOC_198']),
 TaggedDocument(words=['이건', '시종일관', '제목', '야경꾼 일지', '지금', '넘어가', '넘어가', '군가', '얘기', '그렇', '순간', '진짜', '지루함', '지존'], tags=['DOC_199']),
 TaggedDocument(words=['진짜', '재미없', '프로그램'], tags=['DOC_200']),
 TaggedDocument(words=['굉장히', '마음'], tags=['DOC_201']),
 TaggedDocument(words=['아직', '드라마', '인생', '최고'], tags=['DOC_202']),
 TaggedDocument(words=['외로움', '견디', '잔혹', '윌슨', '느끼'], tags=['DOC_203']),
 TaggedDocument(words=['개판', '영화', '청소년', '교훈', '따르', '어른', '모르'], tags=['DOC_204']),
 TaggedDocument(words=['손발', '그러', '미국', '최고', '최고', '파내', '코딱지', '바치', '동네', '편의점', '보안'], tags=['DOC_205']),
 TaggedDocument(words=['하찮', '영화'], tags=['DOC_206']),
 TaggedDocument(words=['영화', '느와르'], tags=['DOC_207']),
 TaggedDocument(words=['고생', '돌아오', '영도', '조선소', '지난해', '선박', '수주', '제로'], tags=['DOC_208']),
 TaggedDocument(words=['재미', '매우'], tags=['DOC_209']),
 TaggedDocument(words=['대중', '공감', '감독', '혼자', '공감'], tags=['DOC_210']),
 TaggedDocument(words=['계속', '전개도', '느리', '주인공', '은희', '나오', '소극', '모습', '짜증', '맨날', '언제', '끝나', '기대', '전개', '빨리빨리'], tags=['DOC_211']),
 TaggedDocument(words=['삼류', '포장', '일류', '최고'], tags=['DOC_212']),
 TaggedDocument(words=['동물', '아이', '이용', '편찮', '눈물', '의미'], tags=['DOC_213']),
 TaggedDocument(words=['심심', '의외로', '웃기', '영화'], tags=['DOC_214']),
 TaggedDocument(words=['시간', '여행', '다루', '아주', '괜찮', '초반', '이후', '지루', '진지', '떨어지', '청소년', '아쉽'], tags=['DOC_215']),
 TaggedDocument(words=['기대', '완전', '웃기', '완전', '재밌'], tags=['DOC_216']),
 TaggedDocument(words=['감독', '실망', '호화', '배역', '아깝', '죽도', '엉성'], tags=['DOC_217']),
 TaggedDocument(words=['평점'], tags=['DOC_218']),
 TaggedDocument(words=['아니', '근래', '다크', '히어로', '무비', '최고', '아주', '그냥', '고스트', '라이', '걸리', '스치', '사망'], tags=['DOC_219']),
 TaggedDocument(words=['시간', '지나', '정말', '가슴', '드라마'], tags=['DOC_220']),
 TaggedDocument(words=['반개', '아깝'], tags=['DOC_221']),
 TaggedDocument(words=['최강', '액션', '영화', '정지훈', '액션', '달인'], tags=['DOC_222']),
 TaggedDocument(words=['만화', '비하', '떨어지'], tags=['DOC_223']),
 TaggedDocument(words=['이영화', '망하', '이유', '어처구니없', '스토리', '연기'], tags=['DOC_224']),
 TaggedDocument(words=['키아누 리브스', '불록', '매력', '빠지', '다시'], tags=['DOC_225']),
 TaggedDocument(words=[], tags=['DOC_226']),
 TaggedDocument(words=['쓰레기'], tags=['DOC_227']),
 TaggedDocument(words=['차마', '버티', '처참히', '잠기'], tags=['DOC_228']),
 TaggedDocument(words=['같이', '사람', '손소'], tags=['DOC_229']),
 TaggedDocument(words=['여자', '주인공', '예뻐서'], tags=['DOC_230']),
 TaggedDocument(words=['만들', '재밌', '영화', '다듬', '소재', '몰입', '기대', '이상', '매끄럽', '부분', '연기'], tags=['DOC_231']),
 TaggedDocument(words=['영화', '안내', '예술', '철학', '들여다보', '영감', '영화'], tags=['DOC_232']),
 TaggedDocument(words=['제가', '로우', '영화', '로우', '영화'], tags=['DOC_233']),
 TaggedDocument(words=['아깝', '영화'], tags=['DOC_234']),
 TaggedDocument(words=['생각'], tags=['DOC_235']),
 TaggedDocument(words=['아직', '22', '길이'], tags=['DOC_236']),
 TaggedDocument(words=[], tags=['DOC_237']),
 TaggedDocument(words=['제작비', '투자', '대작'], tags=['DOC_238']),
 TaggedDocument(words=['재밌', '기억', '천녀유혼', '스토리', '너무'], tags=['DOC_239']),
 TaggedDocument(words=['요즘', '상황', '영화', '생각나'], tags=['DOC_240']),
 TaggedDocument(words=['가장', '인상', '영화'], tags=['DOC_241']),
 TaggedDocument(words=['영화', '내내', '모르', '편안', '느끼'], tags=['DOC_242']),
 TaggedDocument(words=['황신혜', '가짜', '가슴', '여균동', '감독', '쓰레기'], tags=['DOC_243']),
 TaggedDocument(words=['정말', '우리나라', '인터스텔라', '만들', '사랑', '이야기', '빠지'], tags=['DOC_244']),
 TaggedDocument(words=['중국', 'OOO'], tags=['DOC_245']),
 TaggedDocument(words=[], tags=['DOC_246']),
 TaggedDocument(words=['감명', '열심히'], tags=['DOC_247']),
 TaggedDocument(words=['보니', '실소', '나오', '영화관', '평점'], tags=['DOC_248']),
 TaggedDocument(words=['원스', '뛰어넘', '최고', '음악', '영화'], tags=['DOC_249']),
 TaggedDocument(words=[], tags=['DOC_250']),
 TaggedDocument(words=['코엑스', '3D', '살리', '애니', '공각기동대', '좋아하', '3D', '느끼', '현실감', '느끼', '심하', '움직임', '대하', '잔상', '자막', '너무', '배치', '조금', '추천'], tags=['DOC_251']),
 TaggedDocument(words=['해리슨 포드', '이제', '한물'], tags=['DOC_252']),
 TaggedDocument(words=['동성애', '개뿔', '예수', '도와주'], tags=['DOC_253']),

In [198]:
model = Doc2Vec(
    documents=tagged,
    vector_size=200,
    window=5,
    min_count=2,
    dm=1,
    negative=5,
    epochs=50,
    seed=42
)

In [199]:
print(model.dv[0])

[ 3.9937291e-03  4.6814997e-03  3.9908858e-03 -3.8314480e-03
 -4.2419406e-03 -2.2635579e-03 -2.1408796e-03  2.3017400e-03
 -3.3316566e-03 -4.2269509e-03 -2.3112886e-03  4.8547448e-03
 -2.3290981e-03  7.4957073e-04  4.3959604e-03  2.1659744e-03
 -4.8574508e-04  4.6649235e-03 -2.9733211e-03  2.7635538e-03
  2.0161439e-03 -1.7593526e-03 -4.6652733e-04 -4.4027977e-03
  2.6354790e-05 -1.3268429e-03  4.9558799e-03 -2.3597134e-03
 -3.3783133e-03  5.6155684e-04 -3.9088447e-03 -3.9828168e-03
 -3.2779609e-03 -3.0482465e-03 -2.1740568e-03 -9.8177430e-04
 -1.2414980e-03  2.8834527e-03  3.4169352e-03 -2.2675032e-03
 -3.1716502e-03  3.9009453e-04 -2.2545273e-03  1.2917519e-05
  3.5882085e-03  1.9421834e-03 -2.7052737e-03 -6.4148841e-04
  9.1473463e-05 -4.0412582e-03  4.9308627e-03  4.1577681e-03
 -1.4912486e-05  2.9250013e-03  2.2532283e-03  4.3304618e-03
  1.8252111e-03 -4.6403361e-03 -1.2257821e-03  1.7938280e-03
 -2.8638006e-04  2.4509085e-03  1.7629319e-03  2.2126525e-03
  2.7716870e-03  2.8847677e-03 -2.4962402e-03  2.3150772e-03
  4.8928885e-03  5.4348528e-04 -3.8619065e-03 -4.2930120e-03
  1.7340661e-03  1.7936617e-03 -3.4890932e-03  6.4671636e-05
 -2.6200353e-03 -2.8520746e-03 -2.6934331e-03 -2.2123181e-03
 -4.8425109e-03 -1.8277490e-03 -2.0273321e-03 -1.5899122e-03
 -2.3815704e-03  3.3646417e-03  2.5002235e-03 -3.0354792e-03
  4.6909929e-04 -7.8608212e-04  2.7938439e-03 -1.2895119e-03
 -7.2759984e-05  4.5123720e-03  3.9216041e-04  4.2014732e-03
 -1.7875701e-03 -1.2568355e-04 -3.6783994e-04 -1.9265926e-03
 -1.0764014e-03 -3.6496222e-03  2.2304254e-03  4.3912022e-03
  4.6876450e-03  4.4950368e-03  4.5208447e-03 -3.8884587e-03
 -3.1386472e-03 -3.3100718e-03 -1.3360244e-03 -3.0907756e-03
 -7.6614082e-04 -1.8827743e-03  2.6860284e-03  3.1987680e-03
 -1.3826489e-03  4.1476442e-03  2.2008359e-03 -3.1148035e-03
  1.3680590e-03  1.7536408e-03  7.6518179e-04  4.6279137e-03
 -7.5467647e-04  3.1727029e-03  1.8974197e-03  3.2479083e-03
  1.1727059e-03  4.9277730e-03 -1.5133285e-03 -4.8884988e-04
  3.0952669e-03 -1.3389135e-03 -3.3999921e-04  1.2304426e-04
 -4.6165837e-03  6.2322855e-04  1.7571896e-03 -4.9102487e-04
 -2.3483514e-04 -4.7396636e-03 -1.4153242e-04 -7.6535228e-04
 -1.0193074e-03 -1.5332019e-03  1.7533600e-04  2.3539292e-03
 -3.7953116e-03  1.1028540e-03  2.7042616e-03 -2.6171077e-03
 -3.7584698e-03 -2.6771927e-03 -4.4519138e-03 -3.4207480e-03
  2.1419853e-03 -2.2136278e-03 -4.2570592e-04 -4.6497257e-03
  3.5308313e-03  8.3802699e-04 -1.8019879e-03 -3.4526808e-03
 -1.9951772e-03  6.0081662e-04  4.9341517e-03  2.6690620e-03
 -4.1156291e-04  3.7830682e-03  4.9148826e-03 -2.1734769e-03
  3.1942362e-03  4.3216543e-03 -2.0646572e-04 -4.9832941e-04
 -3.5436274e-04 -3.1984686e-03 -9.4044150e-04  6.0012279e-04
  4.9991398e-03 -2.9483652e-03  4.6645836e-03 -4.5036018e-04
 -1.7034429e-03 -1.0665113e-03  9.7319129e-04  4.7629667e-03
  1.7494744e-03  4.5531691e-04  8.9970411e-04 -6.8903566e-05
  3.6046826e-03 -1.4348412e-03 -3.3404476e-03  2.8359825e-03
  2.0977824e-03 -4.2418437e-03 -8.2079472e-04  4.9227006e-03]

- Doc2Vec 객체를 생성하여 학습
    - 매개변수
        - vector_size = 200
        - window = 5
        - min_count = 2
        - dm = 1
        - negative = 5
        - seed = 42
        - epochs = 50
    - 학습시키는 데이터는 X_train
- X_train, X_test -> 문자열 데이터 -> infer_vector() 함수를 이용해서 임베딩
- 고전 머신러닝 분류 모델을 이용하여 임베딩된 데이터를 독립 변수로 Y의 데이터들을 종속 변수로 학습하여 예측
    - 정확도를 확인
    - LogisticRegression(max_iter=2000, random_state=42)
    - LinearSVC(random_state=42)
    - 두 개의 모델을 사용하여 정확도가 좋은 모델을 선택

In [200]:
import re, collections
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

In [201]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score

In [202]:
X_train_vec = [model.infer_vector(doc) for doc in X_train]
X_test_vec = [model.infer_vector(doc) for doc in X_test]

In [203]:
log_model = LogisticRegression(max_iter=2000, random_state=42)
log_model.fit(X_train_vec, Y_train)
log_pred = log_model.predict(X_test_vec)
log_acc = accuracy_score(Y_test, log_pred)
log_acc

0.71

In [204]:
svc_model = LinearSVC(random_state=42)
svc_model.fit(X_train_vec, Y_train)
svc_pred = svc_model.predict(X_test_vec)
svc_acc = accuracy_score(Y_test, svc_pred)
svc_acc

0.724

In [206]:
len(model.dv)

4000

In [207]:
len(tagged)

4000

In [215]:
print(len(X_train_vec))
print(len(X_test_vec))
print(len(Y_train))
print(len(Y_test))

4000
1000
4000
1000