### 복습
- 가전 폴더 안에 모든 데이터파일을 로드해서 하나의 데이터프레임으로 생성
- 감정에 대한 데이터들이 3개 분류 -> 2개의 분류로 변경(부정, 중립 -> 부정)
- 감정 데이터가 없는 데이터들은 따로 저장
- train, test의 비율은 8:2
- Dataset을 기존의 Dataset 구성과 같이 작업
- RawText 데이터를 이용하여 감정분석 모델을 생성
- SBERT 모델을 이용하여 임베딩
- 다중퍼셉트론의 모델을 이용하여 감정 분석 (Linear -> ReLU -> DropOut -> Linear)
- 검증 데이터를 이용하여 정확도와 f1_score 확인
- 감정 데이터가 없는 RawText에서 sample(10)를 출력하여 감정 예측

- 다중퍼셉트론 모델이 아닌 머신러닝 모델 (SVC)을 이용하여 감정 분석 예측

In [2]:
import re
from glob import glob
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from sentence_transformers import SentenceTransformer

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
file_list = glob('../data/가전/*.json')
pd.read_json(file_list[0])

,Index,RawText,Source,Domain,MainCategory,ProductName,ReviewScore,Syllable,Word,RDate,GeneralPolarity,Aspects
0,112038,엄마가 갑자기 전화하시더니 집에서 사용하는 노래방 마이크가 사고 싶다고 하시네요.....,SNS,가전,영상/음향가전,(1+1세트) TJ 태진 블루투스 마이크 / 무선 노래방 마이크,3,323,73,20221110,0.0,"[{'Aspect': '제조일/제조사', 'SentimentText': '우리나라 ..."
1,114572,누가 사용하다가 반품한 것만 같은 제품이 와서 조금 당황스러웠어요ㅠㅠ일단 겉 부분에...,SNS,가전,영상/음향가전,(1등급)삼성 QLED 4K TV 138cm(55형) KQ55QT67AFXKR+삼성...,1,317,70,20221119,-1.0,"[{'Aspect': '품질', 'SentimentText': '겉 부분에 여기저기..."
2,114573,노트북과 TV를 연결해서 모니터 하나에서 다 보려고 구매했어요.여러 제품과 비교하고...,SNS,가전,영상/음향가전,4K HDMI 2.0 양방향 선택기,1,311,70,20221113,0.0,"[{'Aspect': '기능', 'SentimentText': ' 그래도 괜찮은 건..."
3,114574,너무 별로예요 ㅡㅡ… 이 정도 퀄리티인 줄 알았으면 안 샀을 거 같네요… 음질이 거...,SNS,가전,영상/음향가전,ASMR 방송용 녹음용 유튜버 핀마이크 삼성/LG스마트폰 C타입 스마트폰 M31-C,1,306,84,20221121,-1.0,"[{'Aspect': '품질', 'SentimentText': '너무 별로예요 ㅡㅡ..."
4,114575,소음이 섞여서 나는 편이에요... 사이즈도 작고 휴대하기 간편해서 손이 자주 가긴 ...,SNS,가전,영상/음향가전,ASMR 방송용 녹음용 유튜버 핀마이크 삼성/LG스마트폰 C타입 스마트폰 M31-C,1,303,73,20221121,-1.0,"[{'Aspect': '소음', 'SentimentText': '소음이 섞여서 나는..."
...,...,...,...,...,...,...,...,...,...,...,...,...
96,114667,이전부터 구매하고 싶어서 계속 눈여겨보다 구매한 락클래식이에요. 포장을 제거하고 제...,SNS,가전,영상/음향가전,엠지텍 락클래식Q9900 (정품),1,290,61,20221120,-1.0,"[{'Aspect': '품질', 'SentimentText': '마감은 좀 문제가 ..."
97,114668,요즘 집에서 작업하면서 핸드폰으로 음악을 들으니 전화를 하거나 핸드폰을 이용할때 자...,SNS,가전,영상/음향가전,오아 아이브릭 휴대용 블루투스 미니 스피커,1,338,78,20221110,-1.0,"[{'Aspect': '디자인', 'SentimentText': '디자인이 좀 그렇..."
98,114669,"처음 들어보는 생소한 브랜드의 tv라 걱정하면서 구입했는데, 역시나 후회 중입니다....",SNS,가전,영상/음향가전,유맥스 139cm 무결점 UHD ／ UHD55L [스탠드형 자가 설치],1,333,79,20221116,-1.0,"[{'Aspect': '소음', 'SentimentText': '별로 소리를 키우지..."
99,114670,최신 기종이라고 해서 기대했는데 구기종보다 못하네요. 소재가 별로여서 예쁜 디자인이...,SNS,가전,영상/음향가전,유맥스 139cm 무결점 UHD ／ UHD55L [스탠드형 자가 설치],1,324,74,20221116,-1.0,"[{'Aspect': '제조일/제조사', 'SentimentText': '최신 기종..."
100,114671,정말 받아보고 너무 실망했던 이어폰 후기입니다~우선 디자인이 너무 별로에요ㅠㅠ사진으...,SNS,가전,영상/음향가전,유선 이어폰,1,302,61,20221111,-1.0,"[{'Aspect': '디자인', 'SentimentText': '우선 디자인이 너..."

In [4]:
total_df = pd.DataFrame()

for file_path in file_list:
    df = pd.read_json(file_path)
    total_df = pd.concat([total_df, df], axis=0)
total_df.reset_index(drop=True, inplace=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056 entries, 0 to 4055
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            4056 non-null   int64
 1   RawText          4056 non-null   object
 2   Source           4056 non-null   object
 3   Domain           4056 non-null   object
 4   MainCategory     4056 non-null   object
 5   ProductName      4056 non-null   object
 6   ReviewScore      4056 non-null   int64
 7   Syllable         4056 non-null   int64
 8   Word             4056 non-null   int64
 9   RDate            4056 non-null   int64
 10  GeneralPolarity  3678 non-null   float64
 11  Aspects          4056 non-null   object
dtypes: float64(1), int64(5), object(6)
memory usage: 380.4+ KB

In [5]:
total_df['GeneralPolarity'].value_counts()

GeneralPolarity
 1.0    2220
 0.0     944
-1.0     514
Name: count, dtype: int64

In [6]:
def normalize(text):
    text = re.sub(r'[^가-힣0-9a-zA-Z\s\.]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [7]:
total_df['RawText'] = total_df['RawText'].map(normalize)

In [8]:
total_df.drop_duplicates(subset='RawText', inplace=True)
total_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4056 entries, 0 to 4055
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            4056 non-null   int64
 1   RawText          4056 non-null   object
 2   Source           4056 non-null   object
 3   Domain           4056 non-null   object
 4   MainCategory     4056 non-null   object
 5   ProductName      4056 non-null   object
 6   ReviewScore      4056 non-null   int64
 7   Syllable         4056 non-null   int64
 8   Word             4056 non-null   int64
 9   RDate            4056 non-null   int64
 10  GeneralPolarity  3678 non-null   float64
 11  Aspects          4056 non-null   object
dtypes: float64(1), int64(5), object(6)
memory usage: 380.4+ KB

In [9]:
na_df = total_df.loc[total_df['GeneralPolarity'].isna(), ]
na_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 378 entries, 13 to 3944
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Index            378 non-null    int64
 1   RawText          378 non-null    object
 2   Source           378 non-null    object
 3   Domain           378 non-null    object
 4   MainCategory     378 non-null    object
 5   ProductName      378 non-null    object
 6   ReviewScore      378 non-null    int64
 7   Syllable         378 non-null    int64
 8   Word             378 non-null    int64
 9   RDate            378 non-null    int64
 10  GeneralPolarity  0 non-null      float64
 11  Aspects          378 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 38.4+ KB

In [10]:
total_df.dropna(inplace=True)

In [11]:
total_df['GeneralPolarity'] = total_df['GeneralPolarity'].map(lambda x: 1 if x == 1.0 else 0)

In [12]:
df = total_df[['RawText', 'GeneralPolarity']]
df

                                                RawText  GeneralPolarity
0     엄마가 갑자기 전화하시더니 집에서 사용하는 노래방 마이크가 사고 싶다고 하시네요.....                0
1     누가 사용하다가 반품한 것만 같은 제품이 와서 조금 당황스러웠어요 일단 겉 부분에 ...                0
2     노트북과 TV를 연결해서 모니터 하나에서 다 보려고 구매했어요.여러 제품과 비교하고...                0
3     너무 별로예요 이 정도 퀄리티인 줄 알았으면 안 샀을 거 같네요 음질이 거의 입 안...                0
4     소음이 섞여서 나는 편이에요... 사이즈도 작고 휴대하기 간편해서 손이 자주 가긴 ...                0
...                                                 ...              ...
4051  사진으로는 잘 체감하지 못했는데 실제 실물을 보니 디자인이 조금 충격적이라고나 할까...                1
4052  이 에어컨의 제일 큰 장점은 조작법에 있는 것 같아요.인공지능 조작이 가능해서 한번...                1
4053  이 제품을 추천하는 이유는요 일단 LED를 통해 공기질을 눈으로 확인할 수 있고 터...                1
4054  인터넷에서 구매하였는데요 이 공기청정기 처음 발견하고 처음에는 오잉 이게뭐지 했어요...                1
4055  제품 소개 골드 빛이 도는 작은 제품으로 색감도 마음에 들고 사이즈도 참 아담하니 ...                0

[3678 rows x 2 columns]

In [13]:
df.rename(columns = {'GeneralPolarity' : 'label'}, inplace=True)
df

C:\Users\student\AppData\Local\Temp\ipykernel_4860\4226988981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'GeneralPolarity' : 'label'}, inplace=True)

                                                RawText  label
0     엄마가 갑자기 전화하시더니 집에서 사용하는 노래방 마이크가 사고 싶다고 하시네요.....      0
1     누가 사용하다가 반품한 것만 같은 제품이 와서 조금 당황스러웠어요 일단 겉 부분에 ...      0
2     노트북과 TV를 연결해서 모니터 하나에서 다 보려고 구매했어요.여러 제품과 비교하고...      0
3     너무 별로예요 이 정도 퀄리티인 줄 알았으면 안 샀을 거 같네요 음질이 거의 입 안...      0
4     소음이 섞여서 나는 편이에요... 사이즈도 작고 휴대하기 간편해서 손이 자주 가긴 ...      0
...                                                 ...    ...
4051  사진으로는 잘 체감하지 못했는데 실제 실물을 보니 디자인이 조금 충격적이라고나 할까...      1
4052  이 에어컨의 제일 큰 장점은 조작법에 있는 것 같아요.인공지능 조작이 가능해서 한번...      1
4053  이 제품을 추천하는 이유는요 일단 LED를 통해 공기질을 눈으로 확인할 수 있고 터...      1
4054  인터넷에서 구매하였는데요 이 공기청정기 처음 발견하고 처음에는 오잉 이게뭐지 했어요...      1
4055  제품 소개 골드 빛이 도는 작은 제품으로 색감도 마음에 들고 사이즈도 참 아담하니 ...      0

[3678 rows x 2 columns]

In [14]:
train_df, test_df = train_test_split(
    df, test_size=0.2, random_state=42, stratify=df['label']
)

In [15]:
train_df['label'].value_counts()

label
1    1776
0    1166
Name: count, dtype: int64

In [1]:
model_name = 'BM-K/KoSimCSE-roberta-multitask'
sbert = SentenceTransformer(model_name)

NameError: name 'SentenceTransformer' is not defined

In [ ]:
class SBERTDataset(Dataset):

    def __init__(self, document, labels):
        with torch.inference_mode():
            self.emb = sbert.encode(document, convert_to_tensor=True, normalize_embeddings=True)
        # labels를 tensor화
        self.labels = torch.tensor(labels, dtype=torch.long)
    def __len__(self):
        # labels의 길이를 되돌려준다
        return len(self.labels)
    def __getitem__(self, idx):
        return self.emb[idx], self.labels[idx]

In [ ]:
train_ds = SBERTDataset(train_df['RawText'].tolist(), train_df['label'].tolist())
test_ds = SBERTDataset(train_df['RawText'].tolist(), test_df['label'].tolist())

In [ ]:
train_dl = DataLoader(train_ds, batch_size = 128, shuffle = True)
test_dl = DataLoader(test_ds, batch_size = 128, shuffle = True)

In [ ]:
class MLPHead(nn.Module):
    def __init__(self, input_dim, hidden = 256, num_classes = 2):
        super().__init__()
        # 다중 퍼셉트론층 구성
        self.net = nn.Sequential(
            # 선형 모델
            nn.Linear(input_dim, hidden),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(hidden, num_classes)
        )
    # 순전파 함수 -> 독립변수를 받아서 예측값을 되돌려준다
    def forward(self, x):

        result = self.net(x)
        return result

In [ ]:
in_dim = sbert.get_sentence_embedding_dimension()   # 출력 피쳐의 수를 되돌려주는 내장함수
in_dim

768

In [ ]:
clf = MLPHead(in_dim)
# 손실함수 -> 예측값과 실젯값의 차이를 확인하는 함수
crit = nn.CrossEntropyLoss()
# 옵티마이저
opt = torch.optim.AdamW(clf.parameters(), lr=2e-4)

In [ ]:
clf.train()

for epoch in range(5):
    total = 0.0
    for x, y in train_dl:
        # x : document데이터가 임베딩 벡터가 된 묶음(tensor)
        # y : labels 데이터가 tensor 형태 묶음
        opt.zero_grad()
        # 순전파
        logits = clf(x)
        # 손실 계산 (예측값, 실젯값)
        loss = crit(logits, y)
        # 역전파
        loss.backward()
        # 스텝
        opt.step()
        total += loss.item() * x.size(0)
    print(f'epoch : {epoch}, loss : {total/len(train_ds)}')

epoch : 0, loss : 0.6629657192265882
epoch : 1, loss : 0.6066930750695156
epoch : 2, loss : 0.5434395130761702
epoch : 3, loss : 0.4803346037297408
epoch : 4, loss : 0.42876135845074115

In [ ]:
clf.eval()

y_true, y_pred = [], []

with torch.inference_mode():
    for x, y in test_dl:
        logits = clf(x)    # 예측 데이터 -> [[ 0.xxxx, 0.xxxx ], [], [], ...]
        pred = logits.argmax(dim=1).tolist()    # 예측 데이터 -> [0, 1, 1, 0, ...]
        # y_true에 y를 리스트의 형태로 변환하고 데이터를 확장시킨다
        y_true.extend(y.tolist())
        y_pred += pred

print('accuracy_score :', accuracy_score(y_true, y_pred))
print('f1_score :', f1_score(y_true, y_pred))

accuracy_score : 0.5692934782608695
f1_score : 0.672858617131063

In [ ]:
samples = na_df['RawText'].sample(10).tolist()
samples

['두딸이 죽을 너무 좋아해서 자주 죽을 만들어 먹습니다. 재료들을 일일히 다져서 죽을 요리하는데 시간도 걸리고 귀찮을 때가 있습니다 죽제조기를 만나면서 얼마나 편해졌는지 몰라요 25분만 소요하면 뚝 딱 온갖 종류의 죽을 만들 수 있어서 너무 좋습니다 두딸이 좋아하는 전복죽 야채죽 닭죽 등 버튼하나만 눌러주면 마법같이 죽이 완성됩니다. 마트에서 사온 전복을 손질해서 바로 죽제조기에 넣었더니 맛나고 따끈따끈한 전복죽이 만들어졌답니다 나이많으신 어르신이나 죽을 좋아하는 아이들이 있는 집이라면 꼭 필요한 제품이라고 생각합니다',
 '코팅팬 수명이 다해서 다른 브랜드로 찾아보고 있던 참에 공간 활용이 큰 이 세트로 구매해봤어요 티타튬 소재 안심이구요 또 팬과 연결된 스텐레이스 부분이 노랗게 기름때 끼는거 정말 보기 싫었는데탈부착이라 깨끗하게 유지 될 거 같았어요 단점은 손잡이 맨 앞쪽 냄비 끼우는 곳 물때 안 끼게 닦는 거랑손잡이를 빼놓고 어디다 뒀는지 기억을 못 할 때가 있어요 그리고 손잡이 끼기 전에 가스불에 올려 놓고 난 후 생각나서 뜨거운 국물 담긴 냄비에 끼울 때 엄청 곤란했었네요 이번만 사용하고 다음에는 다른 브랜드로 갈아 타려고요 저 같이 깜박깜박하는 사람은 화상 입을까 염려돼요',
 '돌리고 돌리고 노래가 생각 나네요. 오늘도 전자레인지는 열심히 돌아갑니다.요즘 단호박 치즈 슬럿에 빠졌거든요.전자렌지만 있으면 간단하게 멋스러운 요리가 탄생합니다.출력조절기능도 가능해서 레토르트 식품 데울 때 쓰기 좋아요. 가끔 설명서에 쓰인대로 돌려도 덜 데워지거나 너무 데워지는 경우가 발생하는데 출력을 조절할수 있어서 그럴일이 없어요.온도 단계가 다양해서 전자렌지는 할수 없었던 그것 저온으로 숙성시키기가 간단하게 되서 굿이에요 . 요거트를 만들 수 있는 전자레인지라서 깜짝 놀랐어요.전자레인지는 그냥 급하게 음식이나 데우는용이라 생각했거든요.요리가 되고 요거트가 만들어지는 건 마법 같아요.',
 '잘못 산거 같네요.아무리 확인하고 보고 또 봐도 모기나 벌레가 죽어 있는 걸 찾을 수가 없어요.이게 효과가 없는 것 같아요.아담하고 가벼운건 좋은데 그러다 보니 세워놔도 스치기만 해도 쓰러지네요.안정감이 없어요.그리고 건전지 사용도 아니고 전기선을 연결해서 사용해야 되다 보니 공간에 한계성도 있고 이동성이 전혀 없네요.사용하는 곳에 꼭 전선줄이 닿는 곳에 콘센트가 있어야 합니다.너무 불편해요. 디자인은 귀엽고 앙증맞은데 그 외에는 전혀 성능을 찾아 볼 수가 없습니다.그냥 호롱불 같은 거 하나 갖다 놓은 것 같네요.일단 더 두고 나중에 치워 버릴거 같아요.',
 'OOO 쓰다가 노즐이 불편하여 구매했는데 다소 물이 적어서 한번 더 채워 넣어야 해요 용량이 아쉽네요. 불편하다면 불편할수 있고 새 물을 좋아하는 사람이라면 상관없을듯 해요.임플란트 하고부터 칫솔질을 해도 개운 하지가 않았는데 사용해보니 좋아요 괜히 제품을 사서 쓰는건 아니네요.잇몸 사이사이에 끼인 음식물을 시원하게 빼주어 상쾌합니다.가성비 적으로 만족합니다. 잘 쓰고 있어요. 하지만 물살이 너무 쎄네요.잇몸 치료중에 구입해서 좀 더 부드러웠으면 해요. 치실보다는 괜찮네여 물살이 너무 쎄서 금방 물이 없어지네요. 수압 조절이 안돼니 아쉽네요',
 '퀄리티가 엄청 좋은 건 아니에요.... 생각했던 것보다 저렴한 느낌이 나서 아쉽네요... 특히 디자인을 엄청 기대했는데 소재 때문에 살짝... 아쉬운 거 같네요... 사진으로 보는 것보다는 별로예요. 실버 색상이 조금 고급지지는 않은 거 같네요. 노이즈 안 잡힌다고 써있길래 그 부분도 조금 기대했거든요... 근데 제가 듣기에는 살짝 노이즈 섞여 나오는 거 같아서 너무 아쉬워요. 음질이 깨끗하기보다는 살짝 울리는 느낌이랄까 다른 제품에 비해 하울링이 조금 더 심한 느낌이 드네요... 그래도 볼륨 조절이 편하고 용이해서 좋아요....',
 '어머머 이건 사야하는 거예요 에스프레소샷잔도 필요했으니까 이걸로 쓰면 될 거 같아요 이렇게 이쁘고 앙증맞고 세련된 디자인과 색상을 지닌 얘네들을 매일 써도 부족할 판에 캠핑때나 쓰라고 하다니요... 베란다에 매일 텐트 치고 캠핑해얄듯요 여튼 우리는 소주잔 대용으로도 스텐 보관통 속에 술잔 4개가 포개져 들어가니 휴대하기도 좋아요 찍힌 로고도 너무 맘에 들게 이쁘구요 크기도 진짜 작아서 맘에 들어요 돌려 잠그는 뚜껑에 걸어둘 수 있는 구멍이 있어서 야외에서 사용하기에 유용하구요 아이스 박스로 구입해서 시리즈로 들고 다님서 뿌듯해 할라구요',
 '벌써 겨울날씨네요 이웃님들 감기조심하세요 오늘 포스팅은 최신형 스마트 TV 구입 후기입니다 장점 1. 놀라운 기술무려 10억개의 컬러를 표현할 수 있다고 하는데 정말 티비 볼 때마다 화질에 감동받습니다.2. 합리적인 가격가격이 매우 합리적입니다. 최신형임에도 불구하고 이 기능과 디자인에 이 가격이라니 만족합니다.3. NFC로 즐기는 사운드스마트폰 호환 기능써서 즐길 수 있어서 만족해요 단점 1. 아쉬운 내구성그렇게 치명적인 건 아니지만 조금 약해보여서 그게 걱정입니다. 조심조심 사용해야 할 것 같아요...',
 '친정엄마가 김치냉장고는 꼭 이 브랜드로 너무 강조해서 샀습니다.그래서 컬러가 마음에 안 들어요 요즘 화사한 외관이 많은데 이건 좀 칙칙해요 그런데 며칠 사용해 보니까 좋긴 좋더라구요 일단 실속 있게 기능이 똑똑합니다 각 칸마다 탈취 기능이 탑재되어 있고 온도 조절 역시 4룸 각각 조절 가능해요 특히 곡류 열대과일 맥주 음료 등 식재료에 맞는 온도 조절이 진짜 편하네요숙성 기능은 아직 사용 안 해봤는데 사용해보고 후기 올릴 게요 새 김치 받으면 숙성 시켜봐야 겠어요 스탠드형은 냉기 손실이 큰데 이걸 잡으려고 칸칸이 커버를 설치했나 봐요',
 '애기 이유식 먹이려고 OOO 다지기 샀는데사자 마다 후속 제품 나오네요 용량은 필요한 것 보다 너무 크고요딱 진짜 한그릇 애기 이유식 만들려고 샀는데 너무 사이즈가 커요.... 튼튼해 보여 오래는 사용할 수있겠어요 한데 아직 초기인 이유식 먹일용도로 쓰기엔 크기가 무게가 오바라 좀 과한 제품 같아요칼날도 두개나 있는데 하나만 쓰지 않을까 싶어요..제품 밑면에 미끄럼 방지 고무가 따로 깔고 사용하게끔 되어 있는데부착식으로 되어 있으면 필요에 따라 쓰면 어떨까 싶은 생각이에요개인적인 견해로 완전히 만족 스럽지는 않지만제품 자체가 문제라기 보다 제 사용 목적에 맞지 않아서이거는 언니 주고 저는 작은거 다시 살까해요 무게 땜에 많이 부담스럽네여']

In [ ]:
id2label = {
    0 : '부정',
    1 : '긍정'
}
@torch.no_grad()
def predict_review(texts, batch_size = 128):

    if isinstance(texts, str):
        texts = [texts]

    texts_norm = [normalize(t) for t in texts]

    # 2개의 모델을 평가모드 전환 clf, sbert
    sbert.eval()
    clf.eval()

    # 결과값
    result = []

    for idx in range(0, len(texts_norm), batch_size):
        batch_texts = texts_norm[idx : idx + batch_size]
  
        # sbert의 encode함수를 이용해서 임베딩 벡터 생성
        embs = sbert.encode(batch_texts, convert_to_tensor=True, normalize_embeddings=True)
        # embs를 clf모델을 이용하여 예측 확률 데이터를 생성
        logits = clf(embs)
        probs = logits.softmax(dim = -1)
        preds = probs.argmax(dim = -1).tolist()

        for idx2, pred in enumerate(preds):
            prob = float(probs[idx2, pred])
     
            review = texts[idx + idx2]
            label = id2label[pred]

            result.append(
                {
                    'text' : review[:30],
                    'prob' : round(prob, 4),
                    'label' : label
                }
            )
    return result

In [ ]:
out_data = predict_review(samples)

In [ ]:
out_data

[{'text': '두딸이 죽을 너무 좋아해서 자주 죽을 만들어 먹습니다.', 'prob': 0.8229, 'label': '긍정'},
 {'text': '코팅팬 수명이 다해서 다른 브랜드로 찾아보고 있던 참에', 'prob': 0.7483, 'label': '부정'},
 {'text': '돌리고 돌리고 노래가 생각 나네요. 오늘도 전자레인지는', 'prob': 0.6071, 'label': '긍정'},
 {'text': '잘못 산거 같네요.아무리 확인하고 보고 또 봐도 모기나', 'prob': 0.8579, 'label': '부정'},
 {'text': 'OOO 쓰다가 노즐이 불편하여 구매했는데 다소 물이 적', 'prob': 0.7941, 'label': '부정'},
 {'text': '퀄리티가 엄청 좋은 건 아니에요.... 생각했던 것보다', 'prob': 0.8507, 'label': '부정'},
 {'text': '어머머 이건 사야하는 거예요 에스프레소샷잔도 필요했으니', 'prob': 0.8133, 'label': '긍정'},
 {'text': '벌써 겨울날씨네요 이웃님들 감기조심하세요 오늘 포스팅은', 'prob': 0.6941, 'label': '긍정'},
 {'text': '친정엄마가 김치냉장고는 꼭 이 브랜드로 너무 강조해서 ', 'prob': 0.6062, 'label': '긍정'},
 {'text': '애기 이유식 먹이려고 OOO 다지기 샀는데사자 마다 후', 'prob': 0.7855, 'label': '부정'}]