#### 감정 분석 자연어 처리
1. data 폴더 안에 ratings_train.txt 파일을 로드
2. 데이터를 상위 500개 데이터만 추출
3. 리뷰 데이터와 감정 데이터로 나눠준다.
4. 리뷰 데이터를 토큰화(komoran함수 이용) -> 벡터화(Word2Vec, 단위 벡터의 평균)
5. Word2Vec 학습
    - window -> 3
    - epochs -> 10
    - min_count -> 5
    - sg -> 1
    - seed -> 42
6. 벡터화(Word2Vec, 단위 벡터의 평균)
7. 분류 모델(SVC, Logistic)
8. train, test을 이용하여 2개의 모델 중 성능이 높은 모델이 무엇인가?
9. 단위 벡터의 평균의 성능과 단위 벡터 + 중요도 평균의 성능의 차이를 확인

In [68]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from konlpy.tag import Komoran
from sklearn.linear_model import LogisticRegression

In [69]:
df = pd.read_csv('../data/ratings_train.txt', sep='\t')
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [70]:
df = df.head(500)
df

           id                                           document  label
0     9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1     3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2    10265843                                  너무재밓었다그래서보는것을추천한다      0
3     9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4     6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
..        ...                                                ...    ...
495  10049872  그냥 기독교영화네요. 좀 더 깊이있는 내용을 기대했는데.. 실망입니다. 영화도 뭔가...      0
496   9427493  그냥 책으로 읽는게 더 절절하게 다가온다. 영화는 내용을 너무 비약하고 삭제해서 행...      0
497   6629097                                        너무나 감동적인 영화      1
498   9995177                              스킨헤드성님들이 이 영화를 싫어합니다.      0
499   9600841                    자동차 매니아인 나의 평점은 5점 이하~속았다...아오~      0

[500 rows x 3 columns]

In [71]:
X = df['document'].values
Y = df['label'].values

In [72]:
import mod

In [73]:
tokenize = mod.bulid_tokenize()

In [74]:
X_tokens = []
for raw in X:
    X_tokens.append(tokenize(raw))
X_tokens

[['더빙', '진짜', '짜증', '나', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기', '가볍'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '없', '평점', '조정'],
 ['익살', '연기', '돋보이', '영화', '스파이더맨', '늙', '보이', '하', '커스틴 던스트', '너무나'],
 ['막', '걸음마', '떼', '초등학교', '학년', '아깝'],
 ['원작', '긴장감', '제대로', '살리'],
 ['반개',
  '아깝',
  '욕',
  '나오',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '이',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '이',
  '드라마',
  '가족',
  '없',
  '연기',
  '못하',
  '사람',
  '모이'],
 ['액션', '없', '재미', '있', '안', '영화'],
 ['왜', '평점', '낮', '꽤', '보', '헐리우드', '너무', '길들이'],
 [],
 ['볼',
  '때',
  '눈물',
  '나서',
  '죽',
  '향수',
  '자극',
  '!!',
  '허진호',
  '감성',
  '절제',
  '멜로',
  '달인',
  '이다'],
 ['울', '손들', '횡단보도', '건너', '때', '뛰쳐나오', '이범수', '연기', '드럽'],
 ['좋', '신문', '기사', '로만', '보다', '보', '자꾸', '잊어버리', '사람'],
 ['취향',
  '존중',
  '진짜',
  '극장',
  '보',
  '영화',
  '가장',
  '노',
  '재',
  '노',
  '감동',
  '스토리',
  '어거지',
  '감동',
  '어거지'],
 ['매번', '긴장'],
 ['참',
  '사람',
  '웃기',
  '바스코',
  '이기',
  '락스',
  '코',
  '까',
  '고',
  '바비',
  '이기',
  '아이돌',
  '깔',
  '그냥',
  '까',
  '안달',
  '난',
  '보이'],
 ['굿바이 레닌', '표절', '이해', '왜', '뒤', '갈수록', '재미없'],
 ['이건', '정말', '깨알', '캐스팅', '내용', '구성', '잘', '버', '러', '진', '깨알', '드', '!!'],
 ['약탈', '위하', '변명', '착하', '절대'],
 ['뜻', '있', '그냥', '학생', '선생', '놀아나', '영화', '절대'],
 ['보', '웃'],
 ['재미없',
  '같',
  '음식',
  '영화',
  '만찬',
  '넘',
  '만찬',
  '이야기',
  '있',
  '음식',
  '보',
  '재미',
  '있',
  '이건',
  '보',
  '없',
  '음식',
  '별로',
  '안',
  '나오',
  '핀란드',
  '풍경',
  '별로',
  '안',
  '나오'],
 ['절대', '영화', '수작', '말씀', '드리'],
 ['주제', '좋', '중반'],
 ['다', '짜르', '납득', '없', '그렇', '꼭', '그렇', '걸', '끄'],
 ['kl', '고추', '털', '하'],
 ['카밀라', '벨', '발', '연기'],
 [],
 ['센스', '있', '연출력', '캐스팅', '90년대', '향수'],
 ['엄',
  '포스',
  '위력',
  '다시',
  '깨닫',
  '하',
  '남',
  '꽃',
  '검사',
  '연기',
  '정말',
  '좋',
  '완전',
  '명품',
  '드라마'],
 ['졸', '쓰레기', '시간', '아깝'],
 ['재밌', '별점', '왜', '이리', '낮', '은고'],
 ['기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하', '열정', '안나', '윈', '투어'],
 ['키이라 나이틀리', '연기', '하', '대체', '정신', '장애', '틱', '장애'],
 ['원', '작가', '정신', '나가', '유령', '재미있'],
 ['포스터', '있', '보이', '관객'],
 ['영화', '왜', '이렇', '평가', '받', '모르'],
 ['매력', '영화'],
 ['다',
  '알바',
  '내용',
  '없',
  '무섭',
  '거도',
  '없',
  '웃기',
  '거도',
  '없',
  '완전',
  '별',
  '싱겁',
  '넘',
  '아깝',
  '완전',
  '낚이'],
 ['오', '서리', '한', '굶주리'],
 ['정말', '맘', '들', '보', '보', '방법', '없'],
 ['윤제문', '멋지', '배우', '발견', '되', '일탈', '미소', '머금', '음악', '조금', '평점', '올리'],
 ['평점', '속지', '마시', '길', '시간', '낭비', '돈', '낭비'],
 ['리얼리티',
  '뛰어나',
  '하',
  '크',
  '공감',
  '안',
  '가',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '일',
  '툭하면',
  '사람',
  '패',
  '욕',
  '물건',
  '파손',
  '조금',
  '오바',
  '극',
  '초반',
  '가',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불가'],
 ['마이너스', '왜', '없', '보', '영화', '수준', '딱', '알', '북한', '만들', '돈', '주더'],
 ['나', '영화', '사랑합니다'],
 ['데',
  '리스',
  '타르',
  '가르',
  '용의',
  '주인',
  '되',
  '누',
  '이랑',
  '근친상간',
  '하',
  '다니',
  '소설',
  '속',
  '제일',
  '멋지',
  '자이',
  '메',
  '라',
  '니스',
  '드',
  '라마속',
  '에선',
  '드래곤',
  '용',
  '제일',
  '멋지',
  '웃음',
  '감독',
  '토르',
  '-2',
  '다크 월드',
  '잡수',
  '기본',
  '선방',
  '하'],
 ['영화',
  '사람',
  '영혼',
  '어루만지',
  '있',
  '거치',
  '세상사',
  '잠시',
  '잊',
  '동화',
  '같',
  '영화',
  '행복'],
 ['르', '게이', '작', '고추', '매운맛', '보이', '콩', '진호', '간다'],
 ['이렇', '가슴', '시리', '보', '드라마', '감동', '자체'],
 ['난', '꼬마', '애가', '원한', '깊', '하', 'OO', '그냥', '혼자', '나대', 'OO', '걸', '어쩌'],
 ['재미있'],
 ['좋'],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '푹',
  '꺼지',
  '하',
  '느낌',
  '활력',
  '없',
  '너무나',
  '무겁',
  '차갑',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '같',
  '생각',
  '들'],
 ['영화'],
 ['백봉기', '언제나', '오'],
 ['보', '그대로', '들어맞', '예측', '카리스마', '없', '악역'],
 ['불알', '나오', '당황', '아무튼', '영화', '중간', '끝나', '느낌'],
 ['함속', '녹', '아든', '일상', '조금'],
 ['보',
  '계속',
  '보',
  '전개도',
  '느리',
  '주인공',
  '은희',
  '컷',
  '나오',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나',
  '기대',
  '하',
  '전개',
  '좀',
  '빨리빨리'],
 ['사랑', '가슴속', '오', '감정', '헤집', '영화', '예', '요정', '말', '최고'],
 ['많',
  '사람',
  '다',
  '큐',
  '보',
  '우리나라',
  '슬프',
  '현대사',
  '단면',
  '대하',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하',
  '노력',
  '말',
  '듣',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '살인',
  '살인자',
  '다',
  '있'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '먹',
  '내용',
  '산',
  '가',
  '시청률',
  '아예',
  '안',
  '나오',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '손예진'],
 ['재밌', '영화', '안보', '신', '재미있'],
 ['노래', '실력', '뽑', '맞', '박시환', 'mama', '가면', '진짜', '망신'],
 ['일본', '영화', '다'],
 ['이틀',
  '다',
  '보',
  '재밌',
  '안',
  '물건',
  '넣',
  '조작',
  '하',
  '안',
  '열리',
  '집',
  '안',
  '활짝',
  '열리',
  '들어가',
  '문자',
  '조작',
  '비번',
  '안',
  '걸리',
  '억지',
  '내용',
  '자체',
  '좋'],
 ['졸', '작'],
 ['달팽이', '빠르', '더', '재밌'],
 ['어설프', '전개', '어이없', '결말'],
 ['부패', '로마노프 왕조', '기리', '같', '영화', '온몸', '항거', '러시아', '민중', '그저', '폭', '돌'],
 ['내용', '전개', '편이', '잘', '보'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '계',
  '속',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오', '리플릿', '사진', '보', '불안'],
 ['단연', '최고', '하'],
 ['감독', '영화', '만들', '관객', '말', '모르', '엉망진창', '개진', '창'],
 ['이건', '우뢰', '매'],
 ['정말', '쓰레기', '영화'],
 ['진정', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '막', '문', '좋아하'],
 ['진짜', '눈', '부라리', '때'],
 ['성룡', '영화', '최', '악인'],
 ['걸스데이', '이혜리', '잘', '되'],
 ['서기', '이쁘'],
 ['완전'],
 ['인상', '영화'],
 ['세', '레', '스티', '완전', '강', '추', '정말', '재밌'],
 ['재미있', '영화'],
 ['클라라', '볼라', '고', '화신', '본'],
 ['진짜', '보', '너무', '슬프', '영화'],
 ['설정', '재밌', '새롭', '에피소드', '메인', '스토리', '차차', '나오', '재밌'],
 ['신카이 마코토', '작화', '미', '유', '카나', '연기', '잘', '더', '대박', '이'],
 ['재미없', '진심', '캐스팅'],
 ['생각', '보', '영화인', '같'],
 ['감독', '고은님', '쓰', '영화', '안', '보'],
 ['무섭', '스토리'],
 ['영화', '속', '억지', '노골적', '술', '광고', '좀', '센스', '있', '하', '어떻'],
 ['킬링타임'],
 ['크리스마스', '떠오르', '영화'],
 ['재미있', '보', '매력', '행복'],
 ['음악', '완전히', '빠지', '보', '영화', '쪼', '하'],
 ['태어나', '처음', '영화', '중간', '나오', '불륜', '로맨스', '냐'],
 ['왕', '짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭', '하'],
 ['솔직히', '나', '별루', '덜', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '되', '패널', '가구', '거지', '명작', '드라마', '다', '망치', '다'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌', '보'],
 ['내용', '전개', '너무나', '느리'],
 ['소재', '흥미', '끌', '이야기', '전개', '몰입', '안'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '있',
  '보이',
  '안간힘',
  '쓰',
  '노력',
  '가상',
  '고증',
  '현실감',
  '떨어지',
  '설정',
  '도대체',
  '왜',
  '이렇',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡', '영화', '좋', '텐', '우상', '만들', '미국', '설정', '이건'],
 ['2년', '삶', '속', '주인공', '생애', '전부', '드러나'],
 ['별점', '가자'],
 ['별로', '다'],
 ['보', '꽤', '지나', '후', '남기', '재미있'],
 ['아니', '이', '왜', '일'],
 ['지나', '다시', '보', '되', '영화', '다시', '보', '순수', '사랑', '감동', '쇼', '펜', '연기'],
 ['올레',
  '공짜',
  '있',
  '보',
  '허',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리',
  '상대',
  '배우',
  '다',
  '따로',
  '이건',
  '연기자',
  '문제',
  '있',
  '보',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들',
  '젤',
  '볼',
  '하'],
 ['너무', '욕심', '많', '영화', '제대로', '보이'],
 ['빵점'],
 ['베', '말', '아주', '잘', '쓰'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '하', '같', '나라', '만들', '믿'],
 ['온몸', '용기', '가지'],
 ['정말', '재미있', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '있', '재밌', '전하', '작품'],
 ['케이블', '그만', '나오'],
 ['다르', '이', '냐', '리', '차이밍량', '안', '섞이', '짬뽕', '그릇', '담기'],
 ['여군', '재', '없', '뭐', '건지', '다', '재', '없', '질리', '다이'],
 ['좋'],
 ['한석규', '김혜수', '연기', '돋보이', '영화', '모르', '많이', '어설프', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '보',
  '되',
  '영화',
  '작품',
  '면',
  '여',
  '전',
  '영화',
  '믿',
  '힘들',
  '정도',
  '정말',
  '잘',
  '만들',
  '마지막',
  '후반부',
  '살짝',
  '아쉽',
  '하',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝',
  '영화'],
 ['보', '만해'],
 ['재미있', '허풍', '떨', '마'],
 ['용가리'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '꼽',
  '있',
  '작품',
  '어떻',
  '살',
  '위하',
  '고민',
  '더',
  '하',
  '되',
  '시간',
  '모건 프리먼',
  '나이',
  '들',
  '여전히'],
 ['작가',
  '별로',
  '다',
  '내용',
  '이',
  '진짜',
  '맨날',
  '그냥',
  '기대',
  '재방송',
  '혹시나',
  '답',
  '없',
  '진짜'],
 ['명작', '명작', '있', '보', '보', '여운', '남', '영화'],
 ['진짜',
  '조금',
  '더',
  '손',
  '좀',
  '보',
  '왜',
  '하',
  '상업',
  '영화',
  '못하',
  '만들',
  '아쉽',
  '충분히',
  '재미있',
  '개인',
  '조금',
  '더',
  '더',
  '자극',
  '노출',
  '화끈',
  '하',
  '어떻',
  '하',
  '국산',
  '영화',
  '많이',
  '아끼',
  '보이'],
 ['그만', '좀', '끌', '이제', '끝내', '지겹', '지겹'],
 [],
 ['드니', '연기', '일품', '맥스', '샘', '죽이', '하'],
 ['괜찮', '작품'],
 ['너무', '좋', '영화'],
 ['정말', '실망'],
 ['배우',
  '지',
  '안',
  '뜨',
  '영화',
  '찍',
  '껀',
  '왜',
  '안',
  '뜨',
  '진짜',
  '모르',
  '면상',
  '딱',
  '보',
  '알',
  '왜',
  '자신',
  '모르'],
 ['어린이', '좋아하', '어리', '동심', '멀리', '뜨', '낫'],
 ['무술', '인', '왜', '총', '들'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '영화'],
 ['오랜만'],
 ['종',
  '방',
  '아쉽',
  '오늘',
  '막',
  '방도',
  '잘',
  '보',
  '방송',
  '대본',
  '꽤',
  '완성도',
  '있',
  '느낌',
  '받',
  '요즘',
  '드라마',
  '막장',
  '지치',
  '향',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하',
  '어이없',
  'MBC',
  '화이팅',
  '!!'],
 ['평점',
  '조절',
  '위원회',
  '나오',
  '웃음',
  '김혜선',
  '내일이 오면',
  '김',
  '순정',
  '순정',
  '역할',
  '정도',
  '잘',
  '해내',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지',
  '있',
  '그녀',
  '대하',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하',
  '장면',
  '같',
  '웃음'],
 ['영화', '끝나', '때', '멍하', '다', '보', '한마디', '나오'],
 ['공유'],
 ['영화', '말', '끌', '성', '소재', '해설'],
 ['소파', '죽', '치', '앉', '지키', '보', '이유', '없', '작품'],
 ['로큰롤', '!!!', '!!!', '!!!', '!!!', '!!'],
 ['주되',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하',
  '알',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없',
  'CG',
  '배경',
  '거슬리'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '남',
  '주',
  '춤',
  '못',
  '추',
  '내용',
  '뻔하',
  '주인공',
  '목소리',
  '너무',
  '안',
  '어울리',
  '어제',
  'CGV',
  '뛰',
  '나가',
  '참',
  '진심',
  '말리',
  '영국',
  '예산',
  'DVD',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10',
  '안'],
 ['어리', '나이', '보', '꽤', '좋아하', '로맨틱', '코미디'],
 ['게이', '물', '인줄', '모르', '보'],
 ['알바', '끄', '절'],
 ['영화', '내', '왜', '받', '보', '알', '이', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답', '영화', '이'],
 ['자극', '현대인', '보', '눈', '떼', '힘들', '연출력'],
 ['읽', '당하'],
 ['정말',
  '짜증',
  '극치',
  '보이',
  '영화',
  '굉장히',
  '느낌',
  '못생기',
  '남자',
  '애',
  '발',
  '연기',
  '시종일관',
  '보',
  '고역',
  '흘러나오',
  '클래식',
  '음악',
  '조차',
  '듣',
  '싫',
  '짜증',
  '날',
  '정도',
  '상당히',
  '싫',
  '영화'],
 ['정말', '최고', '!!!'],
 ['별점',
  '아깝',
  '얼마나',
  '내용',
  '욕',
  '밖',
  '안',
  '나오',
  '재밌',
  '하',
  '사람',
  '초딩',
  '너무',
  '화가',
  '나서',
  '보',
  '없',
  '보',
  '마',
  '그냥',
  '티',
  '비판',
  '짜',
  '집기',
  '같'],
 ['왜', '하', '짜증', '안', '내'],
 ['돼지', '피', '먹', '닭목', '따', '장면', '에선', '무당', '하'],
 [],
 ['잠'],
 ['판타지', '가져가'],
 ['윤종신',
  '복귀',
  '좋',
  '이하늘',
  '도대체',
  '왜',
  '뽑히',
  '알',
  '없',
  '참가자',
  '실력',
  '따지',
  '전',
  '심사',
  '위원',
  '인격',
  '실력',
  '쌓',
  '오시',
  '길',
  '어',
  '허',
  '그만',
  '좀',
  '하'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['생', '최고', '영화'],
 ['어리',
  '시절',
  '너무',
  '무섭',
  '재미있',
  '보',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘',
  '짓',
  '금물',
  '지옥',
  '가요'],
 ['기존', '멜로', '영화', '형식', '탈피', '하', '감정', '절제', '지나치', '너무', '영화'],
 ['나', '사랑비', '서주', '쏙', '빠지', '절대', '잊', '후회', '도안', '할거'],
 ['이영화', '보', '교훈', '남은', '인생', '말', '안', '나오'],
 ['추억', '젖', '가볍', '보', '추천', '요'],
 ['싸이코', '물', '벗어나'],
 ['이', '만들', '예전', '만들', '허', '접하'],
 ['넘', '사랑', '영화', '보고', '연잇', '보', '!!', '넘', '귀여워'],
 ['청춘 영화',
  '있',
  '감성',
  '넘치',
  '순간',
  '지나가',
  '다시',
  '돌아오',
  '테',
  '순간',
  '무한',
  '젊음',
  '있',
  '감성'],
 ['TV', '건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '달', '재', '웃음', '이안', '나'],
 ['사다코', '한', '서리', '감동'],
 ['후세',
  '사랑',
  '되',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗',
  '이유',
  '시노',
  '출현',
  '연극',
  '으',
  '로',
  '더',
  '알리',
  '하',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '하',
  '노력',
  '더',
  '보이',
  '좋'],
 ['새벽', '시간', '하', '일본', '영화', '전부', '개', '졸', '작', '일본', '영화', '원래', '다'],
 ['강수연', '나가', '최정원', '신음', '신'],
 ['정말', '김혜성', '너무', '예쁘', '이현진', '웃', '정말'],
 ['가발', '쓰'],
 [],
 ['10대', '위하', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '말', '필요', '없', '그냥', '닥치', '보'],
 ['각기', '사람', '재밌', '멋지', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '알', '수없', '사로잡', '최고', '!!'],
 ['너무너무'],
 ['응답하라', '은지원', '원도', '스스로', '욕'],
 ['너무', '웃기', '배꼽', '빠지', '컴', '영화', '있'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점', '믿', '없'],
 ['장', '끌', '로드', '몰락', '가져오', '오우삼', '헐리우드', '작품', '가장', '재미없', '졸', '작'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['작',
  '하나에',
  '설레',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '없',
  '드라마'],
 ['진심', '재미', '없', '너무', '평점', '높', '화', '남'],
 ['더럽', '재미없', '형태', '오', '닿', '허무', '완벽히', '영화', '영양가', '없', '영화'],
 ['이승기', '정말', '연기', '잘', '조연', '연기', '정말', '잘'],
 ['현실', '꿈', '꿈', '현실'],
 ['오늘', '현충일', '특집', '프로', '보', '되', '매우', '작품'],
 ['판', '의미', '동급', 'trash', 'of', 'the', 'trash'],
 ['제대', '보', '더', '재밌'],
 ['영화',
  '보',
  '마음',
  '휴가',
  '다녀오',
  '느낌',
  '소',
  '박',
  '하지',
  '다시',
  '보',
  '영화',
  '햇살',
  '가득',
  '이',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '좋', '짜임새', '너무'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '없',
  '아직',
  '신현준',
  '황',
  '장군',
  '연기',
  '괜찮',
  '전성시대',
  '열리',
  '영화',
  '이때',
  '한석규',
  '뿅',
  '가'],
 ['일단', '재생', '괴물', '같', '서스펜스', '귀신', '같', '흡입', '력'],
 ['진짜',
  '댓글',
  '한번쯤',
  '볼',
  '영화인',
  '같',
  '죽기',
  '직전',
  '소원',
  '들어주',
  '보',
  '죽기',
  '직전',
  '막',
  '살',
  '인',
  '같',
  '감동',
  '없',
  '진짜',
  '란',
  '영화',
  '발톱',
  '때',
  '못',
  '따라가',
  '쓰레기',
  '영화',
  '와',
  '존',
  '실망'],
 ['시간',
  '좀',
  '밝',
  '긍정',
  '드라마',
  '보',
  '보기',
  '보',
  '오버',
  '연기',
  '거슬리',
  '연기',
  '인',
  '게',
  '너무',
  '표',
  '요',
  '홍혜정',
  '역',
  '이그',
  '마도',
  '기도',
  '고시원',
  '나머지',
  '들',
  '내',
  '월요일',
  '해피',
  '한',
  '보'],
 ['정치인', '모순', '인가', '정치범', '모순'],
 ['어떻', '상상'],
 ['좀', '어렵', '하', '전쟁', '대하', '묘사', '잘', '모르'],
 ['일본', '극장판', '만들', '우리나라', '에선', '개봉', '하니', '이건', '좀'],
 ['개그콘서트', '보', '전화', '끊', '개그', '콘서트', '없애'],
 ['한물', '동서양', '배우', '싸움판'],
 ['푸', '하', '하', '하', '기대', '안'],
 ['세계', '최초', '반공', '애니매이션', '역사', '가치'],
 ['감각', '시각', '바라보', '색다르', '느낌', '사랑', '문학'],
 ['엄마', '무고', '딸', '감옥살이', '시키', '시키', '이해', '안'],
 ['이영화', '제발', '책', '을', '보세', '감독', '미치', '이', '만들', '화', '날', '정도'],
 ['신나', '흑인', '음악', '아이스 큐브', '남', '없'],
 ['드럽', '재미없', '시간', '돈', '시간', '어쩌'],
 ['그저', '한마디', '알리', '시아'],
 ['진짜', '느끼'],
 ['재밌', '평점', '정도', '낮'],
 ['옥소리', '프로필', '사진', '남기', '가', '대박', '이다', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 [],
 ['연기', '굿'],
 ['영화', '다시', '안', '나오', '그때', '시절', '잘', '나타내', '같'],
 ['중간', '정도', '보', '꽤'],
 ['콩', '까', '제맛', '콩', '까', '제맛'],
 ['소설', '재미없'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['가', '알', '없', '매력', '빠지', '영화'],
 ['모녀',
  '토막',
  '살해',
  '살인자',
  '성애',
  '말이',
  '감동',
  '받',
  '사람',
  '본인',
  '피해자',
  '감동',
  '받',
  '하',
  '진심',
  '묻'],
 ['재밌', '평점', '왜', '이렇', '구리지'],
 ['OOO', '보', '눈', '아깝', '진짜', '놓', '진짜', 'OOO', '기', '명작'],
 ['필름', '값', '아깝', '재미', '더럽', '없', '점', '수준', '매미', 'OO'],
 [],
 ['영화', '재미있'],
 ['남주인공',
  '연기력',
  '안',
  '습',
  '혀',
  '짧',
  '소리',
  '듣',
  '너무',
  '힘들',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '좋',
  '생각',
  '들',
  '정도',
  '영화',
  '자체',
  '적당히',
  '보',
  '하'],
 ['딱', '액션', '스릴러', '액션', '스릴', '없'],
 ['완전', '스토리', '엉망', '이구', '완전'],
 ['OOO', '영화', '전달', '모르', '오', '글', '거리'],
 ['좋', '영화'],
 ['더빙', '할머니', '월래'],
 ['이', '나오'],
 ['게', '다', '부족'],
 ['정말', '말', '그대로', '쇼', '영화'],
 ['전', '보', '기억', '진개', '천카이거', '감독', '이름', '기억', '두'],
 ['정은지',
  '언니',
  '!!',
  '연기',
  '잘',
  '노래',
  '잘',
  '부르',
  '마지막',
  '웃',
  '즐겁',
  '보',
  '트로트의 연인'],
 ['이'],
 ['망하'],
 ['아이', '시선', '보', '전쟁', '보', '내내', '가슴'],
 ['사람',
  '재미없',
  '하',
  '레알',
  '기대',
  '안',
  '생각',
  '보',
  '여자',
  '애',
  '복순이',
  '다투',
  '장면',
  '굳이',
  '없',
  '되',
  '생각',
  '몰입',
  '겁나',
  '없애',
  '보이'],
 ['설정', '연속극', '같', '느낌', '들', '배우', '연기', '뛰어나'],
 ['여주인공', '인터뷰', '때', '죽', '알', '그냥저냥', '킬링타임', '스릴러'],
 ['미',
  '박스',
  '오피스',
  '그냥',
  '몰아주',
  '하',
  '어떻',
  '영화',
  '하',
  '옛날',
  '90년대',
  '우뢰',
  '매',
  '수준',
  '물',
  '폭탄',
  '싸움',
  '손',
  '빔',
  '가나',
  '손',
  '물',
  '폭탄',
  '나가',
  '다르'],
 ['감독', '여자', '다', '보니', '기량', '많이', '딸리'],
 ['보'],
 ['영화', '개연', '없', '허무', '만들', '조디', '포스터', '이쁘', '모습', '남', '영화'],
 ['굳', '굳'],
 ['스토리',
  '말',
  '안',
  '개막',
  '장',
  '사랑이야',
  '기도',
  '아니',
  '예',
  '보',
  '시간',
  '돈',
  '아끼',
  '예',
  '요',
  '휴',
  '보',
  '호구'],
 ['살리', '쌀', '아깝', '세기', '대사'],
 ['평점',
  '너무',
  '높',
  '전혀',
  '재미있',
  '쓸데없이',
  '말',
  '많',
  '류',
  '영화',
  '조연',
  '뒷받침',
  '조연',
  '내용',
  '자체',
  '전혀',
  '없',
  '여배우',
  '별로',
  '매력',
  '없',
  '이틀',
  '전',
  '저스트',
  '고위',
  '드',
  '잇',
  '애니',
  '스톤',
  '보',
  '영화',
  '보',
  '그렇',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '인가', '가', '훈련', '때', '나오', 'ost', '작살'],
 ['이건',
  '시종일관',
  '질',
  '질',
  '왜',
  '제목',
  '야경꾼 일지',
  '냐',
  '지금',
  '넘어가',
  '달',
  '넘어가',
  '앞',
  '누',
  '군가',
  '얘기',
  '하',
  '더',
  '그렇',
  '순간',
  '훅',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '들', '이해', '가', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '없',
  '아역',
  '연기',
  '추노',
  '나오',
  '민폐',
  '언',
  '외국',
  '판',
  '인줄',
  '초반',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '예', '결말'],
 ['딱히', '재미', '없'],
 ['송강호', '정말', '연기', '하', '위하', '태어나', '인하', '즐거움', '느끼', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리', '불후의 명작', '그립'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌',
  '살인',
  '대하',
  '감독',
  '해석',
  '정말',
  '재치',
  '있',
  '배우',
  '여',
  '전',
  '모습',
  '정말',
  '재밌'],
 ['누', '미', '라파스', '신봉선', '닮', '안', '보'],
 ['케이블', '그만', '좀', '재탕'],
 ['멋지', '정말', '멋지', '말', '이외', '하', '말', '없'],
 ['어떻', '영화', '만들', '의문', '당대', '최고', '영화', '지금', '보', '결코', '떨어지'],
 ['지금', '티', '비', '돈', '내', '보'],
 ['쓰레기', '연예인', '재기', '장', '그렇'],
 ['굿', '좋'],
 ['많', '감동', '드라마'],
 ['발로',
  '만들',
  '영화',
  '지진',
  '나서',
  '주인공',
  '넘어지',
  '뒤',
  '사람',
  '유유히',
  '걷',
  '다니',
  '있',
  '발',
  'CG',
  '발',
  '연기',
  '발',
  '시나리오',
  '내용',
  '정말',
  '같'],
 ['적당히', '하', '언제', '끝나'],
 ['잊', '없', '안개', '끼', '워터', '다리', '마스코트'],
 ['곤',
  '사토시',
  '감독',
  '안타깝',
  '돌아가',
  '가슴',
  '정말',
  '천재',
  '감독',
  '암',
  '가',
  '이제',
  '와서',
  '다시',
  '보',
  '작품',
  '대작'],
 ['많', '생각', '하', '되', '예', '뼈', '지', '맘', '과', '독'],
 ['없', '줄'],
 ['어리',
  '때',
  '영화로',
  '알',
  '나이',
  '들',
  '이',
  '인생',
  '하',
  '영화',
  '세상',
  '살아가',
  '갈수록',
  '오',
  '닿',
  '많',
  '세상',
  '비정',
  '비정',
  '함마',
  '지',
  '친구'],
 ['영상', '너무나', '멋지'],
 ['비디오', '있', '보', '1997년', '도인', '줄', '모르', '정도', '잘', '만들', '긴장감', '있'],
 [],
 ['만들',
  '재밌',
  '영화',
  '길',
  '좀',
  '다듬',
  '소재',
  '좋',
  '몰입',
  '감',
  '기대',
  '이상',
  '매끄럽',
  '부분',
  '있',
  '연기',
  '다',
  '잘'],
 ['철',
  '지나',
  '코미디',
  '뼈대',
  '있',
  '가문',
  '이야기',
  '섞',
  '다',
  '박정아',
  '배우',
  '보',
  '연기',
  '펼치',
  '기억',
  '남',
  '없'],
 ['군더더기', '없이', '잘', '진행', '재미', '없', '문제'],
 ['재밌', '탑', '연기', '알', '배우', '포스', '잘'],
 ['다', '미', '괜찮'],
 ['지대', '짜증', '아빠', '보', '앗', '죽'],
 ['못', '주'],
 ['빠', '순이', '영화'],
 ['최악', '애니메이션', '재미없', '스토리'],
 ['좋', '의도', '다르', '표현법'],
 ['줄리아', '로버츠', '귀엽', '연인', '5년', '전'],
 [],
 ['예술가', '사람', '인생', '당시', '시대', '상황', '느끼', '명작'],
 ['관객',
  '너무',
  '아쉽',
  '영화',
  '베테랑',
  '더',
  '류승완',
  '감독',
  '역작',
  '더',
  '강하',
  '악역',
  '이다'],
 ['한창', '핵', '펭귄', '남북', '거짓', '평화로', '전', '국민', '속', '때', '만들', '영화'],
 ['지금', '티', '비', '못', '보'],
 ['여자', '애'],
 ['성룡', '단연', '최', '고지'],
 ['안', '습'],
 ['감독', '의도', '전혀', '알아차리'],
 ['하나님',
  '이',
  '가정',
  '을',
  '온전히',
  '만들',
  '진리',
  '이신',
  '분이',
  '만들',
  '영화',
  '눈',
  '보',
  '마음',
  '보'],
 ['피', '헤드', '죽', '좀', '아쉽'],
 ['국산', '코미디', '영화', '나', '신라', '달밤', '제일', '좋', '뭐'],
 ['최악', '영화', '잠', '오기', '첨', '지루', '해', '둑', '을'],
 ['배우', '되', '건지'],
 ['영화', '점점', '끝', '달려가', '몰입', '도가', '더', '높', '영화', '이번', '처음'],
 ['결국',
  '감독',
  '자신',
  '하',
  '의견',
  '지존파',
  '핑계',
  '삼',
  '하',
  '지존파',
  '살인',
  '정당화',
  '정부',
  '탓',
  '사회',
  '탓'],
 ['사실',
  '여부',
  '떠나',
  '알',
  '아더',
  '너무',
  '안',
  '덜',
  '원탁',
  '기사',
  '실제',
  '검술',
  '최고',
  '랜스',
  '롯',
  '알',
  '있',
  '트리스탄',
  '싸우',
  '검술',
  '마치',
  '중국',
  '검술',
  '흉내',
  '내',
  '같',
  '란슬롯',
  '실제',
  '쌍',
  '검',
  '너무',
  '안대',
  '하트',
  '미스'],
 ['대한민국', '영화', '수준', '평균', '하락', 'C', '급', '영상물'],

In [75]:
w2v = Word2Vec(
    sentences=X_tokens,
    window=3,
    min_count=3,
    sg = 1,
    epochs=5,
    seed=42
)

In [76]:
wv = w2v.wv

In [77]:
def sent_embed_mean(tokens):
    vecs = []
    for word in tokens:
        if word in wv.index_to_key:
            vecs.append(wv[word])
    result =  np.mean(vecs, axis=0) if vecs else np.zeros(wv.vector_size)
    return result

In [78]:
X_embed = [sent_embed_mean(token) for token in X_tokens]

In [79]:
svc = SVC(random_state=42)
logistic = LogisticRegression(random_state=42)

In [83]:
def run_model(X, Y, test_size=0.2, model='svc'):
    # X는 독립변수
    # Y는 종속변수
    X_train, X_test, Y_train, Y_test = train_test_split(
        X, Y, test_size=test_size, random_state=42, stratify=Y
    )
    svc = SVC(random_state=42)
    logi = LogisticRegression(random_state=42)
    # 모델에 학습
    if model == 'svc':
        svc.fit(X_train, Y_train)
        # 학습된 모델에 예측 값
        y_pred = svc.predict(X_test)
        print("정확도 :", round(accuracy_score(Y_test, y_pred), 4))
        print("분류 레포트 :", classification_report(Y_test, y_pred))
    elif model == 'logistic':
        logi.fit(X_train, Y_train)
        # 학습된 모델에 예측 값
        y_pred = logi.predict(X_test)
        print("정확도 :", round(accuracy_score(Y_test, y_pred), 4))
        print("분류 레포트 :", classification_report(Y_test, y_pred))

In [84]:
run_model(X_embed, Y)

정확도 : 0.6
분류 레포트 :               precision    recall  f1-score   support

           0       0.58      0.58      0.58        48
           1       0.62      0.62      0.62        52

    accuracy                           0.60       100
   macro avg       0.60      0.60      0.60       100
weighted avg       0.60      0.60      0.60       100

In [85]:
run_model(X_embed, Y, model='logistic')

정확도 : 0.52
분류 레포트 :               precision    recall  f1-score   support

           0       0.00      0.00      0.00        48
           1       0.52      1.00      0.68        52

    accuracy                           0.52       100
   macro avg       0.26      0.50      0.34       100
weighted avg       0.27      0.52      0.36       100

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [ ]:
def predict_sentence_list(sentences, model):
    # sentences : 문장들의 리스트
    # 문장들을 토큰화 -> 임베딩
    X_test = []
    for sent in sentences:
        # token() 함수를 호출하여 토큰화
        tokens = tokenize(sent)
        # 토큰화된 문장을 sent_embed_mean 함수에 입력하여 호출(단위 벡터의 평균)
        vec = sent_embed_mean(tokens)
        X_test.append(vec)
    
    preds = model.predict(X_test)
    result = []
    for sent, pred in zip(sentences, preds):
        label = '긍정' if pred == 1 else '부정'
        result.append([sent, label])
    return result

In [86]:
def sent_embed_tfidf(tokens):
    vecs = []
    weight = []
    for word in tokens:
        # tokens의 각각의 단어가 Word2Vec과 TF-IDF에 존재한다면
        if word in wv.key_to_index and word in idf:
            # vecs -> 단위벡터와 중요도를 곱한 값을 vecs 추가
            vecs.append(wv[word] * idf[word])
            # weight -> 중요도 데이터를 추가
            weight.append(idf[word])
    # vecs에 데이터가 존재하지 않는다면 -> tokens 안에 단어는 존재하지만 Word2Vec이나 TF-IDF에 단어가 존재하지 않을때
    if not vecs:
        # 희소행렬 되돌려준다. 0행렬
        result = np.zeros(wv.vector_size)
    else:
        result = np.sum(vecs, axis=0) / (np.sum(weight) + 1e-9)
        return result

In [87]:
X_embed2 = [sent_embed_tfidf(token) for token in X_tokens]

NameError: name 'idf' is not defined

In [ ]:
8. train, test을 이용하여 2개의 모델 중 성능이 높은 모델이 무엇인가?
9. 단위 벡터의 평균의 성능과 단위 벡터 + 중요도 평균의 성능의 차이를 확인