#### 감정 분석 자연어 처리
1. data 폴더 안에 ratings_train.txt 파일을 로드
2. 데이터를 상위 500개 데이터만 추출
3. 리뷰 데이터와 감정 데이터로 나눠준다.
4. 리뷰 데이터를 토큰화(komoran함수 이용) -> 벡터화(Word2Vec, 단위 벡터의 평균)
5. Word2Vec 학습
    - window -> 3
    - epochs -> 10
    - min_count -> 5
    - sg -> 1
    - seed -> 42
6. 벡터화(Word2Vec, 단위 벡터의 평균)
7. 분류 모델(SVC, Logistic)
8. train, test을 이용하여 2개의 모델 중 성능이 높은 모델이 무엇인가?
9. 단위 벡터의 평균의 성능과 단위 벡터 + 중요도 평균의 성능의 차이를 확인

In [1]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('../data/ratings_train.txt', sep='\t')
df.head()

         id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  object
 2   label     150000 non-null  int64
dtypes: int64(2), object(1)
memory usage: 3.4+ MB

In [4]:
# 상위 데이터 500개
# df2 = df.head(500)
df2 = df.loc[:499, ]
df2

           id                                           document  label
0     9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1     3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2    10265843                                  너무재밓었다그래서보는것을추천한다      0
3     9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4     6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
..        ...                                                ...    ...
495  10049872  그냥 기독교영화네요. 좀 더 깊이있는 내용을 기대했는데.. 실망입니다. 영화도 뭔가...      0
496   9427493  그냥 책으로 읽는게 더 절절하게 다가온다. 영화는 내용을 너무 비약하고 삭제해서 행...      0
497   6629097                                        너무나 감동적인 영화      1
498   9995177                              스킨헤드성님들이 이 영화를 싫어합니다.      0
499   9600841                    자동차 매니아인 나의 평점은 5점 이하~속았다...아오~      0

[500 rows x 3 columns]

In [5]:
df2['label'].value_counts()

label
1    258
0    242
Name: count, dtype: int64

In [6]:
def bulid_tokenize():
    try:
        # 라이브러리 로드 -> 라이브러리가 존재하면 코드를 실행
        from konlpy.tag import Komoran
        komoran = Komoran()
        allow_pos = ['NNP' ,'NNG', 'VV', 'VA', 'SL', 'MAG']
        def tokenize(text):
            tokens = []
            for word, pos in komoran.pos(text):
                if pos in allow_pos:
                    tokens.append(word)
            return tokens
        # tokenize 함수를 결과로 되돌려준다.
        return tokenize
    except Exception as e:
        print("Komoran 사용 불가 :", e)
        return lambda x : x.split()

In [7]:
tokenize = bulid_tokenize()

In [8]:
reviews = df2['document'].values
Y = df2['label'].values

In [9]:
X_tokens = [tokenize(review) for review in reviews]

In [10]:
w2v = Word2Vec(
    sentences=X_tokens,
    window=5,
    min_count=2,
    sg = 1,
    epochs=100,
    seed=42
)

In [11]:
wv = w2v.wv

In [12]:
def sent_embed_mean(tokens):
    vecs = []
    for word in tokens:
        if word in wv.index_to_key:
            vecs.append(wv[word])
    result =  np.mean(vecs, axis=0) if vecs else np.zeros(wv.vector_size)
    return result

In [13]:
tfidf_vec = TfidfVectorizer(
    tokenizer=tokenize,
    lowercase=False
).fit(reviews)

idf = dict(
    zip(
        # get_feature_names_out() -> Tfidf에서 사용된 단어들의 목록
        tfidf_vec.get_feature_names_out(),
        # idf_ -> 중요도
        tfidf_vec.idf_
    )
)

# 단어 별 단위 벡터의 평균과 idf을 곱한다. 
def sent_embed_tfidf(tokens):
    vecs = []
    weight = []
    for word in tokens:
        # tokens에 각각의 단어가 Word2Vec과 TF-IDF에 존재한다면
        if word in wv.key_to_index and word in idf:
            # vecs -> 단위벡터와 중요도를 곱한 값을 vecs 추가
            vecs.append(wv[word] * idf[word])
            # weight -> 중요도 데이터를 추가 
            weight.append(idf[word])
    # vecs의 데이터가 존재하지 않는다면 -> tokens 안에 단어는 존재하지만 Word2Vec이나
    # TD-IDF에 단어가 존재하지 않을때
    if not vecs:
        # 희소 행렬 되돌려준다. 0행렬
        result = np.zeros(wv.vector_size)
    else:
        result = np.sum(vecs, axis=0) / ( np.sum(weight) + 1e-9 )
    return result

c:\Users\student\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\feature_extraction\text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [14]:
X_embed = [sent_embed_mean(token) for token in X_tokens]
X_embed

[array([ 5.33957541e-01,  7.00074423e-04, -3.38822186e-01,  5.87574253e-03,
         2.37580147e-02,  5.98014832e-01,  1.17120527e-01,  1.48372784e-01,
        -3.04113656e-01, -8.77798945e-02, -5.33828497e-01,  1.42356157e-01,
         1.34550840e-01,  3.23668033e-01, -2.32036397e-01,  2.44896889e-01,
         4.58733812e-02, -2.46577501e-01,  7.21570104e-02, -6.67451173e-02,
        -6.07907474e-02,  1.77631378e-01,  9.34182256e-02,  2.20190808e-01,
         4.89958584e-01,  8.94318894e-02,  6.21634051e-02,  9.69333500e-02,
         2.22539753e-01, -1.55158252e-01, -2.60440171e-01,  4.50167321e-02,
         2.24932097e-02,  3.69715592e-04, -1.07274912e-01, -3.40299234e-02,
         2.51285970e-01, -2.95914114e-01,  1.00796878e-01, -7.39332512e-02,
         2.45106518e-02, -3.59761491e-02,  4.87316065e-02,  1.47817567e-01,
         1.73935026e-01,  3.09559405e-02,  1.07413985e-01,  5.93005009e-02,
         3.50145280e-01, -2.59373002e-02, -3.90245058e-02, -7.06655800e-01,
         1.45083785e-01,  2.70396352e-01,  1.05334911e-02, -2.55715668e-01,
        -4.12938669e-02, -2.74634719e-01, -7.04872012e-02,  2.96691716e-01,
        -3.00758392e-01,  1.68464243e-01, -4.00057256e-01,  2.73742191e-02,
         5.51737547e-02,  1.44153416e-01,  7.29669780e-02, -1.43037051e-01,
        -3.52031559e-01, -1.50991142e-01,  9.05287713e-02, -6.01654425e-02,
        -2.16593109e-02, -2.50193179e-01,  1.26799252e-02,  2.94089913e-01,
        -2.08211333e-01,  2.53155470e-01,  4.35927480e-01,  2.34580748e-02,
         4.14264500e-01, -1.42478913e-01, -3.53213012e-01, -1.37547761e-01,
        -1.13975443e-01,  1.06995143e-01, -6.35352880e-02,  3.16830492e-03,
        -1.78535834e-01, -1.93830997e-01, -2.63753921e-01,  4.07716513e-01,
         9.66119096e-02, -3.65583122e-01,  3.78842324e-01,  4.23677973e-02,
         2.83248007e-01,  4.16299840e-03, -2.62972027e-01,  6.25825003e-02],
       dtype=float32),
 array([ 0.24403489, -0.00551349,  0.14056866,  0.11107451,  0.06946564,
         0.23514687, -0.04105156,  0.22100693, -0.01984776,  0.06399054,
        -0.35127175,  0.09079797,  0.1973296 ,  0.22726727, -0.07383914,
        -0.0043021 ,  0.03994511, -0.20887285, -0.12474319, -0.11306519,
        -0.03703414, -0.01206862,  0.03307772,  0.15942426,  0.19745284,
         0.15057425, -0.18369621, -0.05656339, -0.30343273, -0.09206787,
         0.06740134, -0.16649422,  0.24675648,  0.02420018, -0.00513342,
        -0.06374487,  0.10959166, -0.300314  , -0.13967961,  0.15896063,
        -0.11435769,  0.13793741,  0.18574105, -0.2302048 , -0.01934459,
         0.00828421,  0.06417091,  0.05638666,  0.21966283, -0.0497317 ,
         0.01628597, -0.38181338,  0.19026123, -0.03647052,  0.21052514,
        -0.13535751, -0.04692806, -0.02057024,  0.00449305,  0.35825884,
        -0.1051913 , -0.0178822 , -0.23912424, -0.06704595,  0.04423954,
         0.08450808,  0.14608176, -0.16265456, -0.32457337, -0.10445163,
         0.0478307 , -0.00090413,  0.12272196, -0.18665428,  0.3147839 ,
         0.12031931, -0.13357542, -0.10302725, -0.11630527, -0.08925302,
         0.12357386,  0.01353563, -0.12506245,  0.06215099,  0.00060337,
         0.05928199, -0.12630107, -0.16037995,  0.01405467,  0.04954707,
        -0.2687342 ,  0.44223914,  0.13215095, -0.07690791,  0.10093409,
        -0.28126153,  0.13835663,  0.18570425, -0.22893661, -0.06171106],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 0.15991373, -0.00147503, -0.13282605, -0.02669647, -0.00263344,
         0.22585717, -0.03687819,  0.46835893, -0.36831254, -0.37248623,
        -0.56901413,  0.2085989 , -0.14667393,  0.2753226 ,  0.19208246,
        -0.12637012, -0.00367468,  0.0499599 , -0.32025003,  0.14415476,
         0.21800132,  0.2532784 , -0.07862413,  0.38229966,  0.25581092,
         0.0806136 ,  0.496457  ,  0.44118857, -0.23798387, -0.18002616,
        -0.3523427 , -0.09496932,  0.22756818,  0.04898049,  0.11593952,
        -0.15096748,  0.30272478, -0.39791662, -0.08700268,  0.2850389 ,
         0.23612957,  0.3249338 ,  0.15147556, -0.03230273,  0.12735152,
         0.1276218 ,  0.15101282,  0.28209102,  0.27114993, -0.4618988 ,
        -0.28954262, -0.46613264, -0.0234886 , -0.05732887, -0.13492216,
         0.06121019, -0.12525645,  0.18666951,  0.06876383,  0.29901138,
        -0.1561873 , -0.033636  , -0.25761867,  0.02022713, -0.21154413,
        -0.10568805, -0.00250563, -0.4877839 , -0.42373055, -0.17863825,
        -0.10798158,  0.02914364,  0.0532221 , -0.21412387,  0.5126025 ,
         0.0893468 ,  0.02237361, -0.08500682, -0.03920099, -0.09365423,
        -0.15783814, -0.21163997, -0.41104937, -0.03275184, -0.14683564,
         0.00767667, -0.3240443 ,  0.20611635, -0.10718407, -0.04521745,
        -0.52497375,  0.6836271 ,  0.13737598, -0.35070318,  0.20687242,
        -0.07336791,  0.29188347, -0.11282539, -0.24524269, -0.10066031],
       dtype=float32),
 array([ 0.14433332,  0.09089863,  0.25990266,  0.20419328, -0.01796955,
         0.20702519, -0.0918274 ,  0.1630784 , -0.1517657 , -0.04140818,
        -0.30966023,  0.10144813,  0.08204349, -0.17081782,  0.07694447,
        -0.01670544,  0.00887698, -0.36827272, -0.0202623 , -0.16333732,
        -0.11813671, -0.06629483,  0.04310474,  0.02256186,  0.12193792,
        -0.11537493, -0.26129264, -0.12952997, -0.4413678 , -0.01514417,
         0.07689732, -0.25953507,  0.15056217,  0.25487024, -0.0312093 ,
         0.12388585, -0.05311454, -0.2860188 ,  0.12953982,  0.13376102,
        -0.21657166, -0.00951557,  0.1288444 , -0.09509908, -0.0027546 ,
        -0.05515899, -0.0909944 ,  0.25260323,  0.21760185, -0.25502688,
        -0.11267173, -0.3578791 ,  0.12214319, -0.0856114 ,  0.56267875,
         0.01691557, -0.06106677,  0.11459084, -0.13381648,  0.31094006,
         0.11333419, -0.06608246, -0.3109133 ,  0.04481997,  0.17980357,
         0.24775015,  0.13009188, -0.17604093, -0.22347936, -0.11417631,
         0.05400905, -0.03510127, -0.23960309, -0.02801215, -0.0841381 ,
        -0.06165356, -0.0800434 , -0.28673974, -0.285774  , -0.18735456,
         0.05196483, -0.00545641, -0.01253169,  0.16274627, -0.1595075 ,
        -0.1588663 , -0.07959238, -0.6031818 , -0.10135972, -0.07674308,
        -0.2407513 ,  0.19151281, -0.15408278, -0.17023532,  0.08456328,
        -0.22584565,  0.06051847,  0.05762263, -0.17164704, -0.00888862],
       dtype=float32),
 array([ 0.13462524, -0.05290052, -0.05108079,  0.09748118,  0.27922988,
         0.4223837 ,  0.25564036,  0.02520918, -0.15574877,  0.2292284 ,
        -0.59393024,  0.46267408, -0.17337592,  0.38201848, -0.1954313 ,
        -0.29150066,  0.19561562, -0.24130897, -0.26446825,  0.11530377,
         0.20797198,  0.08639513,  0.16109166,  0.06976496,  0.17984883,
         0.07892761, -0.1420123 , -0.21436456, -0.07970253, -0.27101302,
        -0.22429474,  0.13775581,  0.16385798,  0.23265457, -0.09622306,
        -0.1263417 ,  0.33352488, -0.29466885, -0.05914363,  0.26738638,
         0.22855787,  0.32919985,  0.25367415, -0.3702796 ,  0.27615693,
        -0.16499431,  0.1972021 ,  0.03696071,  0.47540492, -0.2683433 ,
        -0.02398349, -0.58583397,  0.38734975, -0.14341542,  0.24212892,
        -0.24147098,  0.02506022,  0.05255442, -0.20444903,  0.6208154 ,
        -0.01330036,  0.15475692, -0.56170905, -0.3188765 ,  0.07067211,
         0.26949906, -0.14188437, -0.15984276, -0.39649585,  0.09700675,
         0.42542678,  0.00275677, -0.03030146, -0.48907408,  0.27165478,
         0.13405144,  0.02494219,  0.11181004,  0.3757723 ,  0.00533664,
        -0.16148192, -0.2928629 , -0.20623645,  0.4226902 ,  0.12339371,
         0.04795139,  0.01493298,  0.08945584, -0.02745068,  0.33964446,
        -0.27721697,  0.3657669 ,  0.45742792, -0.3058849 ,  0.07722005,
        -0.28767443,  0.0393439 , -0.2114176 , -0.8232414 , -0.02642621],
       dtype=float32),
 array([ 0.09306749,  0.13142747,  0.09462567, -0.02672419,  0.02534497,
         0.03525072,  0.17518336,  0.19547184,  0.1020843 , -0.08540038,
        -0.39713445,  0.15259378, -0.08343917,  0.00221427,  0.19492276,
        -0.02976744,  0.0685735 , -0.11169702, -0.11509154,  0.01467235,
         0.14944051, -0.00093391,  0.210586  ,  0.06818559,  0.29277146,
         0.13609682, -0.21975946,  0.03547746, -0.24829328, -0.2597858 ,
        -0.07652184, -0.20495425,  0.24807672,  0.06889915,  0.14760411,
        -0.06043825,  0.00293762, -0.44314885, -0.01684685,  0.10719671,
         0.13395214,  0.11929146,  0.23128814, -0.1898932 ,  0.06123836,
        -0.1016233 , -0.03231587,  0.04785049,  0.23422499, -0.00874009,
        -0.06023416, -0.34005055,  0.01858652, -0.25104246,  0.10564192,
         0.07090249, -0.04862202,  0.2552435 , -0.12093642,  0.2806873 ,
        -0.1978379 ,  0.10916933, -0.37201324, -0.21622777,  0.09565189,
         0.12941514,  0.1481484 , -0.16308136, -0.22108437,  0.22829546,
         0.06951991, -0.12663727, -0.13313103, -0.09348419,  0.17788589,
         0.04164979,  0.01329967, -0.2503848 , -0.15752403, -0.37180114,
        -0.15609168, -0.06977557, -0.15060619,  0.29116675, -0.23607768,
         0.02202044,  0.01580256, -0.14900662, -0.04682637,  0.11935731,
        -0.13911833,  0.347322  , -0.16625254, -0.18144381,  0.04260867,
        -0.34638456,  0.04052991,  0.03091978, -0.12379346, -0.23941402],
       dtype=float32),
 array([-3.21084112e-02, -8.92861038e-02, -9.01013613e-04,  9.21983086e-03,
        -1.48674831e-01,  3.76044452e-01, -1.64641678e-01,  2.75960982e-01,
        -3.36255103e-01,  1.31738678e-01, -4.33761895e-01,  1.13435112e-01,
         3.06246608e-01,  1.31026715e-01, -1.75312772e-01,  5.12780771e-02,
         7.92955309e-02, -2.41918400e-01,  3.59162106e-03, -9.37907621e-02,
         1.70866668e-01, -6.86443523e-02, -7.21396357e-02,  3.60335745e-02,
         6.87599853e-02,  2.69677997e-01, -1.66140378e-01, -1.32275909e-01,
        -1.43520385e-01, -1.21332772e-01,  2.62978643e-01, -3.48043501e-01,
         2.03728154e-01,  4.07391377e-02, -1.55636892e-01, -3.77621455e-03,
         6.68518990e-02, -6.90601408e-01, -8.54498595e-02,  2.79804438e-01,
        -8.93534049e-02,  1.17026992e-01,  4.06011231e-02, -2.26816073e-01,
        -5.11337668e-02, -8.71790480e-03, -1.35154530e-01,  2.93332785e-01,
         2.06826910e-01, -4.78581414e-02,  9.32453666e-03, -2.60110289e-01,
         1.95356205e-01, -6.43738266e-03,  1.78596959e-01, -5.97380027e-02,
         9.66490060e-02,  2.33043298e-01, -4.00481343e-01,  3.59236091e-01,
        -3.86896133e-01,  5.24903536e-02, -3.44735503e-01, -2.83034462e-02,
         8.21683556e-02, -9.99047458e-02,  1.49805069e-01, -1.53376281e-01,
        -3.40337187e-01, -7.71314576e-02, -1.11647449e-01, -2.70481259e-01,
         9.91379027e-04, -2.42239326e-01,  1.60337999e-01, -1.11303717e-01,
        -2.43169397e-01, -8.41207802e-03, -5.17191142e-02, -1.71854103e-04,
         2.33239651e-01,  2.58068174e-01, -2.33686760e-01,  3.94465148e-01,
        -6.40397221e-02, -1.17828255e-03, -1.63716227e-01, -1.76876351e-01,
        -1.20543718e-01,  2.36863703e-01, -2.47830361e-01,  3.46807748e-01,
         1.07648812e-01, -1.77005216e-01,  1.70622785e-02, -3.24167997e-01,
         2.40476936e-01,  1.23253204e-01, -4.00822520e-01,  1.24764092e-01],
       dtype=float32),
 array([ 0.30228293,  0.15675391, -0.09238295,  0.06456066, -0.06673205,
         0.29560152,  0.05979647,  0.38891533, -0.3401552 , -0.25684944,
        -0.42289007,  0.22088115, -0.06567322,  0.2512086 , -0.05464901,
         0.03030769, -0.07486304, -0.17912443, -0.02175357,  0.36169836,
         0.11263148,  0.23061366,  0.05337156,  0.104889  ,  0.23221357,
        -0.03706941,  0.25711608,  0.16670187, -0.26366028, -0.05704563,
        -0.16057874, -0.0886415 ,  0.20751627, -0.05997469, -0.0867989 ,
        -0.11033061,  0.3795441 , -0.27300084, -0.15456666,  0.16858865,
         0.09068117,  0.15978864,  0.10785347, -0.00538753, -0.02912187,
         0.03836032,  0.16037007,  0.17352192,  0.05294244, -0.24661903,
        -0.16476168, -0.44160977, -0.23096204, -0.12972422,  0.09122362,
        -0.0733543 ,  0.06118145,  0.08763441, -0.09998707,  0.45310152,
        -0.13199604,  0.01788405, -0.38710943,  0.04595739, -0.06931981,
        -0.01823636,  0.13954954, -0.26977775, -0.45451084, -0.06939364,
         0.03345742,  0.08368545, -0.16847801, -0.06425819,  0.21809293,
         0.07396934, -0.10687953, -0.00945515, -0.2124434 , -0.15008126,
        -0.09316167, -0.2401209 , -0.32178637, -0.10829424, -0.22848688,
         0.17578669, -0.19009976, -0.02779194, -0.13333216,  0.01592107,
        -0.44083515,  0.18433718,  0.10549019, -0.32029483,  0.18681854,
         0.01370152,  0.10046788, -0.05239659, -0.14846002, -0.14400823],
       dtype=float32),
 array([ 0.18465313,  0.06425769, -0.24126543, -0.1808431 ,  0.05243564,
         0.11825508, -0.17842415,  0.34844944, -0.26702866,  0.0156565 ,
        -0.44883427,  0.49758288,  0.10988434,  0.24496563,  0.13953708,
        -0.10684865, -0.02405609, -0.04158588, -0.38157567,  0.02334862,
         0.36079127,  0.09731046, -0.02973333,  0.3289075 ,  0.16572817,
         0.25135675,  0.06054536,  0.11711552,  0.03487604,  0.04475844,
        -0.05879052, -0.10191132,  0.07445378,  0.2310419 ,  0.02906081,
         0.08950862,  0.09396338, -0.37679696, -0.04642751,  0.33748338,
         0.34039596,  0.07548706,  0.31951922, -0.2500908 ,  0.12412811,
        -0.09371328, -0.01584627,  0.2935898 ,  0.30887118, -0.4354808 ,
        -0.1189824 , -0.6575119 ,  0.07919554, -0.08436511,  0.0094307 ,
         0.01526245,  0.11838937,  0.1891788 ,  0.01505467,  0.19132757,
         0.09652261,  0.01366037, -0.10254581, -0.0195962 ,  0.12964226,
         0.22329612,  0.13264267, -0.37908623, -0.23305681,  0.02978174,
        -0.06276853, -0.0708793 ,  0.08027636, -0.19341515,  0.24125542,
         0.04148701,  0.2169467 ,  0.01693311,  0.03840015, -0.02161423,
         0.09594624, -0.32890564, -0.16428198,  0.10617604, -0.24143259,
        -0.03382181, -0.12511031,  0.03100504,  0.07061017, -0.04284447,
        -0.38925657,  0.2548869 , -0.1362468 , -0.1639384 ,  0.15372656,
        -0.16708174,  0.18996134,  0.11436283, -0.23684993, -0.0130208 ],
       dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 0.15526767, -0.42097974, -0.01618268,  0.35595736, -0.13424902,
         0.4726379 ,  0.21247941,  0.16235451, -0.4404513 ,  0.21564816,
        -0.4702742 ,  0.06872397,  0.12567116,  0.08082186, -0.48115647,
        -0.18233877,  0.46242097, -0.6324609 , -0.06961709, -0.25942266,
         0.22717679,  0.05028382,  0.03260976,  0.04084958, -0.06206978,
        -0.16598105, -0.31138268,  0.06257592,  0.12233748, -0.06654728,
        -0.04858819, -0.18690388,  0.21408439, -0.14583685, -0.37712207,
         0.00396319,  0.72067875, -0.3731334 ,  0.1663634 ,  0.35462943,
        -0.02185683, -0.07081314,  0.35914704, -0.50257   ,  0.3634455 ,
         0.2492299 ,  0.05221216,  0.0224544 ,  0.3421513 , -0.266856  ,
        -0.11464795, -0.5721809 ,  0.40260056,  0.03229534,  0.02184008,
         0.06418607,  0.1454651 ,  0.06930745, -0.28252113,  0.35041335,
        -0.01400429,  0.0261057 , -0.16824646,  0.08695928,  0.1683415 ,
         0.2477647 ,  0.08322021, -0.22468942, -0.18415357,  0.04487577,
         0.21132748,  0.2985532 ,  0.04803533, -0.16948755,  0.03385477,
        -0.1748507 ,  0.05769087, -0.10056674,  0.5369061 , -0.05500192,
         0.13052304, -0.1494019 , -0.19209705,  0.3066208 , -0.22679228,
         0.1470249 ,  0.11998805, -0.2915769 , -0.17528279, -0.16558684,
        -0.06659682,  0.3117205 ,  0.24292327,  0.01343942,  0.24810483,
        -0.03873776, -0.21344294,  0.02704424, -0.39740786,  0.12792398],
       dtype=float32),
 array([ 0.23112002, -0.22500591,  0.02519742,  0.17876808,  0.02872111,
         0.4178012 ,  0.0449561 ,  0.26051518, -0.2394724 ,  0.08295605,
        -0.3230626 ,  0.13422078,  0.00990328,  0.18570933, -0.19024149,
        -0.16677424,  0.24407323, -0.2767881 , -0.22234137, -0.22038904,
        -0.00071634,  0.03762939, -0.06784134,  0.38916752,  0.28262246,
         0.00119128, -0.06844786, -0.01333604, -0.03429833, -0.38089633,
        -0.03140464, -0.09164011,  0.0928975 ,  0.08016245, -0.02218838,
        -0.06093939,  0.04862459, -0.36017066, -0.04578808,  0.14433219,
        -0.0430527 ,  0.03600725,  0.07181512, -0.13988373,  0.29243758,
        -0.11435056,  0.1746194 , -0.06263874,  0.30589592, -0.01752639,
         0.05277561, -0.33847463,  0.17162049,  0.07784341,  0.06833357,
        -0.16281438, -0.23089007, -0.14622915, -0.08878224,  0.40348896,
        -0.32366902,  0.07241255, -0.39026636, -0.12891814, -0.1192936 ,
         0.0525507 ,  0.0722184 , -0.08476762, -0.2960832 , -0.20567563,
         0.11298411, -0.07674462, -0.0548819 , -0.28071046,  0.33361697,
         0.04296619, -0.25722697,  0.02173487,  0.1735607 ,  0.09368294,
         0.08840919, -0.01929654, -0.13450293,  0.20218892, -0.02517796,
         0.0474817 , -0.15516375, -0.03328793, -0.05158949,  0.14515992,
        -0.0889845 ,  0.53260136,  0.32011437, -0.040686  ,  0.09940644,
        -0.26514482,  0.19749734, -0.08387082, -0.42055768,  0.00325311],
       dtype=float32),
 array([ 0.16710177, -0.09527853,  0.05530754,  0.08282603, -0.21083245,
         0.31676573, -0.17879489,  0.23314348, -0.08271665, -0.02571096,
        -0.26642895,  0.04455076,  0.10377493,  0.06433766, -0.16112518,
        -0.06118629,  0.03086576, -0.20398574, -0.19936796, -0.02456434,
        -0.06052496, -0.07250427, -0.02744531, -0.02616965,  0.28707775,
         0.12456603, -0.18213326,  0.12214683, -0.22471538, -0.00902736,
         0.18430208, -0.19116423,  0.19489478, -0.06338657, -0.04206108,
        -0.02880312,  0.04407829, -0.43658218, -0.08629869,  0.22196369,
         0.02318107, -0.03390194,  0.19997475,  0.04026952, -0.04387381,
         0.00671662,  0.0201996 ,  0.22753558,  0.03462999, -0.10047574,
        -0.07502084, -0.5081639 ,  0.15375698, -0.08682777,  0.08867265,
        -0.07408312,  0.00170416,  0.05455551, -0.10980344,  0.32545465,
        -0.42487517, -0.04850486, -0.24741617, -0.03075092,  0.04527596,
         0.09373771,  0.08551534, -0.10956067, -0.43673235, -0.05828736,
        -0.04420122, -0.18926296, -0.14341532, -0.06548747, -0.00387489,
        -0.02995902, -0.22617516, -0.10230638, -0.15381444,  0.00808207,
         0.3038886 ,  0.03944397, -0.05458882,  0.09932055, -0.20488569,
        -0.18069676, -0.20987368, -0.29458866, -0.30008256, -0.09120661,
        -0.18624024,  0.2638088 , -0.0278824 , -0.10295628, -0.02971516,
        -0.10724349,  0.14718871,  0.05868268, -0.16000877, -0.02824761],
       dtype=float32),
 array([ 0.15785982,  0.20362315, -0.4546779 , -0.27007157,  0.11247151,
         0.4494362 ,  0.1953632 ,  0.16179489, -0.25560415,  0.03094576,
        -0.43419364,  0.11706915,  0.38621706,  0.39580038,  0.030542  ,
        -0.00747038,  0.05180216, -0.36638924, -0.19039634,  0.20486477,
         0.13366514,  0.21374646,  0.2666114 ,  0.00590628,  0.3616912 ,

In [15]:
X_embed2 = [sent_embed_tfidf(token) for token in X_tokens]
X_embed2

[array([ 5.39810571e-01, -1.63267108e-02, -3.34723341e-01,  2.10780082e-04,
         1.28492306e-02,  5.96225796e-01,  9.78287297e-02,  1.56600010e-01,
        -2.93080290e-01, -8.62237030e-02, -5.29292403e-01,  1.24439640e-01,
         1.32396636e-01,  3.34281594e-01, -2.39801207e-01,  2.42105018e-01,
         4.63566677e-02, -2.38939629e-01,  6.36984335e-02, -6.13891317e-02,
        -6.15614971e-02,  1.80698753e-01,  8.58029122e-02,  2.22408567e-01,
         4.86226051e-01,  8.98643890e-02,  6.28417737e-02,  1.20808420e-01,
         2.24022601e-01, -1.45166678e-01, -2.53360332e-01,  3.45796081e-02,
         2.60688084e-02,  2.58241135e-05, -1.07769559e-01, -2.92493854e-02,
         2.48378824e-01, -2.95590640e-01,  8.87420428e-02, -6.94806043e-02,
         2.68022020e-02, -4.16400678e-02,  4.63562419e-02,  1.48776384e-01,
         1.74009445e-01,  2.84692285e-02,  1.09732941e-01,  7.13947251e-02,
         3.22795593e-01, -3.38640961e-02, -4.84301780e-02, -7.18098818e-01,
         1.52895058e-01,  2.62287846e-01,  4.50087431e-03, -2.58709052e-01,
        -4.78470366e-02, -2.59448725e-01, -5.28511053e-02,  2.88641202e-01,
        -2.94251820e-01,  1.51832097e-01, -3.87250645e-01,  3.33211447e-02,
         3.76942323e-02,  1.34081715e-01,  8.94864228e-02, -1.48138713e-01,
        -3.59702761e-01, -1.55695295e-01,  7.63869132e-02, -6.88745237e-02,
        -2.49741306e-02, -2.52337457e-01,  1.88542363e-02,  2.79587769e-01,
        -2.15078494e-01,  2.44605185e-01,  4.23869032e-01,  1.98522475e-02,
         4.05025037e-01, -1.27981502e-01, -3.49285343e-01, -1.52992361e-01,
        -1.22092829e-01,  1.08901654e-01, -7.90880511e-02,  1.01531516e-02,
        -1.89369764e-01, -2.11547400e-01, -2.69214901e-01,  4.28667769e-01,
         8.95841575e-02, -3.56279963e-01,  3.64110355e-01,  4.48962492e-02,
         2.93016837e-01,  1.01019230e-03, -2.57304955e-01,  6.36965390e-02]),
 array([ 0.25831045, -0.00058165,  0.11719055,  0.12680619,  0.07991907,
         0.24673815, -0.03845837,  0.21469165, -0.00746171,  0.12308506,
        -0.38958426,  0.06794147,  0.21105345,  0.25872954, -0.11277663,
        -0.00907398,  0.05548901, -0.2117014 , -0.14527608, -0.12910046,
        -0.03252   , -0.01260672,  0.04063941,  0.17420526,  0.20649719,
         0.14809527, -0.18785455, -0.07170224, -0.31586893, -0.11150123,
         0.06791676, -0.16499308,  0.26362414,  0.01608228,  0.0041702 ,
        -0.04687904,  0.10761109, -0.31359219, -0.1362321 ,  0.15380824,
        -0.10828321,  0.13493212,  0.19333162, -0.22983144, -0.02796346,
         0.00482828,  0.08104915,  0.03551494,  0.20252235, -0.04666768,
         0.02287486, -0.38675803,  0.21663298, -0.02514648,  0.20353115,
        -0.15284118, -0.07633291, -0.05212771,  0.01596701,  0.37383562,
        -0.13605787, -0.00357835, -0.24631916, -0.11488149,  0.03251697,
         0.0841862 ,  0.14062736, -0.14857067, -0.31505595, -0.09804481,
         0.06488881,  0.01683982,  0.170542  , -0.20729998,  0.35540456,
         0.14187911, -0.13821658, -0.07290028, -0.11895609, -0.06090717,
         0.15171347,  0.01189094, -0.123761  ,  0.04674336,  0.03711404,
         0.06343648, -0.14461904, -0.1481687 ,  0.00955996,  0.0343944 ,
        -0.28991856,  0.47347817,  0.14300702, -0.08219504,  0.1036101 ,
        -0.30602575,  0.18259182,  0.21316806, -0.24192287, -0.05173569]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 0.17429105, -0.01691708, -0.13355292, -0.01622496, -0.00528729,
         0.23180245, -0.04316039,  0.47327683, -0.35652732, -0.40816142,
        -0.57676682,  0.19595322, -0.1694116 ,  0.28303392,  0.18909341,
        -0.13870056,  0.01476751,  0.07066437, -0.35749244,  0.11792254,
         0.21129102,  0.25416508, -0.06477546,  0.40932343,  0.25238798,
         0.07625975,  0.48127486,  0.47455184, -0.24821119, -0.18757974,
        -0.36823186, -0.08659397,  0.26182077,  0.05023979,  0.13324237,
        -0.17356076,  0.2942062 , -0.39814725, -0.08080608,  0.27798867,
         0.25410899,  0.33904429,  0.18555061, -0.03558961,  0.1293725 ,
         0.14646238,  0.14062519,  0.26014363,  0.28084634, -0.45800963,
        -0.27695245, -0.46938166, -0.0332481 , -0.05565699, -0.16862894,
         0.06522871, -0.14929171,  0.19335967,  0.08341611,  0.30492348,
        -0.18806842, -0.02678917, -0.24728296,  0.02981063, -0.24345807,
        -0.08774345, -0.01204007, -0.48883914, -0.41789319, -0.2008243 ,
        -0.11258739,  0.04151131,  0.04060721, -0.21451925,  0.53710073,
         0.09008399,  0.04167445, -0.1064673 , -0.0194577 , -0.07771968,
        -0.15680142, -0.19753187, -0.41613065, -0.03876604, -0.17856025,
        -0.00286935, -0.31457292,  0.21136156, -0.11999676, -0.07038859,
        -0.536834  ,  0.73087743,  0.14337366, -0.34608502,  0.22719105,
        -0.07711032,  0.30394229, -0.11875443, -0.22671212, -0.09062581]),
 array([ 0.14111863,  0.08976132,  0.27680697,  0.2128642 , -0.00957565,
         0.23223566, -0.0899792 ,  0.13328751, -0.15598731, -0.01422719,
        -0.33255868,  0.08322266,  0.0996146 , -0.19674938,  0.08431054,
        -0.0306709 ,  0.00996966, -0.3873068 , -0.03506482, -0.20121432,
        -0.1335552 , -0.07263598,  0.05085188,  0.01155056,  0.10050595,
        -0.14727081, -0.26483918, -0.15101785, -0.4743387 , -0.03340864,
         0.07116927, -0.2828951 ,  0.13953712,  0.27779389, -0.03518492,
         0.15688362, -0.11073702, -0.28904859,  0.19165384,  0.12501564,
        -0.22351484, -0.02421199,  0.12348188, -0.08355619, -0.01111756,
        -0.06503366, -0.10493829,  0.26808179,  0.23828211, -0.27847814,
        -0.12909158, -0.37677568,  0.14968773, -0.07883467,  0.60642182,
         0.00813723, -0.07414308,  0.10563936, -0.12583191,  0.30877958,
         0.12558708, -0.07970694, -0.31965832,  0.02740374,  0.21709225,
         0.29281639,  0.12576375, -0.16158159, -0.20382207, -0.11825789,
         0.07522608, -0.03833161, -0.27307847, -0.03054394, -0.11529274,
        -0.07468214, -0.08067261, -0.30167002, -0.3075553 , -0.17786822,
         0.0772065 , -0.01689897, -0.00655026,  0.16976262, -0.14089054,
        -0.19814271, -0.09316177, -0.67510684, -0.13045613, -0.10308543,
        -0.25483872,  0.19198643, -0.20148457, -0.16549441,  0.06887967,
        -0.24505638,  0.0936934 ,  0.06869761, -0.17500561,  0.00522555]),
 array([ 1.59893255e-01, -6.13505405e-02, -5.52088288e-02,  9.82199806e-02,
         2.97426924e-01,  4.37692703e-01,  2.68218263e-01,  3.39156213e-02,
        -1.57026934e-01,  2.35355934e-01, -5.95508154e-01,  4.78161784e-01,
        -1.64780982e-01,  3.69531357e-01, -1.87358094e-01, -2.88400155e-01,
         2.07121479e-01, -2.33030804e-01, -2.71767910e-01,  1.17280151e-01,
         2.14841659e-01,  9.59688016e-02,  1.62270705e-01,  8.75039870e-02,
         1.80386974e-01,  7.16148168e-02, -1.20154492e-01, -1.93001083e-01,
        -8.72708423e-02, -2.63724367e-01, -2.25135059e-01,  1.32648283e-01,
         1.45945380e-01,  2.23987196e-01, -1.14586587e-01, -1.42128871e-01,
         3.27433143e-01, -2.97390452e-01, -4.66692752e-02,  2.68441477e-01,
         2.30912491e-01,  3.21615760e-01,  2.68314391e-01, -3.79061129e-01,
         2.88505140e-01, -1.64337968e-01,  2.00309756e-01,  6.95954126e-03,
         4.86776292e-01, -2.79306572e-01, -2.83632703e-02, -6.07008565e-01,
         3.67913460e-01, -1.41828849e-01,  2.34511883e-01, -2.31120883e-01,
         8.81428347e-03,  5.88944577e-02, -1.92918415e-01,  6.24077490e-01,
         8.52183403e-04,  1.72083962e-01, -5.67376635e-01, -2.99090059e-01,
         6.16912250e-02,  2.84861600e-01, -1.43657820e-01, -1.43616815e-01,
        -3.98554957e-01,  1.07814389e-01,  4.29755737e-01,  1.94870735e-02,
        -2.08969486e-02, -4.81885280e-01,  2.81266180e-01,  1.41927515e-01,
         3.11241154e-02,  1.11083975e-01,  3.84971359e-01, -6.14087491e-04,
        -1.67922212e-01, -3.03692085e-01, -2.04552024e-01,  4.21867672e-01,
         1.35077703e-01,  4.87938443e-02,  1.02569914e-02,  9.41069390e-02,
        -2.91355624e-02,  3.35104312e-01, -2.79447825e-01,  3.66479283e-01,
         4.55384136e-01, -2.94048924e-01,  9.17085786e-02, -2.85773063e-01,
         2.96203271e-02, -2.06361337e-01, -8.18020157e-01, -2.41192690e-02]),
 array([ 0.0903316 ,  0.13146963,  0.09308286, -0.02453484,  0.02505487,
         0.03403434,  0.17352886,  0.19386978,  0.10247051, -0.08409873,
        -0.39713262,  0.14985707, -0.08574017,  0.00235306,  0.19477519,
        -0.03091164,  0.06667221, -0.11374853, -0.11509751,  0.01348832,
         0.14539355, -0.00383425,  0.20795963,  0.06940685,  0.29283629,
         0.13388354, -0.22258925,  0.03568461, -0.24949758, -0.26007691,
        -0.07857889, -0.20429952,  0.24816153,  0.07152479,  0.1492331 ,
        -0.05746122,  0.00344262, -0.44222507, -0.01803002,  0.10611063,
         0.13070537,  0.11970306,  0.22900886, -0.18876146,  0.06074318,
        -0.0990659 , -0.03240198,  0.0500159 ,  0.23254391, -0.00963502,
        -0.06101002, -0.33900198,  0.02019962, -0.25006743,  0.10716944,
         0.069588  , -0.0495263 ,  0.25077466, -0.12076417,  0.28190948,
        -0.19756786,  0.10602993, -0.36805449, -0.2156222 ,  0.09586834,
         0.12668192,  0.14697029, -0.16175877, -0.22092155,  0.22434432,
         0.06983199, -0.12764012, -0.13281689, -0.09305502,  0.17604504,
         0.04167623,  0.01355851, -0.24998719, -0.15732307, -0.36906008,
        -0.15254544, -0.06810943, -0.14984967,  0.28725549, -0.23435611,
         0.01932665,  0.01619607, -0.15070525, -0.04712725,  0.11721481,
        -0.13993998,  0.34682701, -0.16358409, -0.18299527,  0.03984916,
        -0.34695589,  0.0394605 ,  0.03001482, -0.12529109, -0.2372234 ]),
 array([-0.03870096, -0.09846333, -0.02611235, -0.00125278, -0.16958809,
         0.36551091, -0.16176047,  0.27295495, -0.36762274,  0.15234234,
        -0.46637445,  0.11054428,  0.32123866,  0.1363985 , -0.20067752,
         0.07185969,  0.09248049, -0.24543722,  0.01241766, -0.08254399,
         0.20852765, -0.10208822, -0.06974576,  0.03342405,  0.0564385 ,
         0.27689622, -0.2078173 , -0.15522334, -0.13644616, -0.1172507 ,
         0.28879656, -0.37631549,  0.20901248,  0.03779091, -0.15931459,
        -0.00578913,  0.06484716, -0.73277971, -0.07710214,  0.29826013,
        -0.0998843 ,  0.12466716,  0.03822273, -0.24141772, -0.06963379,
         0.00264015, -0.16145127,  0.31814214,  0.20642848, -0.04337485,
         0.00818497, -0.26343686,  0.20892572, -0.00495942,  0.18624648,
        -0.05596652,  0.10965979,  0.26006859, -0.41650835,  0.38271845,
        -0.41505264,  0.05768543, -0.35482547, -0.03105226,  0.08263749,
        -0.11201806,  0.16502322, -0.13499359, -0.32886163, -0.0625404 ,
        -0.11249541, -0.27407824,  0.01691031, -0.25590949,  0.16069092,
        -0.11288733, -0.24287722,  0.01873692, -0.04257539,  0.00850441,
         0.26594753,  0.27484574, -0.24732173,  0.4411261 , -0.05219023,
        -0.00803757, -0.15449655, -0.17890294, -0.12094879,  0.2503567 ,
        -0.24719979,  0.34856613,  0.11055514, -0.18307882,  0.01037241,
        -0.34077396,  0.24297668,  0.1362388 , -0.42023505,  0.15637904]),
 array([ 0.33321247,  0.18181439, -0.11501949,  0.06970656, -0.06995259,
         0.31606831,  0.10820592,  0.42267599, -0.38442565, -0.2508797 ,
        -0.44871544,  0.20753398, -0.08144346,  0.30042348, -0.08987914,
         0.01599017, -0.10178811, -0.17477615, -0.02440443,  0.40709383,
         0.12948638,  0.26107152,  0.07296528,  0.12877085,  0.23404648,
        -0.06036079,  0.28819136,  0.17945204, -0.28061348, -0.08198145,
        -0.16287296, -0.07978613,  0.23433995, -0.07069526, -0.09171496,
        -0.1045049 ,  0.40379768, -0.26143034, -0.1313422 ,  0.16111077,
         0.12759763,  0.18127836,  0.13790033,  0.02268077, -0.04938061,
         0.02813479,  0.19551145,  0.18440373,  0.02887204, -0.23197161,
        -0.18998138, -0.46680119, -0.27729927, -0.13935573,  0.0845293 ,
        -0.1020784 ,  0.07083294,  0.09890327, -0.10474812,  0.51110835,
        -0.17338947,  0.05224246, -0.41155533,  0.02783932, -0.10897593,
        -0.04126672,  0.15206332, -0.30652951, -0.46514539, -0.07584776,
         0.05074079,  0.09990517, -0.18461316, -0.1045777 ,  0.23354357,
         0.08949111, -0.09579369,  0.02695831, -0.2365784 , -0.16082805,
        -0.1202912 , -0.31826797, -0.36203585, -0.14705357, -0.2547396 ,
         0.20542135, -0.19993004, -0.02280426, -0.15564682,  0.00468332,
        -0.50965688,  0.17936604,  0.09039294, -0.35379087,  0.22177027,
         0.01797641,  0.15356831, -0.05605469, -0.14859933, -0.15084422]),
 array([ 0.18430684,  0.0923533 , -0.25963277, -0.20792982,  0.05576251,
         0.09872016, -0.18703468,  0.3657382 , -0.28852024,  0.01964838,
        -0.48237962,  0.50418064,  0.13513303,  0.26527579,  0.14814477,
        -0.10947548, -0.02800333, -0.01204489, -0.39621994,  0.06164937,
         0.39531357,  0.10105485, -0.0139793 ,  0.31626831,  0.17040589,
         0.24903619,  0.06706658,  0.12841293,  0.05623717,  0.03762789,
        -0.05490613, -0.08165608,  0.08100916,  0.25608072,  0.01313125,
         0.10808521,  0.09939773, -0.39369678, -0.05200459,  0.3389781 ,
         0.35601323,  0.09532263,  0.35219391, -0.25012781,  0.12462471,
        -0.11973916, -0.04186775,  0.29353429,  0.3105689 , -0.433734  ,
        -0.11999296, -0.67586809,  0.06395646, -0.07759223,  0.01468491,
         0.01528132,  0.11295316,  0.2511081 ,  0.02095004,  0.16103765,
         0.11404626,  0.01278902, -0.10139745, -0.01246135,  0.11256094,
         0.26647693,  0.12426691, -0.41614731, -0.22570317,  0.0637857 ,
        -0.07466594, -0.07189295,  0.06655235, -0.20078228,  0.22749317,
         0.0396549 ,  0.22929373,  0.02727721,  0.03275833, -0.05059295,
         0.06018228, -0.34595393, -0.18036761,  0.1193818 , -0.26095275,
        -0.03870584, -0.11654731,  0.05909386,  0.07467152, -0.01986833,
        -0.43249412,  0.26189552, -0.1669511 , -0.18244859,  0.17909143,
        -0.17361708,  0.20989716,  0.10296941, -0.23774043, -0.02412651]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([ 0.15174236, -0.41681261, -0.01437195,  0.35715882, -0.12859734,
         0.46605681,  0.20779259,  0.15611108, -0.43803564,  0.2140768 ,
        -0.47317905,  0.07463768,  0.12607767,  0.07801099, -0.47646327,
        -0.17254794,  0.45781231, -0.6364909 , -0.06263849, -0.25707634,
         0.2259445 ,  0.04666859,  0.04979621,  0.02826901, -0.06580546,
        -0.16268901, -0.32965026,  0.06263188,  0.12566776, -0.05801259,
        -0.05394813, -0.18468434,  0.21989495, -0.13633219, -0.38183047,
         0.00993438,  0.72388489, -0.36626761,  0.16801373,  0.3484386 ,
        -0.0188548 , -0.07631463,  0.37169879, -0.51091539,  0.36816105,
         0.25749995,  0.04468713,  0.02218491,  0.332785  , -0.27421227,
        -0.11360901, -0.57906876,  0.40177577,  0.0278893 ,  0.02016021,
         0.06663448,  0.15138509,  0.07008862, -0.285862  ,  0.35382566,
        -0.00584981,  0.03393769, -0.1697661 ,  0.08282316,  0.17858058,
         0.25371308,  0.08990156, -0.225908  , -0.17828551,  0.0402528 ,
         0.21070378,  0.30103884,  0.04514359, -0.1655987 ,  0.02816167,
        -0.16830433,  0.06961022, -0.10323132,  0.54398247, -0.07020279,
         0.13481428, -0.14446594, -0.1846883 ,  0.30209405, -0.24497368,
         0.15554587,  0.13209635, -0.29457092, -0.1704958 , -0.17309786,
        -0.07017245,  0.30179061,  0.22805609,  0.0211282 ,  0.25080453,
        -0.03804457, -0.21883422,  0.04382787, -0.39162072,  0.12971694]),
 array([ 0.23589932, -0.20706739, -0.02009024,  0.16776482,  0.01739666,
         0.40785948,  0.05899671,  0.24253758, -0.23346762,  0.07247663,
        -0.34030868,  0.14752852, -0.01317621,  0.21431107, -0.19248211,
        -0.17304574,  0.24194885, -0.27866063, -0.23600409, -0.2113937 ,
         0.0093553 ,  0.03751952, -0.05150553,  0.40783463,  0.32315276,
        -0.00977596, -0.09105569,  0.00661171, -0.02144114, -0.37639695,
        -0.08509304, -0.09022814,  0.06455556,  0.0816744 ,  0.01511833,
        -0.05547592,  0.06059831, -0.36209723, -0.05884575,  0.12781337,
        -0.03004464,  0.01346594,  0.06828308, -0.13323377,  0.30824201,
        -0.11500292,  0.18537085, -0.07597911,  0.27957513, -0.00619488,
         0.06002047, -0.34086677,  0.17195308,  0.09016184,  0.05374568,
        -0.17017317, -0.25190236, -0.17033401, -0.07370488,  0.42622427,
        -0.34175432,  0.07157179, -0.42097911, -0.13807277, -0.13372075,
         0.04940342,  0.07390595, -0.0700522 , -0.28061961, -0.19489623,
         0.10273255, -0.08501413, -0.05370219, -0.26086981,  0.33232042,
         0.04509544, -0.25786986,  0.06154021,  0.21394981,  0.10360063,
         0.11267768, -0.03315009, -0.13410741,  0.18400059, -0.01405731,
         0.0632931 , -0.14706423, -0.00251216, -0.03386596,  0.13424065,
        -0.0904265 ,  0.52903328,  0.3244175 , -0.07174382,  0.10758595,
        -0.25457722,  0.18839462, -0.10908556, -0.419176  ,  0.0122235 ]),
 array([ 0.15496687, -0.12678363,  0.06474854,  0.10346279, -0.25144341,
         0.32129298, -0.21868579,  0.23351175, -0.10902346, -0.0135258 ,
        -0.29002587,  0.01508876,  0.08669595,  0.10363158, -0.20129515,
        -0.06633887,  0.01662491, -0.18129585, -0.21644421,  0.01997394,
        -0.08527518, -0.09140414, -0.03072585, -0.06297185,  0.30216284,
         0.10160316, -0.20579288,  0.15299538, -0.21260301, -0.01356465,
         0.20991618, -0.19102572,  0.19939861, -0.10340728, -0.06312436,
        -0.00928384,  0.05131894, -0.45907797, -0.10894322,  0.24609701,
         0.01599633, -0.02736856,  0.21855045,  0.09487335, -0.0605639 ,
         0.01151552,  0.05751557,  0.24731084, -0.01119917, -0.12105415,
        -0.08551129, -0.52006565,  0.13713663, -0.09263794,  0.09684715,
        -0.10294124, -0.00312399,  0.07568274, -0.12393575,  0.3099313 ,
        -0.46877075, -0.04264281, -0.22834426, -0.03917682,  0.05760163,
         0.10009908,  0.11652467, -0.12654678, -0.4833551 , -0.08798697,
        -0.05321223, -0.20172774, -0.19313814, -0.11000327, -0.04069371,
        -0.02657351, -0.28690589, -0.11302702, -0.16605134,  0.03435754,
         0.28520807,  0.05226172, -0.04116852,  0.05826713, -0.23983886,
        -0.20106586, -0.1783662 , -0.28829775, -0.35629617, -0.11458447,
        -0.21296065,  0.29780994, -0.01612108, -0.12477152, -0.04659901,
        -0.10144115,  0.18959826,  0.03642438, -0.15432844, -0.03832683]),
 array([ 0.15286498,  0.22453631, -0.49893221, -0.29042571,  0.13500416,
         0.47709383,  0.21055946,  0.1608434 , -0.27516595,  0.05968428,
        -0.47252713,  0.0889204 ,  0.42182352,  0.42603964,  0.01540407,
        -0.00332781,  0.05262815, -0.3852221 , -0.19665739,  0.24180332,
         0.14065169,  0.22957714,  0.2987146 , -0.02083893,  0.38529773,
         0.20974366, -0.31093196,  0.2604093 , -0.46409686, -0.13513584,
        -0.07138722,  0.13588223,  0.11062186,  0.09991319, -0.00280937,
         0.42591089,  0.4780095 , -0.40900742,  0.06209411,  0.16693033,
         0.37835217,  0.20699006,  0.41139071,  0.1512818 ,  0.27191101,

In [16]:
svc = SVC(random_state=42)
logi = LogisticRegression(random_state=42)


def run_model(X, Y, model):
    # X는 독립변수
    # Y는 종속변수
    X_train, X_test, Y_train, Y_test = train_test_split(
        X, Y, test_size=0.2, random_state=42, stratify=Y
    )
    # 모델에 학습
    model.fit(X_train, Y_train)
    # 학습된 모델에 예측 값
    y_pred = model.predict(X_test)
    print("정확도 :", round(accuracy_score(Y_test, y_pred), 4))
    print("분류 레포트 :", classification_report(Y_test, y_pred))

In [17]:
run_model(X_embed, Y, svc)

정확도 : 0.65
분류 레포트 :               precision    recall  f1-score   support

           0       0.64      0.60      0.62        48
           1       0.65      0.69      0.67        52

    accuracy                           0.65       100
   macro avg       0.65      0.65      0.65       100
weighted avg       0.65      0.65      0.65       100

In [18]:
run_model(X_embed, Y, logi)

정확도 : 0.68
분류 레포트 :               precision    recall  f1-score   support

           0       0.67      0.67      0.67        48
           1       0.69      0.69      0.69        52

    accuracy                           0.68       100
   macro avg       0.68      0.68      0.68       100
weighted avg       0.68      0.68      0.68       100

In [19]:
run_model(X_embed2, Y, svc)

정확도 : 0.63
분류 레포트 :               precision    recall  f1-score   support

           0       0.62      0.58      0.60        48
           1       0.64      0.67      0.65        52

    accuracy                           0.63       100
   macro avg       0.63      0.63      0.63       100
weighted avg       0.63      0.63      0.63       100

- df에서 하위 10개 데이터를 이용하여 예측

In [20]:
# 학습된 모델에 예측의 값을 반환하는 함수
# 세번째 매개변수(vec_type)를 생성 -> 기본값은 'mean'
# 'tfidf' 입력이 들어온다면 벡터화 작업을 w2v + tfidf 융합한 벡터화
def predict_sentence_list(sentences, model, vec_type='mean'):
    # sentences : 문장들의 리스트
    # 문장들을 토큰화 -> 임베딩
    X_test = []
    for sent in sentences:
        # token() 함수를 호출하여 토큰화
        tokens = tokenize(sent)
        # 토큰화된 문장을 sent_embed_mean 함수에 입력하여 호출(단위 벡터의 평균)
        if vec_type == 'mean':
            vec = sent_embed_mean(tokens)
        elif vec_type == 'tfidf':
            vec = sent_embed_tfidf(tokens)
        X_test.append(vec)
    
    preds = model.predict(X_test)
    result = []
    for sent, pred in zip(sentences, preds):
        label = '긍정' if pred == 1 else '부정'
        result.append([sent, label])
    return result

In [21]:
# 모델 학습 -> 예측
X_test = df['document'].tail(10).values
run_model(X_embed, Y, svc)

predict_sentence_list(X_test, svc, vec_type='mean')

정확도 : 0.65
분류 레포트 :               precision    recall  f1-score   support

           0       0.64      0.60      0.62        48
           1       0.65      0.69      0.67        52

    accuracy                           0.65       100
   macro avg       0.65      0.65      0.65       100
weighted avg       0.65      0.65      0.65       100

[['이걸 영화라고 찎었냐?', '긍정'],
 ['http://blog.naver.com/oroblast/220215679580 나쁜 인상은 아니지만,오랫동안 기억에 남아....종종 떠올라서....조금은 사람을 피곤하게 만드는 영화. ^^',
  '긍정'],
 ['공포나 재난영화가 아니라 아예 대놓고 비급 크리쳐개그물임ㅋㅋ 음악 완전 흥겹다ㅋ 5점정도가 적당한 거 같은데 평점이 좀 높아서ㅋㅋ',
  '긍정'],
 ['For Carl.칼 세이건으로 시작해서 칼 세이건으로 끝난다.', '부정'],
 ['디케이드 다음에 더블 다음에 오즈인데 더블은 조금밖에 안나오네요.', '부정'],
 ['인간이 문제지.. 소는 뭔죄인가..', '긍정'],
 ['평점이 너무 낮아서...', '긍정'],
 ['이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?', '부정'],
 ['청춘 영화의 최고봉.방황과 우울했던 날들의 자화상', '부정'],
 ['한국 영화 최초로 수간하는 내용이 담긴 영화', '부정']]

In [22]:
run_model(X_embed2, Y, logi)
predict_sentence_list(X_test, logi, vec_type = 'tfidf')

정확도 : 0.67
분류 레포트 :               precision    recall  f1-score   support

           0       0.65      0.67      0.66        48
           1       0.69      0.67      0.68        52

    accuracy                           0.67       100
   macro avg       0.67      0.67      0.67       100
weighted avg       0.67      0.67      0.67       100

[['이걸 영화라고 찎었냐?', '긍정'],
 ['http://blog.naver.com/oroblast/220215679580 나쁜 인상은 아니지만,오랫동안 기억에 남아....종종 떠올라서....조금은 사람을 피곤하게 만드는 영화. ^^',
  '긍정'],
 ['공포나 재난영화가 아니라 아예 대놓고 비급 크리쳐개그물임ㅋㅋ 음악 완전 흥겹다ㅋ 5점정도가 적당한 거 같은데 평점이 좀 높아서ㅋㅋ',
  '긍정'],
 ['For Carl.칼 세이건으로 시작해서 칼 세이건으로 끝난다.', '부정'],
 ['디케이드 다음에 더블 다음에 오즈인데 더블은 조금밖에 안나오네요.', '부정'],
 ['인간이 문제지.. 소는 뭔죄인가..', '긍정'],
 ['평점이 너무 낮아서...', '긍정'],
 ['이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?', '부정'],
 ['청춘 영화의 최고봉.방황과 우울했던 날들의 자화상', '부정'],
 ['한국 영화 최초로 수간하는 내용이 담긴 영화', '부정']]